import test from 'node:test';
import assert from 'node:assert/strict';
import { server } from '../server.js';
import { reset, load, mutate } from '../src/store.js';
import { dailyFor } from '../src/game.js';

let base;
class Client{
 constructor(){this.cookie='';this.csrf=''}
 async request(path,{method='GET',body,headers={}}={}){const h={...headers};if(body!==undefined)h['content-type']='application/json';if(this.cookie)h.cookie=this.cookie;if(method!=='GET'&&this.csrf)h['x-csrf-token']=this.csrf;const r=await fetch(base+path,{method,headers:h,body:body===undefined?undefined:JSON.stringify(body)});const sc=r.headers.get('set-cookie');if(sc)this.cookie=sc.split(';')[0];let d;try{d=await r.json()}catch{d=null}return {status:r.status,data:d,headers:r.headers}}
 async login(email,password){const r=await this.request('/api/auth/login',{method:'POST',body:{email,password}});assert.equal(r.status,200);this.csrf=r.data.csrf;return r.data.user}
}
test.before(async()=>{reset();await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}`});
test.after(async()=>{await new Promise(r=>server.close(r))});

test('public config exposes centralized bit and plan prices',async()=>{const c=new Client(),r=await c.request('/api/public-config');assert.equal(r.status,200);assert.equal(r.data.bitPhone,'0526262828');assert.equal(r.data.prices.basic,9);assert.equal(r.data.prices.plus,19);assert.equal(r.data.prices.pro,39);assert.equal(r.data.plans.free.features.canPlayFull3DGames,false);assert.equal(r.data.plans.basic.features.canPlayFull3DGames,true)});

test('free user is blocked from full game and gets preview metadata',async()=>{const c=new Client();const u=await c.login('demo@levelup.local','Demo1234');assert.equal(u.planId,'free');const daily=await c.request('/api/game/daily');assert.equal(daily.status,200);assert.equal(daily.data.canPlay,false);const start=await c.request('/api/game/start',{method:'POST',body:{}});assert.equal(start.status,403);assert.equal(start.data.error.code,'upgrade_required')});

test('task completion grants XP only once',async()=>{const c=new Client();await c.login('demo@levelup.local','Demo1234');const before=(await c.request('/api/auth/me')).data.user.xp;const first=await c.request('/api/tasks/css/complete',{method:'POST',body:{text:'יצרתי variables ועיצוב',difficulty:'right'}});assert.equal(first.status,200);assert.equal(first.data.alreadyCompleted,false);const after1=first.data.user.xp;assert(after1>before);const second=await c.request('/api/tasks/css/complete',{method:'POST',body:{text:'שוב',difficulty:'right'}});assert.equal(second.status,200);assert.equal(second.data.alreadyCompleted,true);assert.equal(second.data.user.xp,after1)});

test('manual bit proof does not activate before admin approval, then refreshes permission',async()=>{const user=new Client();await user.login('demo@levelup.local','Demo1234');const order=await user.request('/api/orders',{method:'POST',body:{planId:'basic'}});assert.equal(order.status,201);assert.equal(order.data.order.priceNis,9);assert.equal(order.data.order.status,'awaiting_payment');let me=(await user.request('/api/auth/me')).data.user;assert.equal(me.planId,'free');const pixel='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=';const proof=await user.request(`/api/orders/${order.data.order.id}/proof`,{method:'POST',body:{name:'proof.png',dataUrl:pixel}});assert.equal(proof.status,200);me=(await user.request('/api/auth/me')).data.user;assert.equal(me.planId,'free');
 const admin=new Client();await admin.login('admin@levelup.local','Admin1234');const summary=await admin.request('/api/admin/summary');const row=summary.data.orders.find(x=>x.id===order.data.order.id);assert(row);assert.equal(row.status,'under_review');assert.equal(row.proofs.length,1);const approve=await admin.request(`/api/admin/orders/${row.id}/approve`,{method:'POST',body:{note:'בדיקת Demo'}});assert.equal(approve.status,200);me=(await user.request('/api/auth/me')).data.user;assert.equal(me.planId,'basic');assert.equal(me.features.canPlayFull3DGames,true);
 const twice=await admin.request(`/api/admin/orders/${row.id}/approve`,{method:'POST',body:{}});assert.equal(twice.status,409)});

test('basic game start hides answers and finish is server validated + idempotent',async()=>{const c=new Client();await c.login('demo@levelup.local','Demo1234');const start=await c.request('/api/game/start',{method:'POST',body:{}});assert.equal(start.status,201);assert.equal('answerIndex' in start.data.game.questions[0],false);mutate(db=>{const a=db.daily_game_attempts.find(x=>x.id===start.data.attemptId);a.started_at=new Date(Date.now()-5000).toISOString()});const db=load(),profile=db.profiles.find(x=>x.userId===db.users.find(u=>u.email==='demo@levelup.local').id),en=db.path_enrollments.find(x=>x.userId===profile.userId&&x.active),g=dailyFor(profile,en,start.data.game.gameMode);for(const q of g.questions){const ans=await c.request('/api/game/answer',{method:'POST',body:{attemptId:start.data.attemptId,nonce:start.data.nonce,questionId:q.id,answerIndex:q.answerIndex,usedHint:false}});assert.equal(ans.status,200);assert.equal(ans.data.correct,true)}const fin=await c.request('/api/game/finish',{method:'POST',body:{attemptId:start.data.attemptId,nonce:start.data.nonce}});assert.equal(fin.status,200);assert.equal(fin.data.result.correct,g.questions.length);assert(fin.data.result.score>0);const dup=await c.request('/api/game/finish',{method:'POST',body:{attemptId:start.data.attemptId,nonce:start.data.nonce}});assert.equal(dup.status,400)});

test('minor registration requires demo parent consent before onboarding',async()=>{const c=new Client(),email=`minor${Date.now()}@example.com`;const reg=await c.request('/api/auth/register',{method:'POST',body:{email,password:'Minor1234',displayName:'משתמש צעיר',birthYear:new Date().getFullYear()-13,acceptTerms:true}});assert.equal(reg.status,201);c.csrf=reg.data.csrf;const status=await c.request('/api/parental-consent');assert.equal(status.data.required,true);const on=await c.request('/api/onboarding',{method:'POST',body:{skill:'תכנות',goal:'לבנות אתר',level:'beginner',dailyMinutes:20,targetDate:'2026-12-01',styles:['practice']}});assert.equal(on.status,403);assert.equal(on.data.error.code,'parental_consent_required');const consent=await c.request('/api/parental-consent',{method:'POST',body:{guardianEmail:'guardian@example.com',guardianConfirmed:true}});assert.equal(consent.status,200);const on2=await c.request('/api/onboarding',{method:'POST',body:{skill:'תכנות',goal:'לבנות אתר',level:'beginner',dailyMinutes:20,targetDate:'2026-12-01',styles:['practice']}});assert.equal(on2.status,201)});

test('marketplace favorite and report persist',async()=>{const c=new Client();await c.login('basic@levelup.local','Basic1234');const list=await c.request('/api/marketplace');assert(list.data.paths.length>=8);const id=list.data.paths[0].id;const f=await c.request(`/api/marketplace/${id}/favorite`,{method:'POST',body:{}});assert.equal(f.data.favorite,true);const rep=await c.request(`/api/marketplace/${id}/report`,{method:'POST',body:{reason:'בדיקת דיווח'}});assert.equal(rep.status,201)});

test('weekly challenge can be joined without open chat',async()=>{const c=new Client();await c.login('basic@levelup.local','Basic1234');const list=await c.request('/api/challenges');assert.equal(list.status,200);assert(list.data.challenges.length>=1);const ch=list.data.challenges[0];const join=await c.request(`/api/challenges/${ch.id}/join`,{method:'POST',body:{}});assert.equal(join.status,200);const after=await c.request('/api/challenges');assert.equal(after.data.challenges.find(x=>x.id===ch.id).joined,true)});

test('creator moderation and paid marketplace purchase use manual bit approval',async()=>{
 const free=new Client();await free.login('demo@levelup.local','Demo1234');const denied=await free.request('/api/marketplace/create',{method:'POST',body:{title:'לא אמור להתפרסם',description:'x'.repeat(20),category:'תכנות',price:5,durationDays:7}});assert.equal(denied.status,403);
 const admin=new Client();await admin.login('admin@levelup.local','Admin1234');const created=await admin.request('/api/marketplace/create',{method:'POST',body:{title:'מסלול Creator Test',description:'מסלול בדיקה עם תוכן ייחודי לצורך אימות מערכת היוצרים.',category:'תכנות',difficulty:'beginner',durationDays:10,price:12}});assert.equal(created.status,201);assert.equal(created.data.path.status,'pending');const mid=created.data.path.id;const approvedPath=await admin.request(`/api/admin/marketplace/${mid}/approve`,{method:'POST',body:{}});assert.equal(approvedPath.status,200);assert.equal(approvedPath.data.path.status,'approved');
 const buyer=new Client();await buyer.login('basic@levelup.local','Basic1234');const buy=await buyer.request(`/api/marketplace/${mid}/order`,{method:'POST',body:{}});assert.equal(buy.status,201);assert.equal(buy.data.order.type,'marketplace');assert.equal(buy.data.order.priceNis,12);const pixel='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=';const proof=await buyer.request(`/api/orders/${buy.data.order.id}/proof`,{method:'POST',body:{name:'market.png',dataUrl:pixel}});assert.equal(proof.status,200);const approveOrder=await admin.request(`/api/admin/orders/${buy.data.order.id}/approve`,{method:'POST',body:{note:'creator sale test'}});assert.equal(approveOrder.status,200);
 const owned=await buyer.request('/api/marketplace');const row=owned.data.paths.find(x=>x.id===mid);assert.equal(row.started,true);const path=await buyer.request(`/api/path/${row.pathSlug}`);assert.equal(path.status,200);assert.equal(path.data.enrollment.active,false);const activate=await buyer.request(`/api/path/${row.pathSlug}/activate`,{method:'POST',body:{}});assert.equal(activate.status,200);const complete=await buyer.request('/api/tasks/creator-goal/complete',{method:'POST',body:{text:'הגדרתי יעד',difficulty:'right'}});assert.equal(complete.status,200);const review=await buyer.request(`/api/marketplace/${mid}/review`,{method:'POST',body:{rating:5,body:'מסלול בדיקה טוב'}});assert.equal(review.status,200);assert.equal(review.data.rating,5);
});
