import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import { URL } from 'node:url';
import { config, plans, hasFeature } from './src/config.js';
import { load, save, mutate, root } from './src/store.js';
import { id, hashPassword, verifyPassword, makeSession, readSession, csrfFor, safeText, isEmail, strongPassword, parseCookies } from './src/security.js';
import { pathTemplates, categories, gameModes, worlds } from './src/catalog.js';
import { dailyFor, validateAttempt, newAttemptId } from './src/game.js';
import { coachReply, generatePath } from './src/ai.js';
import { paymentInstructions } from './src/payment.js';

const publicDir=path.join(root,'public');
const uploadDir=path.join(root,'data','uploads');
const rates=new Map();
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json','.svg':'image/svg+xml','.png':'image/png','.ico':'image/x-icon'};
const now=()=>new Date().toISOString();
const json=(res,status,data,extra={})=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...extra});res.end(JSON.stringify(data));};
const err=(res,status,code,message,details)=>json(res,status,{ok:false,error:{code,message,details}});
const ok=(res,data={},status=200,extra={})=>json(res,status,{ok:true,...data},extra);
const audit=(db,actorId,action,targetType,targetId,meta={})=>db.admin_actions.push({id:id('audit'),actorId,action,targetType,targetId,meta,created_at:now()});
function securityHeaders(res){
 res.setHeader('x-content-type-options','nosniff'); res.setHeader('referrer-policy','strict-origin-when-cross-origin'); res.setHeader('x-frame-options','DENY'); res.setHeader('permissions-policy','camera=(), microphone=(), geolocation=()');
 res.setHeader('content-security-policy',"default-src 'self'; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline'; script-src 'self'; connect-src 'self'; font-src 'self' data:; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; form-action 'self'");
}
function rate(req,res,limit=120,windowMs=60000){const ip=req.socket.remoteAddress||'local',key=`${ip}:${Math.floor(Date.now()/windowMs)}`,n=(rates.get(key)||0)+1;rates.set(key,n);if(n>limit){err(res,429,'rate_limited','יותר מדי בקשות. נסה שוב בעוד רגע.');return false}return true;}
async function body(req,max=6*1024*1024){return await new Promise((resolve,reject)=>{let size=0,b='';req.on('data',c=>{size+=c.length;if(size>max){reject(new Error('body_too_large'));req.destroy();return}b+=c});req.on('end',()=>{if(!b)return resolve({});try{resolve(JSON.parse(b))}catch{reject(new Error('invalid_json'))}});req.on('error',reject)});}
function auth(req){const cookies=parseCookies(req.headers.cookie||''),token=cookies.levelup_session||'',session=readSession(token);if(!session)return {user:null,profile:null,token,csrf:''};const db=load(),user=db.users.find(x=>x.id===session.userId&&!x.deleted_at&&!x.blocked_at),profile=db.profiles.find(x=>x.userId===user?.id);return {user,profile,token,csrf:csrfFor(token)};}
function requireAuth(req,res){const a=auth(req);if(!a.user){err(res,401,'unauthorized','יש להתחבר כדי להמשיך.');return null}return a;}
function requireCsrf(req,res,a){if(req.method==='GET'||req.method==='HEAD')return true;if(!a?.user)return false;if(req.headers['x-csrf-token']!==a.csrf){err(res,403,'csrf_invalid','הבקשה לא אושרה. רענן את הדף ונסה שוב.');return false}return true;}
function requireAdmin(req,res){const a=requireAuth(req,res);if(!a)return null;if(a.user.role!=='admin'){err(res,403,'admin_required','אין הרשאת מנהל.');return null}return a;}
function setSession(res,userId){const token=makeSession(userId),csrf=csrfFor(token);return {token,csrf,cookie:`levelup_session=${encodeURIComponent(token)}; Path=/; HttpOnly; SameSite=Strict; Max-Age=2592000${process.env.NODE_ENV==='production'?'; Secure':''}`};}
function publicUser(user,profile){return {id:user.id,email:user.email,role:user.role,emailVerified:user.emailVerified,displayName:profile?.displayName,planId:profile?.planId||'free',xp:profile?.xp||0,coins:profile?.coins||0,level:profile?.level||1,streak:profile?.streak||0,birthYear:profile?.birthYear,privacy:profile?.privacy||'private',locale:profile?.locale||'he',coachStyle:profile?.coachStyle||'supportive',theme:profile?.theme||'dark',features:plans[profile?.planId||'free'].features};}
function activeEnrollment(db,userId){return db.path_enrollments.find(x=>x.userId===userId&&x.active&&x.primary===true&&!x.deleted_at)||db.path_enrollments.find(x=>x.userId===userId&&x.active&&!x.deleted_at);}
function pathDetail(slug,db=load()){
 const fixed=pathTemplates.find(p=>p.slug===slug);if(fixed)return fixed;
 const gen=db.generated_paths.find(x=>x.slug===slug);if(gen)return gen;
 const mp=db.marketplace_paths.find(x=>x.pathSlug===slug&&x.status==='approved');if(!mp)return null;
 const mk=(id,title,goal,xp=90)=>({id,title,summary:goal,goal,minutes:25,instructions:['קרא את מטרת השלב.','בצע דוגמה אחת שמתאימה לפרויקט שלך.','שמור תוצאה או קישור שמוכיחים השלמה.'],example:`תוצר לדוגמה עבור ${title}`,hints:['בחר גרסה קטנה שאפשר לסיים היום.','בדוק את התוצאה מול המטרה לפני שממשיכים.'],resources:[],completion:`קיים תוצר שמדגים: ${goal}`,quiz:{prompt:`מה הדבר החשוב ביותר בשלב “${title}”?`,options:['תוצאה שאפשר לבדוק','להוסיף צבעים','לדלג על בדיקה','להגדיל את היקף הפרויקט'],answerIndex:0,explanation:'התקדמות טובה נמדדת בתוצאה שאפשר לבדוק.'},xp,coins:Math.round(xp/6)});
 return {slug:mp.pathSlug,marketplacePathId:mp.id,title:mp.title,category:mp.category,difficulty:mp.difficulty,durationDays:mp.durationDays,dailyMinutes:30,goal:`להשלים פרויקט בנושא ${mp.title}`,description:mp.description,achievement:'מסלול יוצר הושלם',chapters:[{id:'creator-foundation',title:'הגדרת היעד',tasks:[mk('creator-goal','הגדרת תוצאה','לנסח תוצאה מדידה למסלול'),mk('creator-baseline','בדיקת נקודת פתיחה','לתעד מה כבר ידוע ומה חסר')]},{id:'creator-practice',title:'תרגול ממוקד',tasks:[mk('creator-practice-1','תרגול ראשון','לבצע תרגול קצר לפי נושא המסלול',110),mk('creator-practice-2','חיזוק נקודה חלשה','לחזור על טעות אחת ולתקן אותה',120)]},{id:'creator-project',title:'פרויקט',tasks:[mk('creator-build','בניית תוצר','להכין גרסה ראשונה של פרויקט הסיום',140),mk('creator-review','בדיקה ושיפור','לבצע סבב QA ולסכם מה השתפר',160)]}],finalProject:`פרויקט מסכם: ${mp.title}`};
}
function calcProgress(tpl,completed=[]){const all=tpl?.chapters.flatMap(c=>c.tasks)||[];return all.length?Math.round(completed.filter(id=>all.some(t=>t.id===id)).length/all.length*100):0;}
function updateLevel(profile){profile.level=Math.max(1,Math.floor((profile.xp||0)/500)+1);}
function updateStreak(db,userId){let s=db.streaks.find(x=>x.userId===userId);const today=new Date().toISOString().slice(0,10);if(!s){s={id:id('streak'),userId,current:1,best:1,lastDate:today,created_at:now(),updated_at:now()};db.streaks.push(s)}else if(s.lastDate!==today){const prev=new Date(s.lastDate),cur=new Date(today),days=Math.round((cur-prev)/86400000);s.current=days===1?s.current+1:1;s.best=Math.max(s.best,s.current);s.lastDate=today;s.updated_at=now()}const p=db.profiles.find(x=>x.userId===userId);if(p)p.streak=s.current;}
function grantXp(db,userId,amount,reason,key){if(db.xp_events.some(x=>x.userId===userId&&x.idempotencyKey===key))return false;db.xp_events.push({id:id('xp'),userId,amount,reason,idempotencyKey:key,created_at:now()});const p=db.profiles.find(x=>x.userId===userId);p.xp=(p.xp||0)+amount;updateLevel(p);return true;}
function grantCoins(db,userId,amount){const p=db.profiles.find(x=>x.userId===userId);p.coins=(p.coins||0)+amount;}
function checkAchievement(db,userId,achievementId){if(db.user_achievements.some(x=>x.userId===userId&&x.achievementId===achievementId))return;db.user_achievements.push({id:id('ua'),userId,achievementId,created_at:now()});}
function validPlan(id){return ['basic','plus','pro'].includes(id)}
function fileData(dataUrl,maxBytes=5*1024*1024){const m=String(dataUrl||'').match(/^data:(image\/(?:png|jpeg|webp)|application\/pdf);base64,([A-Za-z0-9+/=]+)$/);if(!m)return {error:'file_type'};const buf=Buffer.from(m[2],'base64');if(buf.length>maxBytes)return {error:'file_size'};return {mime:m[1],buf,ext:m[1]==='application/pdf'?'.pdf':m[1]==='image/png'?'.png':m[1]==='image/webp'?'.webp':'.jpg'};}

async function api(req,res,u){
 const p=u.pathname;
 if(p==='/api/health'&&req.method==='GET')return ok(res,{status:'healthy',demoMode:config.demoMode,version:'1.0.0'});
 if(p==='/api/public-config'&&req.method==='GET')return ok(res,{demoMode:config.demoMode,bitPhone:config.bitPhone,bitUrl:config.bitUrl,prices:config.prices,plans,gameModes,worlds,categories});
 if(p==='/api/catalog'&&req.method==='GET')return ok(res,{paths:pathTemplates.map(x=>({...x,chapters:x.chapters.map(c=>({...c,tasks:c.tasks.map(t=>({...t,quiz:{...t.quiz,answerIndex:undefined}}))}))}))});
 if(p==='/api/auth/register'&&req.method==='POST'){
  if(!rate(req,res,20))return; const b=await body(req,1024*50); const email=String(b.email||'').toLowerCase().trim(),name=safeText(b.displayName,60),year=Number(b.birthYear);
  if(!isEmail(email))return err(res,400,'email_invalid','כתובת האימייל אינה תקינה.'); if(!strongPassword(b.password))return err(res,400,'password_weak','הסיסמה צריכה להכיל לפחות 8 תווים, אות ומספר.'); if(!name)return err(res,400,'name_required','יש להזין שם תצוגה.'); if(!Number.isInteger(year)||year<1900||year>new Date().getFullYear())return err(res,400,'birth_year_invalid','שנת הלידה אינה תקינה.'); if(!b.acceptTerms)return err(res,400,'terms_required','יש לאשר את תנאי השימוש והפרטיות.');
  const db=load(); if(db.users.some(x=>x.email===email&&!x.deleted_at))return err(res,409,'email_exists','כבר קיים חשבון עם כתובת זו.'); const userId=id('usr'),verifyToken=id('verify');
  db.users.push({id:userId,email,passwordHash:hashPassword(b.password),role:'user',emailVerified:config.demoMode,created_at:now(),updated_at:now()}); db.profiles.push({userId,displayName:name,birthYear:year,planId:'free',xp:0,coins:0,level:1,streak:0,privacy:year>new Date().getFullYear()-18?'private':'private',locale:'he',coachStyle:'supportive',theme:'dark',created_at:now(),updated_at:now()}); db.email_verifications.push({id:id('ev'),userId,token:verifyToken,expires_at:new Date(Date.now()+86400000).toISOString(),used_at:config.demoMode?now():null}); if(year>new Date().getFullYear()-16)db.parental_consents.push({id:id('pc'),userId,status:'required',created_at:now(),updated_at:now()}); save(db);
  const s=setSession(res,userId); return ok(res,{user:publicUser(db.users.at(-1),db.profiles.at(-1)),csrf:s.csrf,verificationRequired:!config.demoMode,demoVerificationUrl:config.demoMode?`/verify?token=${verifyToken}`:undefined},201,{'set-cookie':s.cookie});
 }
 if(p==='/api/auth/login'&&req.method==='POST'){
  if(!rate(req,res,30))return; const b=await body(req,1024*20),email=String(b.email||'').toLowerCase().trim(),db=load(),user=db.users.find(x=>x.email===email&&!x.deleted_at);if(!user||!verifyPassword(String(b.password||''),user.passwordHash))return err(res,401,'login_failed','אימייל או סיסמה שגויים.');const profile=db.profiles.find(x=>x.userId===user.id);const s=setSession(res,user.id);return ok(res,{user:publicUser(user,profile),csrf:s.csrf},200,{'set-cookie':s.cookie});
 }
 if(p==='/api/auth/logout'&&req.method==='POST'){const a=auth(req);if(a.user&&!requireCsrf(req,res,a))return;return ok(res,{},200,{'set-cookie':'levelup_session=; Path=/; HttpOnly; SameSite=Strict; Max-Age=0'});}
 if(p==='/api/auth/me'&&req.method==='GET'){const a=auth(req);return ok(res,{user:a.user?publicUser(a.user,a.profile):null,csrf:a.csrf||null});}
 if(p==='/api/auth/verify'&&req.method==='POST'){const b=await body(req,1024*20),db=load(),v=db.email_verifications.find(x=>x.token===b.token&&!x.used_at&&new Date(x.expires_at)>new Date());if(!v)return err(res,400,'token_invalid','קישור האימות אינו תקין או שפג.');v.used_at=now();const user=db.users.find(x=>x.id===v.userId);user.emailVerified=true;user.updated_at=now();save(db);return ok(res,{message:'האימייל אומת.'});}
 if(p==='/api/auth/forgot'&&req.method==='POST'){const b=await body(req,1024*20),email=String(b.email||'').toLowerCase().trim(),db=load(),user=db.users.find(x=>x.email===email&&!x.deleted_at);let token;if(user){token=id('reset');db.password_resets.push({id:id('pr'),userId:user.id,token,expires_at:new Date(Date.now()+3600000).toISOString(),used_at:null});save(db)}return ok(res,{message:'אם החשבון קיים, נשלחו הוראות שחזור.',demoResetToken:config.demoMode?token:undefined});}
 if(p==='/api/auth/reset'&&req.method==='POST'){const b=await body(req,1024*20);if(!strongPassword(b.password))return err(res,400,'password_weak','הסיסמה חלשה מדי.');const db=load(),r=db.password_resets.find(x=>x.token===b.token&&!x.used_at&&new Date(x.expires_at)>new Date());if(!r)return err(res,400,'token_invalid','קישור האיפוס אינו תקין או שפג.');const user=db.users.find(x=>x.id===r.userId);user.passwordHash=hashPassword(b.password);user.updated_at=now();r.used_at=now();save(db);return ok(res,{message:'הסיסמה עודכנה.'});}

 const a=requireAuth(req,res); if(!a)return; if(!requireCsrf(req,res,a))return;
 if(p==='/api/parental-consent'&&req.method==='GET'){const db=load(),c=db.parental_consents.find(x=>x.userId===a.user.id);return ok(res,{consent:c?{status:c.status,guardianEmail:c.guardianEmail||null}:null,required:Boolean(c&&c.status==='required')});}
 if(p==='/api/parental-consent'&&req.method==='POST'){const b=await body(req,1024*20),db=load(),c=db.parental_consents.find(x=>x.userId===a.user.id);if(!c)return ok(res,{required:false});if(c.status!=='required')return ok(res,{consent:c});const guardianEmail=String(b.guardianEmail||'').toLowerCase().trim();if(!isEmail(guardianEmail)||!b.guardianConfirmed)return err(res,400,'guardian_invalid','יש להזין אימייל של הורה/אפוטרופוס ולאשר שהטופס מולא בהסכמתו.');if(!config.demoMode)return err(res,501,'external_consent_required','במצב Production נדרש שירות אימות הורה חיצוני לפני אישור.');c.guardianEmail=guardianEmail;c.status='approved_demo';c.verified_at=now();c.updated_at=now();save(db);return ok(res,{consent:c,demo:true,message:'הסכמת ההורה נשמרה במצב Demo.'});}
 if(p==='/api/dashboard'&&req.method==='GET'){
  const db=load(),en=activeEnrollment(db,a.user.id),tpl=en&&pathDetail(en.pathSlug),nextTask=tpl?.chapters.flatMap(c=>c.tasks).find(t=>!en.completedTaskIds.includes(t.id)),ach=db.user_achievements.filter(x=>x.userId===a.user.id).map(x=>db.achievements.find(y=>y.id===x.achievementId)).filter(Boolean),recent=db.xp_events.filter(x=>x.userId===a.user.id).slice(-8).reverse();const game=dailyFor(a.profile,en);
  return ok(res,{user:publicUser(a.user,a.profile),enrollment:en?{...en,path:tpl,nextTask}:null,achievements:ach,recentXp:recent,dailyGame:{...game,questions:game.questions.map(q=>({...q,answerIndex:undefined,explanation:undefined}))},notifications:db.notifications.filter(x=>x.userId===a.user.id).slice(-10).reverse(),challenges:db.challenges.filter(x=>x.status==='active').map(c=>({...c,joined:db.challenge_participants.some(p=>p.challengeId===c.id&&p.userId===a.user.id)}))});
 }
 if(p==='/api/onboarding'&&req.method==='POST'){
  const b=await body(req,1024*100),skill=safeText(b.skill,100),goal=safeText(b.goal,180),level=['beginner','intermediate','advanced'].includes(b.level)?b.level:'beginner',daily=[10,20,30,60].includes(Number(b.dailyMinutes))?Number(b.dailyMinutes):20,targetDate=String(b.targetDate||''),styles=Array.isArray(b.styles)?b.styles.slice(0,7):[];if(!skill||!goal||!/^\d{4}-\d{2}-\d{2}$/.test(targetDate))return err(res,400,'onboarding_invalid','יש להשלים מיומנות, מטרה ותאריך יעד.');
  const pre=load(),consent=pre.parental_consents.find(x=>x.userId===a.user.id);if(consent?.status==='required')return err(res,403,'parental_consent_required','נדרשת הסכמת הורה לפני יצירת מסלול.');if(pre.path_enrollments.filter(x=>x.userId===a.user.id&&x.active&&!x.deleted_at).length>=plans[a.profile.planId].activePathLimit)return err(res,403,'path_limit','הגעת למספר המסלולים הפעילים בתוכנית שלך.');
  let tpl=null,generated=null;
  try{generated=await generatePath({skill,goal,level,dailyMinutes:daily,targetDate,styles,slug:`ai-${id('path')}`});}catch(e){console.error('path_generation_failed, falling back to template:',e?.message||e);}
  const db=load();
  if(!generated){tpl=pathTemplates.find(x=>x.title.includes(skill)||x.category.includes(skill))||pathTemplates.find(x=>x.category===b.category)||pathTemplates[0];}
  else{tpl=generated;db.generated_paths.push({...generated,ownerId:a.user.id,created_at:now()});}
  const current=db.path_enrollments.filter(x=>x.userId===a.user.id&&x.active&&!x.deleted_at);if(current.length>=plans[a.profile.planId].activePathLimit)return err(res,403,'path_limit','הגעת למספר המסלולים הפעילים בתוכנית שלך.');
  current.forEach(x=>x.primary=false);const en={id:id('enr'),userId:a.user.id,pathSlug:tpl.slug,category:tpl.category,customSkill:skill,customGoal:goal,level,dailyMinutes:daily,targetDate,styles,progress:0,completedTaskIds:[],active:true,primary:true,started_at:now(),created_at:now(),updated_at:now()};db.path_enrollments.push(en);save(db);return ok(res,{enrollment:{...en,path:tpl},generated:Boolean(generated),aiQuestions:[]},201);
 }
 if(p.startsWith('/api/path/')&&req.method==='GET'){
  const slug=decodeURIComponent(p.split('/')[3]||''),db=load(),tpl=pathDetail(slug,db);if(!tpl)return err(res,404,'path_not_found','המסלול לא נמצא.');const en=db.path_enrollments.find(x=>x.userId===a.user.id&&x.pathSlug===slug&&!x.deleted_at);if(tpl.marketplacePathId&&!en&&a.user.role!=='admin'&&db.marketplace_paths.find(x=>x.id===tpl.marketplacePathId)?.creatorId!==a.user.id)return err(res,403,'purchase_required','יש לרכוש או להוסיף את המסלול לפני פתיחתו.');if(tpl.generated&&!en&&a.user.role!=='admin')return err(res,404,'path_not_found','המסלול לא נמצא.');return ok(res,{path:tpl,enrollment:en||null,isPrimary:Boolean(en&&(en.primary===true||activeEnrollment(db,a.user.id)?.id===en.id))});
 }
 if(p.startsWith('/api/path/')&&p.endsWith('/activate')&&req.method==='POST'){const slug=decodeURIComponent(p.split('/')[3]||''),db=load(),en=db.path_enrollments.find(x=>x.userId===a.user.id&&x.pathSlug===slug&&!x.deleted_at);if(!en)return err(res,404,'enrollment_not_found','המסלול לא נוסף לחשבון.');const active=db.path_enrollments.filter(x=>x.userId===a.user.id&&x.active&&!x.deleted_at&&x.id!==en.id),limit=plans[a.profile.planId].activePathLimit;if(!en.active&&active.length>=limit){if(limit===1)active.forEach(x=>{x.active=false;x.primary=false});else return err(res,403,'path_limit','הגעת למגבלת המסלולים הפעילים. השבת מסלול אחר לפני ההפעלה.');}db.path_enrollments.filter(x=>x.userId===a.user.id&&!x.deleted_at).forEach(x=>x.primary=false);en.active=true;en.primary=true;en.updated_at=now();save(db);return ok(res,{enrollment:en});}
 if(p.startsWith('/api/tasks/')&&p.endsWith('/complete')&&req.method==='POST'){
  const taskId=decodeURIComponent(p.split('/')[3]||''),b=await body(req),db=load(),en=activeEnrollment(db,a.user.id),tpl=en&&pathDetail(en.pathSlug),task=tpl?.chapters.flatMap(c=>c.tasks).find(t=>t.id===taskId);if(!en||!task)return err(res,404,'task_not_found','המשימה לא נמצאה במסלול הפעיל.');const already=en.completedTaskIds.includes(taskId);if(!already){en.completedTaskIds.push(taskId);en.progress=calcProgress(tpl,en.completedTaskIds);en.updated_at=now();grantXp(db,a.user.id,task.xp,'task_complete',`task:${en.id}:${taskId}`);grantCoins(db,a.user.id,task.coins);updateStreak(db,a.user.id);if(en.completedTaskIds.length===1)checkAchievement(db,a.user.id,'first-task');}
  db.task_submissions.push({id:id('sub'),userId:a.user.id,enrollmentId:en.id,taskId,text:safeText(b.text,3000),link:/^https?:\/\//.test(b.link||'')?String(b.link).slice(0,500):'',difficulty:['easy','right','hard'].includes(b.difficulty)?b.difficulty:'right',created_at:now()});save(db);return ok(res,{alreadyCompleted:already,progress:en.progress,user:publicUser(a.user,db.profiles.find(x=>x.userId===a.user.id))});
 }
 if(p==='/api/coach'&&req.method==='POST'){
  const b=await body(req,1024*30),message=safeText(b.message,1000);if(!message)return err(res,400,'message_required','כתוב שאלה למאמן.');const db=load(),today=new Date().toISOString().slice(0,10),used=db.ai_coach_messages.filter(x=>x.userId===a.user.id&&x.role==='user'&&x.created_at.startsWith(today)).length,limit=plans[a.profile.planId].coachDailyLimit;if(used>=limit)return err(res,429,'coach_limit','הגעת למגבלת המאמן היומית בתוכנית שלך.');const en=activeEnrollment(db,a.user.id),tpl=en&&pathDetail(en.pathSlug),history=db.ai_coach_messages.filter(x=>x.userId===a.user.id).slice(-10);db.ai_coach_messages.push({id:id('msg'),userId:a.user.id,role:'user',content:message,created_at:now()});
  const generated=await coachReply({message,enrollment:en,path:tpl,planId:a.profile.planId,history,coachStyle:a.profile.coachStyle}),reply=generated.reply;
  db.ai_coach_messages.push({id:id('msg'),userId:a.user.id,role:'assistant',content:reply,demo:generated.demo,created_at:now()});save(db);return ok(res,{reply,demo:generated.demo,remaining:Math.max(0,limit-used-1)});
 }
 if(p==='/api/game/daily'&&req.method==='GET'){
  const db=load(),en=activeEnrollment(db,a.user.id),override=a.user.role==='admin'&&gameModes.some(x=>x.id===u.searchParams.get('mode'))?u.searchParams.get('mode'):undefined,g=dailyFor(a.profile,en,override),best=Math.max(0,...db.daily_game_attempts.filter(x=>x.userId===a.user.id&&x.dailyGameId===g.dailyGameId&&x.finished_at).map(x=>x.score||0));return ok(res,{game:{...g,questions:g.questions.map(q=>({...q,answerIndex:undefined,explanation:undefined}))},best,canPlay:hasFeature(a.profile.planId,'canPlayFull3DGames'),plan:a.profile.planId});
 }
 if(p==='/api/game/start'&&req.method==='POST'){
  if(!hasFeature(a.profile.planId,'canPlayFull3DGames'))return err(res,403,'upgrade_required','משחק 3D מלא זמין מ־Basic ומעלה.',{minimumPlan:'basic',price:plans.basic.price});const b=await body(req),db=load(),en=activeEnrollment(db,a.user.id),override=a.user.role==='admin'&&gameModes.some(x=>x.id===b.mode)?b.mode:undefined,g=dailyFor(a.profile,en,override);const attempts=db.daily_game_attempts.filter(x=>x.userId===a.user.id&&x.date===g.date);const allowed=a.profile.planId==='basic'?2:3;if(attempts.filter(x=>x.started_at).length>=allowed)return err(res,403,'attempt_limit','אין ניסיונות נוספים להיום בתוכנית שלך.');const attempt={id:newAttemptId(),userId:a.user.id,dailyGameId:g.dailyGameId,date:g.date,gameMode:g.gameMode,started_at:now(),finished_at:null,score:null,questionCount:g.questions.length,nonce:id('nonce'),created_at:now()};db.daily_game_attempts.push(attempt);save(db);const clientGame={...g,questions:g.questions.map(q=>({id:q.id,prompt:q.prompt,options:q.options,topic:q.topic}))};return ok(res,{attemptId:attempt.id,nonce:attempt.nonce,game:clientGame},201);
 }
 if(p==='/api/game/answer'&&req.method==='POST'){
  const b=await body(req,1024*30),db=load(),attempt=db.daily_game_attempts.find(x=>x.id===b.attemptId&&x.userId===a.user.id),en=activeEnrollment(db,a.user.id);if(!attempt||attempt.finished_at||attempt.nonce!==b.nonce)return err(res,400,'attempt_invalid','ניסיון המשחק אינו תקין.');const g=dailyFor(a.profile,en,attempt.gameMode),events=db.game_events.filter(x=>x.attemptId===attempt.id).sort((x,y)=>x.sequence-y.sequence),sequence=events.length,q=g.questions[sequence];if(!q)return err(res,409,'questions_complete','כל השאלות בניסיון כבר נענו.');if(b.questionId!==q.id||!Number.isInteger(b.answerIndex)||b.answerIndex<0||b.answerIndex>=q.options.length)return err(res,400,'sequence_invalid','סדר השאלות או התשובה אינם תקינים.');const correct=b.answerIndex===q.answerIndex,priorStreak=[...events].reverse().findIndex(e=>!e.correct),streak=correct?((priorStreak===-1?events.length:priorStreak)+1):0,scoreDelta=correct?g.scoreRules.correct+(streak>1?g.scoreRules.streak:0)+(b.usedHint?0:g.scoreRules.noHint):g.scoreRules.wrong;db.game_events.push({id:id('ge'),attemptId:attempt.id,userId:a.user.id,sequence,questionId:q.id,answerIndex:b.answerIndex,usedHint:Boolean(b.usedHint),correct,scoreDelta,created_at:now()});save(db);return ok(res,{correct,explanation:q.explanation,topic:q.topic,scoreDelta,streak,penaltySeconds:correct?0:5,questionNumber:sequence+1,total:g.questions.length});
 }
 if(p==='/api/game/finish'&&req.method==='POST'){
  const b=await body(req,1024*50),db=load(),attempt=db.daily_game_attempts.find(x=>x.id===b.attemptId&&x.userId===a.user.id),en=activeEnrollment(db,a.user.id),g=dailyFor(a.profile,en,attempt?.gameMode);if(!attempt||attempt.nonce!==b.nonce)return err(res,400,'attempt_invalid','ניסיון המשחק אינו תקין.');const events=db.game_events.filter(x=>x.attemptId===attempt.id).sort((x,y)=>x.sequence-y.sequence),answers=events.map(e=>({questionId:e.questionId,answerIndex:e.answerIndex,usedHint:e.usedHint})),result=validateAttempt(attempt,g,{answers});if(!result.ok)return err(res,400,result.error,'תוצאת המשחק לא עברה אימות שרת.');attempt.finished_at=now();Object.assign(attempt,result);grantXp(db,a.user.id,result.xp,'daily_game',`game:${attempt.id}`);grantCoins(db,a.user.id,result.coins);updateStreak(db,a.user.id);checkAchievement(db,a.user.id,'game-first');save(db);const rank=db.daily_game_attempts.filter(x=>x.dailyGameId===attempt.dailyGameId&&x.finished_at).sort((x,y)=>y.score-x.score).findIndex(x=>x.id===attempt.id)+1;return ok(res,{result:{...result,rank},user:publicUser(a.user,db.profiles.find(x=>x.userId===a.user.id))});
 }
 if(p==='/api/leaderboard'&&req.method==='GET'){
  const db=load(),en=activeEnrollment(db,a.user.id),g=dailyFor(a.profile,en);const rows=db.daily_game_attempts.filter(x=>x.date===g.date&&x.finished_at).sort((x,y)=>y.score-x.score).slice(0,50).map((x,i)=>{const pr=db.profiles.find(z=>z.userId===x.userId);return {rank:i+1,displayName:pr?.displayName||'שחקן',score:x.score,level:pr?.level||1}});return ok(res,{rows});
 }
 if(p==='/api/orders'&&req.method==='POST'){
  const b=await body(req,1024*30),planId=String(b.planId||'');if(!validPlan(planId))return err(res,400,'plan_invalid','תוכנית לא תקינה.');const db=load(),order={id:id('ord'),userId:a.user.id,type:'subscription',itemId:planId,planId,priceNis:plans[planId].price,paymentMethod:'bit',status:'awaiting_payment',history:[{status:'created',at:now()},{status:'awaiting_payment',at:now()}],internalNote:'',created_at:now(),updated_at:now()};db.orders.push(order);save(db);const pay=paymentInstructions(planId,order.id);return ok(res,{order,bitPhone:pay.phone,bitUrl:pay.verifiedUrl||'',message:pay.message},201);
 }
 if(p.startsWith('/api/orders/')&&p.endsWith('/proof')&&req.method==='POST'){
  const orderId=p.split('/')[3],b=await body(req,6*1024*1024),db=load(),order=db.orders.find(x=>x.id===orderId&&x.userId===a.user.id);if(!order)return err(res,404,'order_not_found','ההזמנה לא נמצאה.');if(!['awaiting_payment','rejected'].includes(order.status))return err(res,409,'order_state','לא ניתן להעלות אישור במצב הנוכחי.');const f=fileData(b.dataUrl);if(f.error==='file_type')return err(res,400,'file_type','מותר להעלות PNG, JPG, WEBP או PDF בלבד.');if(f.error==='file_size')return err(res,413,'file_size','הקובץ גדול מדי. הגודל המרבי הוא 5MB.');fs.mkdirSync(uploadDir,{recursive:true});const proofId=id('proof'),filename=`${proofId}${f.ext}`;fs.writeFileSync(path.join(uploadDir,filename),f.buf);db.payment_proofs.push({id:proofId,orderId,userId:a.user.id,filename,originalName:safeText(b.name,120),mime:f.mime,size:f.buf.length,created_at:now()});order.status='under_review';order.history.push({status:'proof_uploaded',at:now()},{status:'under_review',at:now()});order.updated_at=now();save(db);return ok(res,{order,message:'האישור הועלה ונשלח לבדיקה ידנית.'});
 }
 if(p==='/api/orders/mine'&&req.method==='GET'){const db=load();return ok(res,{orders:db.orders.filter(x=>x.userId===a.user.id).slice().reverse()});}
 if(p==='/api/challenges'&&req.method==='GET'){const db=load();return ok(res,{challenges:db.challenges.filter(x=>x.status==='active').map(c=>({...c,joined:db.challenge_participants.some(p=>p.challengeId===c.id&&p.userId===a.user.id),participants:db.challenge_participants.filter(p=>p.challengeId===c.id).length}))});}
 if(/^\/api\/challenges\/[^/]+\/join$/.test(p)&&req.method==='POST'){const cid=p.split('/')[3],db=load(),c=db.challenges.find(x=>x.id===cid&&x.status==='active');if(!c)return err(res,404,'challenge_not_found','האתגר לא נמצא.');if(!db.challenge_participants.some(x=>x.challengeId===cid&&x.userId===a.user.id))db.challenge_participants.push({id:id('cp'),challengeId:cid,userId:a.user.id,score:0,created_at:now()});save(db);return ok(res,{joined:true});}
 if(p==='/api/marketplace'&&req.method==='GET'){
  const db=load(),q=(u.searchParams.get('q')||'').toLowerCase(),cat=u.searchParams.get('category')||'',price=u.searchParams.get('price')||'';let rows=db.marketplace_paths.filter(x=>x.status==='approved');if(q)rows=rows.filter(x=>`${x.title} ${x.description}`.toLowerCase().includes(q));if(cat)rows=rows.filter(x=>x.category===cat);if(price==='free')rows=rows.filter(x=>x.price===0);if(price==='paid')rows=rows.filter(x=>x.price>0);return ok(res,{paths:rows.map(x=>({...x,creatorName:db.profiles.find(p=>p.userId===x.creatorId)?.displayName||'יוצר LEVELUP',favorite:db.favorites.some(f=>f.userId===a.user.id&&f.marketplacePathId===x.id),started:db.path_enrollments.some(e=>e.userId===a.user.id&&e.pathSlug===x.pathSlug&&!e.deleted_at)}))});
 }
 if(p==='/api/marketplace/create'&&req.method==='POST'){if(!hasFeature(a.profile.planId,'canPublishMarketplacePath'))return err(res,403,'feature_required','פרסום מסלולים זמין בתוכנית Pro.');const b=await body(req,1024*100),title=safeText(b.title,120),description=safeText(b.description,800),category=safeText(b.category,80),price=Math.max(0,Math.min(999,Number(b.price)||0)),durationDays=Math.max(1,Math.min(365,Number(b.durationDays)||7));if(!title||!description||!categories.includes(category))return err(res,400,'marketplace_invalid','יש להשלים שם, תיאור וקטגוריה תקינים.');const db=load(),row={id:id('mp'),pathSlug:`creator-${Date.now().toString(36)}`,creatorId:a.user.id,title,description,category,difficulty:['beginner','intermediate','advanced'].includes(b.difficulty)?b.difficulty:'beginner',durationDays,price,rating:0,learners:0,status:'pending',updated_at:now(),created_at:now()};db.marketplace_paths.push(row);save(db);return ok(res,{path:row,message:'המסלול נשלח לבדיקה לפני פרסום.'},201);}
 if(/^\/api\/marketplace\/[^/]+\/order$/.test(p)&&req.method==='POST'){const mid=p.split('/')[3],db=load(),mp=db.marketplace_paths.find(x=>x.id===mid&&x.status==='approved');if(!mp)return err(res,404,'marketplace_not_found','המסלול לא נמצא.');if(db.path_enrollments.some(e=>e.userId===a.user.id&&e.pathSlug===mp.pathSlug&&!e.deleted_at))return ok(res,{alreadyOwned:true,pathSlug:mp.pathSlug,message:'המסלול כבר נוסף לחשבון.'});if(mp.price<=0){if(!db.path_enrollments.some(e=>e.userId===a.user.id&&e.pathSlug===mp.pathSlug&&!e.deleted_at))db.path_enrollments.push({id:id('enr'),userId:a.user.id,pathSlug:mp.pathSlug,marketplacePathId:mp.id,progress:0,active:false,primary:false,completedTaskIds:[],started_at:now(),created_at:now(),updated_at:now()});mp.learners=(mp.learners||0)+1;save(db);return ok(res,{free:true,enrolled:true,message:'המסלול החינמי נוסף לחשבון.'},201)}const order={id:id('ord'),userId:a.user.id,type:'marketplace',itemId:mp.id,itemTitle:mp.title,priceNis:mp.price,paymentMethod:'bit',status:'awaiting_payment',history:[{status:'created',at:now()},{status:'awaiting_payment',at:now()}],internalNote:'',created_at:now(),updated_at:now()};db.orders.push(order);save(db);return ok(res,{order,bitPhone:config.bitPhone,bitUrl:config.bitUrl,message:'התשלום באמצעות bit נבדק ידנית. הגישה תופעל לאחר אישור ההעברה.'},201);}
 if(/^\/api\/marketplace\/[^/]+\/review$/.test(p)&&req.method==='POST'){const mid=p.split('/')[3],b=await body(req),rating=Number(b.rating),db=load(),mp=db.marketplace_paths.find(x=>x.id===mid&&x.status==='approved');if(!mp)return err(res,404,'marketplace_not_found','המסלול לא נמצא.');if(!db.path_enrollments.some(e=>e.userId===a.user.id&&(e.marketplacePathId===mid||e.pathSlug===mp.pathSlug)))return err(res,403,'review_requires_start','אפשר לדרג רק לאחר התחלת המסלול.');if(!Number.isInteger(rating)||rating<1||rating>5)return err(res,400,'rating_invalid','הדירוג חייב להיות בין 1 ל־5.');let r=db.reviews.find(x=>x.marketplacePathId===mid&&x.userId===a.user.id);if(r){r.rating=rating;r.body=safeText(b.body,600);r.updated_at=now()}else db.reviews.push({id:id('review'),marketplacePathId:mid,userId:a.user.id,rating,body:safeText(b.body,600),created_at:now(),updated_at:now()});const reviews=db.reviews.filter(x=>x.marketplacePathId===mid);mp.rating=reviews.reduce((n,x)=>n+x.rating,0)/reviews.length;save(db);return ok(res,{rating:mp.rating});}
 if(p.startsWith('/api/marketplace/')&&p.endsWith('/favorite')&&req.method==='POST'){
  const mid=p.split('/')[3],db=load(),existing=db.favorites.find(x=>x.userId===a.user.id&&x.marketplacePathId===mid);if(existing)db.favorites=db.favorites.filter(x=>x!==existing);else db.favorites.push({id:id('fav'),userId:a.user.id,marketplacePathId:mid,created_at:now()});save(db);return ok(res,{favorite:!existing});
 }
 if(p.startsWith('/api/marketplace/')&&p.endsWith('/report')&&req.method==='POST'){
  const mid=p.split('/')[3],b=await body(req),db=load();if(!db.marketplace_paths.some(x=>x.id===mid))return err(res,404,'marketplace_not_found','המסלול לא נמצא.');db.reports.push({id:id('report'),userId:a.user.id,targetType:'marketplace_path',targetId:mid,reason:safeText(b.reason,500),status:'open',created_at:now()});save(db);return ok(res,{message:'הדיווח התקבל לבדיקה.'},201);
 }
 if(p==='/api/settings'&&req.method==='PATCH'){
  const b=await body(req,1024*30),db=load(),profile=db.profiles.find(x=>x.userId===a.user.id);if(b.displayName!==undefined){const n=safeText(b.displayName,60);if(!n)return err(res,400,'name_invalid','שם התצוגה ריק.');profile.displayName=n}if(['he','en'].includes(b.locale))profile.locale=b.locale;if(['supportive','direct','energetic','professional'].includes(b.coachStyle))profile.coachStyle=b.coachStyle;if(['dark','light'].includes(b.theme))profile.theme=b.theme;if(['private','friends'].includes(b.privacy))profile.privacy=b.privacy;profile.updated_at=now();save(db);return ok(res,{user:publicUser(a.user,profile),message:'השינויים נשמרו.'});
 }
 if(p==='/api/export'&&req.method==='GET'){const db=load();const exportData={user:{email:a.user.email,created_at:a.user.created_at},profile:a.profile,enrollments:db.path_enrollments.filter(x=>x.userId===a.user.id),submissions:db.task_submissions.filter(x=>x.userId===a.user.id),xp:db.xp_events.filter(x=>x.userId===a.user.id),gameAttempts:db.daily_game_attempts.filter(x=>x.userId===a.user.id),orders:db.orders.filter(x=>x.userId===a.user.id)};return json(res,200,exportData,{'content-disposition':'attachment; filename="levelup-data.json"'});}
 if(p==='/api/account'&&req.method==='DELETE'){const db=load(),user=db.users.find(x=>x.id===a.user.id);user.deleted_at=now();user.updated_at=now();const profile=db.profiles.find(x=>x.userId===a.user.id);profile.deleted_at=now();save(db);return ok(res,{message:'החשבון סומן למחיקה.'},200,{'set-cookie':'levelup_session=; Path=/; HttpOnly; SameSite=Strict; Max-Age=0'});}

 if(p.startsWith('/api/admin/')){
  if(a.user.role!=='admin')return err(res,403,'admin_required','אין הרשאת מנהל.');
  if(p==='/api/admin/summary'&&req.method==='GET'){const db=load();return ok(res,{counts:{users:db.users.filter(x=>!x.deleted_at).length,enrollments:db.path_enrollments.filter(x=>x.active).length,pendingOrders:db.orders.filter(x=>x.status==='under_review').length,reports:db.reports.filter(x=>x.status==='open').length,gameAttempts:db.daily_game_attempts.filter(x=>x.finished_at).length,pendingMarketplace:db.marketplace_paths.filter(x=>x.status==='pending').length},orders:db.orders.slice().reverse().slice(0,20).map(o=>({...o,proofs:db.payment_proofs.filter(p=>p.orderId===o.id).map(p=>({id:p.id,originalName:p.originalName,mime:p.mime,size:p.size,created_at:p.created_at}))})),reports:db.reports.slice().reverse().slice(0,20),users:db.users.filter(x=>!x.deleted_at).map(u=>publicUser(u,db.profiles.find(x=>x.userId===u.id))),marketplacePending:db.marketplace_paths.filter(x=>x.status==='pending').slice(-20).reverse()});}
  if(/^\/api\/admin\/orders\/[^/]+\/(approve|reject)$/.test(p)&&req.method==='POST'){
   const [, , , ,orderId,action]=p.split('/'),b=await body(req,1024*30),db=load(),order=db.orders.find(x=>x.id===orderId);if(!order)return err(res,404,'order_not_found','ההזמנה לא נמצאה.');if(action==='approve'){if(order.status==='approved')return err(res,409,'already_approved','ההזמנה כבר אושרה.');if(order.status!=='under_review')return err(res,409,'order_state','אפשר לאשר רק הזמנה שנמצאת בבדיקה.');order.status='approved';order.approvedBy=a.user.id;order.approvedAt=now();order.internalNote=safeText(b.note,500);order.history.push({status:'approved',at:now(),by:a.user.id});if(order.type==='marketplace'){const mp=db.marketplace_paths.find(x=>x.id===order.itemId);if(mp&&!db.marketplace_sales.some(x=>x.orderId===order.id)){db.marketplace_sales.push({id:id('sale'),orderId:order.id,marketplacePathId:mp.id,buyerId:order.userId,creatorId:mp.creatorId,priceNis:order.priceNis,commissionNis:Math.round(order.priceNis*.2*100)/100,created_at:now()});db.path_enrollments.push({id:id('enr'),userId:order.userId,pathSlug:mp.pathSlug,marketplacePathId:mp.id,progress:0,active:false,primary:false,completedTaskIds:[],started_at:now(),created_at:now(),updated_at:now()});mp.learners=(mp.learners||0)+1}db.notifications.push({id:id('noti'),userId:order.userId,title:'הרכישה אושרה',body:`המסלול ${mp?.title||''} נוסף לחשבון.`,read:false,created_at:now()});audit(db,a.user.id,'marketplace.order.approve','order',order.id,{marketplacePathId:order.itemId});}else{const profile=db.profiles.find(x=>x.userId===order.userId);profile.planId=order.planId;profile.updated_at=now();let sub=db.subscriptions.find(x=>x.userId===order.userId&&x.status==='active');if(sub)sub.status='replaced';db.subscriptions.push({id:id('subscr'),userId:order.userId,planId:order.planId,status:'active',starts_at:now(),ends_at:new Date(Date.now()+30*86400000).toISOString(),orderId:order.id,created_at:now(),updated_at:now()});db.notifications.push({id:id('noti'),userId:order.userId,title:'התשלום אושר',body:`תוכנית ${plans[order.planId].name} הופעלה.`,read:false,created_at:now()});audit(db,a.user.id,'order.approve','order',order.id,{planId:order.planId});}}else{if(order.status==='approved')return err(res,409,'approved_order','אי אפשר לדחות הזמנה שאושרה.');order.status='rejected';order.internalNote=safeText(b.note,500);order.history.push({status:'rejected',at:now(),by:a.user.id});db.notifications.push({id:id('noti'),userId:order.userId,title:'אישור התשלום נדחה',body:'האישור לא אושר. ניתן להעלות אישור חדש או לפנות לתמיכה.',read:false,created_at:now()});audit(db,a.user.id,'order.reject','order',order.id,{});}order.updated_at=now();save(db);return ok(res,{order});
  }
  if(p.startsWith('/api/admin/proofs/')&&req.method==='GET'){
   const proofId=p.split('/')[4],db=load(),proof=db.payment_proofs.find(x=>x.id===proofId);if(!proof)return err(res,404,'proof_not_found','האישור לא נמצא.');const fp=path.join(uploadDir,proof.filename);if(!fs.existsSync(fp))return err(res,404,'file_missing','הקובץ אינו קיים.');res.writeHead(200,{'content-type':proof.mime,'content-disposition':`inline; filename="proof${path.extname(proof.filename)}"`,'cache-control':'no-store'});return fs.createReadStream(fp).pipe(res);
  }
  if(/^\/api\/admin\/marketplace\/[^/]+\/(approve|reject)$/.test(p)&&req.method==='POST'){const parts=p.split('/'),mid=parts[4],action=parts[5],b=await body(req,1024*20),db=load(),mp=db.marketplace_paths.find(x=>x.id===mid);if(!mp)return err(res,404,'marketplace_not_found','המסלול לא נמצא.');mp.status=action==='approve'?'approved':'rejected';mp.moderationNote=safeText(b.note,500);mp.updated_at=now();audit(db,a.user.id,`marketplace.${action}`,'marketplace_path',mid,{});save(db);return ok(res,{path:mp});}
  if(p.startsWith('/api/admin/users/')&&p.endsWith('/block')&&req.method==='POST'){const uid=p.split('/')[4],db=load(),user=db.users.find(x=>x.id===uid);if(!user)return err(res,404,'user_not_found','המשתמש לא נמצא.');user.blocked_at=user.blocked_at?null:now();audit(db,a.user.id,user.blocked_at?'user.block':'user.unblock','user',uid,{});save(db);return ok(res,{blocked:Boolean(user.blocked_at)});}
 }
 return err(res,404,'not_found','הפעולה המבוקשת לא נמצאה.');
}

function staticFile(req,res,u){
 let reqPath=decodeURIComponent(u.pathname);if(reqPath==='/'||!path.extname(reqPath))reqPath='/index.html';const fp=path.normalize(path.join(publicDir,reqPath));if(!fp.startsWith(publicDir))return err(res,403,'forbidden','גישה אסורה.');if(!fs.existsSync(fp)||!fs.statSync(fp).isFile()){if(path.extname(reqPath))return err(res,404,'asset_not_found','הקובץ לא נמצא.');return fs.createReadStream(path.join(publicDir,'index.html')).pipe(res)}const ext=path.extname(fp);res.writeHead(200,{'content-type':mime[ext]||'application/octet-stream','cache-control':ext==='.html'?'no-cache':'public, max-age=3600'});fs.createReadStream(fp).pipe(res);
}

export const server=http.createServer(async(req,res)=>{securityHeaders(res);const u=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);try{if(u.pathname.startsWith('/api/')){await api(req,res,u);return}staticFile(req,res,u)}catch(e){console.error(e);if(!res.headersSent)err(res,e.message==='body_too_large'?413:500,e.message||'server_error',e.message==='body_too_large'?'הבקשה גדולה מדי.':'אירעה שגיאת שרת. הנתונים שכבר נשמרו לא נמחקו.');else res.end();}});
if(process.argv[1]&&path.resolve(process.argv[1])===path.resolve(new URL(import.meta.url).pathname)){server.listen(config.port,()=>console.log(`LEVELUP AI running at http://localhost:${config.port}`));}
