"""Rendering `reports/teacher_faculty.md` from the registry.

The markdown is generated, never edited. A hand-maintained table of a hundred
models is wrong within a month, and a table that disagrees with the JSON beside
it is worse than no table — the reader cannot tell which one the pipeline
actually reads. This renders from `data/teachers_registry.json`, so the two
cannot drift apart.
"""
from __future__ import annotations

import json
from pathlib import Path

from .licences import CONDITIONAL, PERMITTED

ROLE_TITLES = {
    "code": "Code",
    "hebrew": "Hebrew",
    "multilingual": "Multilingual",
    "reasoning": "Reasoning",
    "math": "Maths",
    "general": "General / English",
}


def _size(entry: dict) -> str:
    return f"{entry['billions']}B" if entry.get("billions") else "—"


def _mark(entry: dict) -> str:
    return {PERMITTED: "", CONDITIONAL: " †"}.get(entry["licence_verdict"], " ✗")


def render(payload: dict) -> str:
    summary = payload["summary"]
    lines: list[str] = []
    add = lines.append

    add("# LEKOY — The Teacher Faculty")
    add("")
    add("One hundred open-weight models that can generate training data for LEKOY "
        "students, and the forty-odd of them that specialise in code.")
    add("")
    add("Generated by `scripts/build_teachers.py` from the live Hugging Face model "
        "API. Every licence and parameter count below was read from the hub, not "
        "typed in. Do not edit this file; rebuild it.")
    add("")
    add(f"Built {payload['updated_at']}.")
    add("")
    add("---")
    add("")

    add("## Summary")
    add("")
    add("| | |")
    add("| --- | ---: |")
    add(f"| Candidates considered | {summary['candidates']} |")
    add(f"| **Teachers selected** | **{summary['selected']}** |")
    add(f"| **of which teach code** | **{summary['code_teachers']}** |")
    add(f"| Hebrew specialists | {summary['hebrew_teachers']} |")
    add(f"| Rejected | {summary['rejected']} |")
    add(f"| Licence attaches no obligation | {summary['unconditional']} |")
    add(f"| Licence attaches an obligation | {summary['conditional']} |")
    add(f"| Need hub credentials (gated) | {summary['gated']} |")
    add(f"| Combined parameters | {summary['total_parameters'] / 1e9:,.0f}B |")
    add("")
    add("Tiers, relative to the 0.49B student: "
        + ", ".join(f"**{v}** {k}" for k, v in summary["by_tier"].items() if v))
    add("")

    add("## The faculty")
    add("")
    add("Grouped by primary role. A teacher with code as a *secondary* role is "
        f"counted in the {summary['code_teachers']} above but listed under its "
        "primary heading below, which is why the two numbers differ.")
    add("")
    add("† marks a licence that permits distillation and attaches an obligation to "
        "the release. The obligations are listed in full at the end.")
    add("")

    by_role: dict[str, list[dict]] = {}
    for entry in payload["teachers"]:
        by_role.setdefault(entry["role"], []).append(entry)

    for role, title in ROLE_TITLES.items():
        entries = by_role.get(role, [])
        if not entries:
            continue
        add(f"### {title} — {len(entries)}")
        add("")
        add("| Model | Size | Tier | Licence | Why it is here |")
        add("| --- | ---: | --- | --- | --- |")
        for entry in sorted(entries, key=lambda e: -(e.get("params") or 0)):
            add(f"| `{entry['id']}` | {_size(entry)} | {entry['tier']} | "
                f"{entry['licence_verdict']}{_mark(entry)} | {entry['note']} |")
        add("")

    add("## Considered and refused")
    add("")
    add("Recorded rather than omitted. An absence is not an answer to "
        "\"why is this model not in the mixture\".")
    add("")
    add("| Model | Licence | Why not |")
    add("| --- | --- | --- |")
    rejected = sorted(payload["rejected"],
                      key=lambda e: (e.get("licence_verdict") != "refused",
                                     e.get("id", "")))
    for entry in rejected:
        licence = entry.get("licence_name") or entry.get("licence") or "—"
        add(f"| `{entry['id']}` | {licence} | {entry.get('reason', '')} |")
    add("")

    if payload.get("release_obligations"):
        add("## Obligations a release inherits")
        add("")
        add("A checkpoint distilled from a conditional teacher carries that "
            "teacher's obligation into its own licence and model card. These are "
            "readings of published licence text, not legal advice.")
        add("")
        for line in payload["release_obligations"]:
            licence, _, reason = line.partition(": ")
            add(f"- **`{licence}`** — {reason}")
        add("")

    return "\n".join(lines) + "\n"


def write(payload: dict, path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(payload), encoding="utf-8")
    return path


def render_file(registry_path: Path, out: Path) -> Path:
    return write(json.loads(registry_path.read_text(encoding="utf-8")), out)
