/** Original, editable bilingual curriculum. Answer keys stay on the server. */
export type Localized = { he: string; en: string };
export type LearningTask = {
  id: string; title: Localized; description: Localized; objective: Localized;
  minutes: number; xp: number; instructions: { he: string[]; en: string[] };
  example: Localized; hints: { he: string[]; en: string[] };
  resources: { title: string; url: string }[];
  question: { prompt: Localized; options: { he: string[]; en: string[] }; answer: number; explanation: Localized };
  type: 'practice' | 'quiz' | 'project';
};
export type LearningPath = {
  id: string; title: Localized; description: Localized; category: string;
  level: 'beginner' | 'intermediate' | 'advanced'; durationDays: number;
  dailyMinutes: number; price: number; creator: string; cover: string;
  chapters: { id: string; title: Localized; tasks: LearningTask[] }[];
};
const l = (he: string, en: string): Localized => ({ he, en });
const lines = (...pairs: [string, string][]) => ({ he: pairs.map(p => p[0]), en: pairs.map(p => p[1]) });
export const categories = [
  ['programming', 'תכנות', 'Programming'], ['apps', 'בניית אפליקציות', 'App development'],
  ['games', 'בניית משחקים', 'Game development'], ['ai', 'כלי AI', 'AI tools'],
  ['english', 'אנגלית', 'English'], ['math', 'מתמטיקה', 'Mathematics'],
  ['content', 'יצירת תוכן', 'Content creation'], ['video', 'עריכת וידאו', 'Video editing'],
  ['design', 'עיצוב', 'Design'], ['business', 'יזמות ועסקים', 'Entrepreneurship'],
  ['marketing', 'שיווק ומכירות', 'Marketing'], ['learning', 'הרגלי למידה', 'Learning habits'],
  ['personal', 'כישורים אישיים', 'Personal skills'], ['fitness', 'הרגלים בריאים', 'Healthy habits'],
].map(([id, he, en]) => ({ id, title: l(he, en) }));

type TaskContent = Omit<LearningTask, 'xp' | 'resources'>;
const task = (value: TaskContent): LearningTask => ({ ...value, xp: value.type === 'project' ? 160 : value.type === 'quiz' ? 60 : 80, resources: [] });
const q = (prompt: Localized, options: { he: string[]; en: string[] }, answer: number, explanation: Localized) => ({ prompt, options, answer, explanation });
const chapter = (id: string, title: Localized, tasks: LearningTask[]) => ({ id, title, tasks });

export const learningPaths: LearningPath[] = [
  {
    id: 'website', title: l('האתר הראשון שלך ב־7 ימים', 'Your first website in 7 days'),
    description: l('מעמוד HTML ראשון לאתר אישי נגיש, מותאם לטלפון ועם פעולה אינטראקטיבית.', 'Build an accessible personal website with a responsive layout and a working interaction.'),
    category: 'programming', level: 'beginner', durationDays: 7, dailyMinutes: 20, price: 0, creator: 'LEVELUP Studio', cover: '/covers/website.svg',
    chapters: [
      chapter('website-structure', l('01 · בונים את הבסיס', '01 · Build the foundation'), [
        task({ id: 'website-brief', title: l('מגדירים אתר שאפשר לסיים', 'Define a website you can finish'), description: l('לפני קוד, בוחרים למי האתר נועד ומה המבקר צריך לעשות.', 'Before coding, decide who the site serves and what a visitor should do.'), objective: l('מסמך קצר עם קהל, מטרה ושלושה אזורי תוכן.', 'A brief with an audience, a goal, and three content sections.'), minutes: 15, type: 'practice',
          instructions: lines(['בחרו תחביב או פרויקט שאפשר להציג ללא פרטים אישיים רגישים.', 'Pick a hobby or project you can describe without sensitive personal details.'], ['כתבו מי יקרא את האתר ומה תרצו שיבין בסיום.', 'Write who will read the site and what they should understand.'], ['שרטטו כותרת, אזור דוגמאות וכפתור אחד. העלו את השרטוט או תארו אותו.', 'Sketch a heading, an examples section, and one button. Upload or describe the sketch.']),
          example: l('אתר לתיק עבודות צילום: המבקר יראה שלוש תמונות מקוריות ויוכל לפתוח תיאור לכל תמונה.', 'A photography portfolio: visitors see three original photos and can open a description for each.'), hints: lines(['התחילו בעמוד אחד ובפעולה אחת. פרסום פרטי קשר אינו דרוש.', 'Start with one page and one action. Contact details are unnecessary.']),
          question: q(l('איזו מטרה היא המדידה ביותר?', 'Which goal is most measurable?'), lines(['המבקר יפתח אחת משלוש דוגמאות', 'A visitor opens one of three examples'], ['האתר יהיה מדהים', 'The website looks amazing'], ['האתר יכיל הכול', 'The website contains everything']), 0, l('אפשר לבדוק פתיחת דוגמה בפועל. שאר המטרות אינן מגדירות פעולה ניתנת לבדיקה.', 'Opening an example is an observable action; the other goals cannot be tested clearly.')) }),
        task({ id: 'website-html', title: l('כותבים עמוד HTML ראשון', 'Write your first HTML page'), description: l('HTML מתאר את משמעות התוכן: כותרת, פסקה, קישור וכפתור.', 'HTML describes the meaning of content: a heading, paragraph, link, or button.'), objective: l('קובץ index.html עם כותרת ראשית, פסקה וקישור תקין.', 'An index.html file with a main heading, a paragraph, and a working link.'), minutes: 20, type: 'practice',
          instructions: lines(['צרו תיקייה וקובץ index.html בעורך טקסט.', 'Create a folder and an index.html file in a text editor.'], ['הוסיפו html עם lang="he" ו־dir="rtl", ואז head ו־body.', 'Add html with lang="he" and dir="rtl", then head and body.'], ['בתוך main כתבו h1, פסקת p וקישור a. פתחו בדפדפן וצרפו את הקוד.', 'Inside main, add an h1, a p paragraph, and an a link. Open in a browser and submit the code.']),
          example: l('<main><h1>הצילום שלי</h1><p>שלושה רגעים מהטבע.</p><a href="#gallery">לגלריה</a></main>', '<main><h1>My photography</h1><p>Three moments in nature.</p><a href="#gallery">View gallery</a></main>'), hints: lines(['תגית פתיחה וסגירה מקיפות תוכן. ודאו שיש רק h1 ראשי אחד.', 'Opening and closing tags surround content. Use one primary h1.']),
          question: q(l('איזו תגית מייצגת את הכותרת הראשית?', 'Which element represents the main heading?'), lines(['<p>', '<p>'], ['<h1>', '<h1>'], ['<img>', '<img>']), 1, l('h1 מציינת את הכותרת הראשית; p היא פסקה ו־img היא תמונה.', 'h1 is the main heading; p is a paragraph and img is an image.')) }),
      ]),
      chapter('website-style', l('02 · עיצוב שמתאים למסך', '02 · Design for the screen'), [
        task({ id: 'website-css', title: l('מוסיפים היררכיה עם CSS', 'Create hierarchy with CSS'), description: l('הפרידו תוכן מעיצוב בעזרת קובץ CSS אחד.', 'Separate content from presentation using one CSS file.'), objective: l('כותרת ברורה, טקסט קריא וריווח עקבי ללא עיצוב בתוך תגיות.', 'A clear heading, readable text, and consistent spacing without inline styling.'), minutes: 20, type: 'practice',
          instructions: lines(['צרו style.css וקשרו אותו ב־head באמצעות link.', 'Create style.css and link it in head.'], ['הגדירו צבע רקע, צבע טקסט, line-height: 1.6 ורוחב קריאה מרבי.', 'Set a background, text color, line-height: 1.6, and a maximum reading width.'], ['תנו לכפתור padding ובדקו שניתן לזהות מיקוד במקלדת. הגישו צילום והסבר לשתי בחירות.', 'Give the button padding and check keyboard focus visibility. Submit a screenshot and explain two choices.']),
          example: l('main { max-width: 44rem; margin-inline: auto; padding: 1rem; }', 'main { max-width: 44rem; margin-inline: auto; padding: 1rem; }'), hints: lines(['padding הוא הרווח בתוך האלמנט; margin הוא הרווח מחוץ לו.', 'Padding is space inside an element; margin is space outside.']),
          question: q(l('איזו תכונה מוסיפה רווח בתוך כפתור?', 'Which property adds space inside a button?'), lines(['margin', 'margin'], ['padding', 'padding'], ['opacity', 'opacity']), 1, l('padding מרחיק את תוכן הכפתור מהגבול שלו.', 'Padding separates button content from its border.')) }),
        task({ id: 'website-responsive', title: l('מתאימים את הגלריה לטלפון', 'Make the gallery responsive'), description: l('בנו פריסה שזורמת עם רוחב המסך במקום לכפות רוחב קבוע.', 'Build a layout that follows available space instead of forcing a fixed width.'), objective: l('שלוש דוגמאות ללא גלילה אופקית ברוחב 375px וברוחב 1280px.', 'Three examples without horizontal scrolling at 375px and 1280px.'), minutes: 25, type: 'practice',
          instructions: lines(['הוסיפו meta viewport והגדירו לתמונות max-width: 100%.', 'Add the viewport meta tag and set images to max-width: 100%.'], ['השתמשו ב־grid-template-columns: repeat(auto-fit, minmax(min(100%, 15rem), 1fr)).', 'Use grid-template-columns: repeat(auto-fit, minmax(min(100%, 15rem), 1fr)).'], ['פתחו כלי מפתחים בשני רוחבי המסך. צרפו שתי תמונות ורשמו תיקון שביצעתם.', 'Open developer tools at both widths. Submit two screenshots and describe one fix.']),
          example: l('<meta name="viewport" content="width=device-width, initial-scale=1">', '<meta name="viewport" content="width=device-width, initial-scale=1">'), hints: lines(['תמונה ברוחב קבוע גדול מהמיכל יכולה לגרום לגלילה אופקית.', 'An image with a fixed width larger than its container can cause horizontal scrolling.']),
          question: q(l('מהי מטרת עיצוב רספונסיבי?', 'What is the purpose of responsive design?'), lines(['אותו רוחב קשיח בכל מסך', 'A fixed width on every screen'], ['הסתרת כל התמונות', 'Hiding every image'], ['התאמת הפריסה לשטח הזמין', 'Adapting layout to available space']), 2, l('פריסה רספונסיבית מתאימה את ארגון התוכן לשטח הזמין.', 'Responsive layout adapts content organization to available space.')) }),
      ]),
      chapter('website-ship', l('03 · פעולה, בדיקה ופרסום', '03 · Interact, test, and share'), [
        task({ id: 'website-js', title: l('נותנים לכפתור תפקיד אמיתי', 'Give a button a real action'), description: l('אירוע לחיצה יכול לפתוח ולסגור הסבר בלי לרענן את העמוד.', 'A click event can reveal or hide an explanation without reloading the page.'), objective: l('כפתור שמשנה את נראות ההסבר ואת aria-expanded.', 'A button that toggles an explanation and its aria-expanded state.'), minutes: 25, type: 'practice',
          instructions: lines(['הוסיפו כפתור ומתחתיו פסקה עם id="details" ו־hidden.', 'Add a button followed by a paragraph with id="details" and hidden.'], ['ב־script הוסיפו addEventListener מסוג click. החליפו את hidden ואת aria-expanded.', 'Use a click addEventListener in a script. Toggle hidden and aria-expanded.'], ['בדקו עכבר, Tab ו־Enter. הגישו קוד והסבירו מה משתנה בכל לחיצה.', 'Test mouse, Tab, and Enter. Submit code and explain what changes on each click.']),
          example: l('button.addEventListener("click", () => { details.hidden = !details.hidden; button.setAttribute("aria-expanded", String(!details.hidden)); });', 'button.addEventListener("click", () => { details.hidden = !details.hidden; button.setAttribute("aria-expanded", String(!details.hidden)); });'), hints: lines(['העדיפו button אמיתי. הוא מקבל פעולות מקלדת באופן טבעי.', 'Use a real button. It supports keyboard activation naturally.']),
          question: q(l('איזו שיטה מחברת פעולה לאירוע?', 'Which method connects an action to an event?'), lines(['addEventListener', 'addEventListener'], ['toUpperCase', 'toUpperCase'], ['parseInt', 'parseInt']), 0, l('addEventListener מפעילה פונקציה כשאירוע מסוים מתרחש.', 'addEventListener calls a function when a specified event occurs.')) }),
        task({ id: 'website-final', title: l('פרויקט סיום: אתר שעובד', 'Final project: a working website'), description: l('חברו את כל החלקים ובדקו את האתר כמו משתמש חדש.', 'Combine the pieces and test the website as a new visitor would.'), objective: l('אתר בן עמוד אחד עם שלוש דוגמאות, פעולה עובדת ובדיקת נגישות בסיסית.', 'A one-page site with three examples, a working interaction, and basic accessibility checks.'), minutes: 30, type: 'project',
          instructions: lines(['בדקו שכל קישור מגיע ליעד, לכל תמונה תיאור חלופי והעמוד קריא בטלפון.', 'Check link destinations, image alternatives, and mobile readability.'], ['עברו על כל הפעולות במקלדת בלבד ותקנו לפחות בעיה אחת.', 'Try all actions using only the keyboard and fix at least one issue.'], ['העלו קובץ טקסט עם הקוד או קישור פרטי לפרויקט יחד עם רשימת הבדיקות. פרסום ציבורי הוא בחירה.', 'Submit a text file containing the code or a private project link with your checklist. Public publishing is optional.']),
          example: l('בדקתי: כפתור נפתח ב־Enter, הגלריה אינה נחתכת ב־375px, שלוש התמונות מקוריות.', 'Checked: Enter opens the details, the gallery fits at 375px, and all three photos are original.'), hints: lines(['אל תפרסמו כתובת מגורים, סיסמאות או פרטי קשר של אחרים.', 'Do not publish home addresses, passwords, or other people’s contact details.']),
          question: q(l('איך בודקים נגישות בסיסית של הפעולות?', 'How can you check basic action accessibility?'), lines(['מסתכלים רק על צילום מסך', 'Only inspect a screenshot'], ['מנווטים עם Tab ומפעילים עם Enter', 'Navigate with Tab and activate with Enter'], ['מקטינים את כל הטקסט', 'Make all text smaller']), 1, l('בדיקת מקלדת מוודאת שאפשר להגיע לפעולות ולהפעיל אותן גם ללא עכבר.', 'Keyboard testing confirms that actions can be reached and activated without a mouse.')) }),
      ]),
    ],
  },
  {
    id: 'app', title: l('האפליקציה הראשונה שלך ב־30 יום', 'Your first app in 30 days'), description: l('בנו מנהל הרגלים ב־React: רכיבים, מצב, טפסים, שמירה ובדיקות משתמש.', 'Build a React habit tracker with components, state, forms, persistence, and user testing.'),
    category: 'apps', level: 'beginner', durationDays: 30, dailyMinutes: 30, price: 0, creator: 'LEVELUP Studio', cover: '/covers/app.svg',
    chapters: [
      chapter('app-plan', l('01 · בעיה וממשק', '01 · Problem and interface'), [
        task({ id: 'app-story', title: l('מנסחים סיפור משתמש', 'Write a user story'), description: l('מיקוד בפעולה שימושית אחת יקל על בניית גרסה ראשונה.', 'Focusing on one useful action makes a first version achievable.'), objective: l('סיפור משתמש ושלושה תנאי קבלה למנהל הרגלים.', 'One user story and three acceptance criteria for a habit tracker.'), minutes: 20, type: 'practice', instructions: lines(['בחרו הרגל פשוט, למשל קריאה של עשר דקות.', 'Choose a simple habit, such as ten minutes of reading.'], ['כתבו: בתור לומד, אני רוצה לסמן ביצוע כדי לראות את ההתקדמות.', 'Write: As a learner, I want to mark completion so I can see progress.'], ['הגדירו מה קורה לפני סימון, אחרי סימון ואחרי רענון. צרפו תרשים מסך.', 'Define behavior before completion, after completion, and after reload. Submit a screen sketch.']), example: l('לא ניתן ליצור הרגל ללא שם; סימון מופיע מיד; רענון שומר את הסימון.', 'An empty name is rejected; completion appears immediately; reload preserves completion.'), hints: lines(['תנאי קבלה צריך להיות משהו שאפשר לבדוק.', 'An acceptance criterion must describe something testable.']), question: q(l('איזה תנאי קבלה ניתן לבדיקה?', 'Which acceptance criterion is testable?'), lines(['האפליקציה תהיה נחמדה', 'The app is nice'], ['הרגל ללא שם מציג שגיאה', 'A habit without a name shows an error'], ['כולם ישתמשו בה', 'Everyone uses it']), 1, l('אפשר להזין שם ריק ולבדוק שהשגיאה מופיעה.', 'You can submit an empty name and verify an error appears.')) }),
        task({ id: 'app-components', title: l('מפרקים את המסך לרכיבים', 'Break the screen into components'), description: l('רכיב מחבר תצוגה ותפקיד מוגדר, כמו שורת הרגל.', 'A component combines a view with a focused responsibility, such as one habit row.'), objective: l('רכיבי App, HabitList ו־HabitRow עם נתונים דרך props.', 'App, HabitList, and HabitRow components passing data through props.'), minutes: 30, type: 'practice', instructions: lines(['הקימו פרויקט React לפי ההדרכה הרשמית או סביבת הלימוד שלכם.', 'Create a React project using the official guide or your learning environment.'], ['בנו HabitRow שמקבל name ו־done ומציג אותם.', 'Build HabitRow accepting name and done and displaying both.'], ['הציגו שתי שורות מתוך מערך עם key יציב. הגישו את הרכיבים.', 'Render two rows from an array using stable keys. Submit the components.']), example: l('<HabitRow key={habit.id} name={habit.name} done={habit.done} />', '<HabitRow key={habit.id} name={habit.name} done={habit.done} />'), hints: lines(['השתמשו במזהה ההרגל כמפתח, לא במיקום במערך.', 'Use the habit ID as its key rather than the array index.']), question: q(l('איך מעבירים מידע מהורה לרכיב ילד?', 'How do you pass data from a parent to a child?'), lines(['באמצעות props', 'Through props'], ['באמצעות שינוי HTML ידני', 'By editing HTML manually'], ['רק דרך קובץ CSS', 'Only through a CSS file']), 0, l('props הן הקלט של רכיב React.', 'Props are inputs to a React component.')) }),
      ]),
      chapter('app-data', l('02 · מידע ואינטראקציה', '02 · Data and interaction'), [
        task({ id: 'app-state', title: l('שומרים מצב בלי לשנות מערך קיים', 'Update state without mutating arrays'), description: l('React מציג מחדש רכיבים כשהמצב מתעדכן.', 'React renders components again when their state changes.'), objective: l('סימון הרגל כבוצע וביטול הסימון באמצעות useState.', 'Complete and uncomplete a habit using useState.'), minutes: 30, type: 'practice', instructions: lines(['העבירו את מערך ההרגלים ל־useState.', 'Move the habits array into useState.'], ['כתבו toggle שמייצר מערך חדש עם map לפי id.', 'Write a toggle that creates a new array with map using the ID.'], ['בדקו שסימון שורה אחת אינו משנה את האחרת. הגישו את הפונקציה ותוצאת הבדיקה.', 'Check that toggling one row leaves another unchanged. Submit the function and test result.']), example: l('setHabits(items => items.map(h => h.id === id ? { ...h, done: !h.done } : h));', 'setHabits(items => items.map(h => h.id === id ? { ...h, done: !h.done } : h));'), hints: lines(['אל תשתמשו ב־push על המערך השמור במצב.', 'Do not call push on the array stored in state.']), question: q(l('מה מחזירה map?', 'What does map return?'), lines(['תמיד מחרוזת', 'Always a string'], ['מערך חדש', 'A new array'], ['שינוי אוטומטי במסד נתונים', 'An automatic database update']), 1, l('map יוצרת מערך חדש מהתוצאות של פונקציה לכל איבר.', 'map creates a new array from the results of a function applied to each item.')) }),
        task({ id: 'app-form', title: l('טופס הוספה עם בדיקות קלט', 'Build a validated add form'), description: l('טופס צריך לעזור לתקן טעות בלי למחוק את מה שכבר הוזן.', 'A form should help correct mistakes without discarding entered information.'), objective: l('יצירת הרגל עם שם באורך 2–60 תווים והודעת שגיאה נגישה.', 'Create a habit with a 2–60 character name and an accessible validation error.'), minutes: 30, type: 'practice', instructions: lines(['הוסיפו label, input וכפתור submit בתוך form.', 'Add a label, input, and submit button inside a form.'], ['ב־submit בצעו trim ובדקו אורך. הציגו שגיאה בלי לנקות את השדה.', 'Trim on submit and validate length. Display an error without clearing the field.'], ['בדקו ריק, רווחים בלבד ושם תקין. שלחו את שלוש התוצאות.', 'Test empty input, only spaces, and a valid name. Submit all three results.']), example: l('const name = value.trim(); if (name.length < 2) setError("יש להזין לפחות שני תווים");', 'const name = value.trim(); if (name.length < 2) setError("Enter at least two characters");'), hints: lines(['placeholder אינו מחליף label.', 'A placeholder does not replace a label.']), question: q(l('מה כדאי לעשות כשהקלט שגוי?', 'What should happen when input is invalid?'), lines(['למחוק את כל הטופס', 'Clear the whole form'], ['להתעלם מהשגיאה', 'Ignore the error'], ['לשמור את הקלט ולהציג תיקון נדרש', 'Preserve the input and explain the required fix']), 2, l('שמירת הקלט והסבר ממוקד מקלים על תיקון.', 'Preserving input and providing a specific message makes correction easier.')) }),
      ]),
      chapter('app-release', l('03 · שמירה ומסירה', '03 · Persistence and delivery'), [
        task({ id: 'app-storage', title: l('שומרים הרגלים בין ביקורים', 'Persist habits between visits'), description: l('לפרויקט מקומי, localStorage מתאים למידע שאינו רגיש.', 'For a local project, localStorage can hold non-sensitive information.'), objective: l('שמירה ושחזור עם טיפול בנתונים לא תקינים.', 'Save and restore habits with handling for malformed data.'), minutes: 30, type: 'practice', instructions: lines(['שמרו JSON של הרגלים תחת מפתח ייחודי לאפליקציה.', 'Save habit JSON under a unique app key.'], ['בקריאה השתמשו ב־try/catch ובדקו שקיבלתם מערך לפני השימוש.', 'When reading, use try/catch and check for an array before using it.'], ['רעננו, שנו ערך לשגוי בכלי המפתחים וודאו שהאפליקציה מציגה מצב בטוח. תעדו.', 'Reload, corrupt the stored value in developer tools, and verify a safe state is shown. Document the result.']), example: l('localStorage.setItem("habits-v1", JSON.stringify(habits));', 'localStorage.setItem("habits-v1", JSON.stringify(habits));'), hints: lines(['אל תשמרו סיסמאות, פרטי תשלום או מידע רפואי ב־localStorage.', 'Do not store passwords, payment details, or medical information in localStorage.']), question: q(l('איזה מידע מתאים לפרויקט localStorage הזה?', 'Which information fits this localStorage project?'), lines(['סיסמת המשתמש', 'A user password'], ['שם הרגל כללי ומצב ביצוע', 'A generic habit name and completion state'], ['פרטי כרטיס אשראי', 'Card details']), 1, l('שם הרגל כללי הוא המידע הלא־רגיש שהפרויקט צריך.', 'A generic habit name is the non-sensitive data this project needs.')) }),
        task({ id: 'app-final', title: l('פרויקט סיום: מנהל הרגלים', 'Final project: a habit tracker'), description: l('מסרו גרסה שאדם אחר יכול להפעיל בלי הסבר בעל פה.', 'Deliver a version another person can use without a verbal explanation.'), objective: l('אפליקציה עם הוספה, סימון, מחיקה, שמירה ו־README.', 'An app with create, toggle, delete, persistence, and a README.'), minutes: 60, type: 'project', instructions: lines(['הוסיפו מחיקה עם אפשרות ביטול או אישור ברור.', 'Add deletion with an undo option or clear confirmation.'], ['בקשו מאדם מוכר לבצע הוספה וסימון בלי הכוונה. רשמו מקום אחד שבו היסס.', 'Ask someone you know to add and complete a habit without guidance. Record one hesitation.'], ['תקנו את הבעיה והגישו קוד, הוראות הרצה ושלוש בדיקות קבלה שעברו.', 'Fix the issue and submit code, run instructions, and three passed acceptance checks.']), example: l('README: התקנה, הרצה, כיצד הנתונים נשמרים ואיך לאפס אותם.', 'README: install, run, how data is saved, and how to reset it.'), hints: lines(['כתבו גם מה האפליקציה עדיין אינה עושה, למשל סנכרון בין מכשירים.', 'Document what the app does not yet do, such as device synchronization.']), question: q(l('מה מוכיחה בדיקת שימוש עם אדם נוסף?', 'What can testing with another person reveal?'), lines(['האם ההוראות והפעולות מובנות', 'Whether instructions and actions are understandable'], ['שאין שום באג אפשרי', 'That no bug can exist'], ['שהאפליקציה תאבטח כל מידע', 'That the app secures every kind of data']), 0, l('בדיקת שימוש חושפת אי־בהירות בתהליך, אך אינה מוכיחה היעדר באגים או אבטחה מלאה.', 'A usability test exposes unclear steps but does not prove the absence of bugs or complete security.')) }),
      ]),
    ],
  },
  {
    id: 'game', title: l('בונים משחק 3D ראשון', 'Build your first 3D game'), description: l('צרו מסלול איסוף קטן ב־Three.js עם תנועה, התנגשויות, ניקוד וסיום.', 'Create a small Three.js collection course with movement, collisions, scoring, and a finish.'), category: 'games', level: 'beginner', durationDays: 21, dailyMinutes: 30, price: 0, creator: 'LEVELUP Studio', cover: '/covers/game.svg',
    chapters: [
      chapter('game-scene', l('01 · עולם ומצלמה', '01 · World and camera'), [
        task({ id: 'game-scene', title: l('סצנה, מצלמה וקובייה', 'Scene, camera, and cube'), description: l('סצנה מכילה עצמים; מצלמה קובעת מבט; renderer מצייר את התמונה.', 'The scene holds objects, the camera chooses a view, and the renderer draws it.'), objective: l('קובייה מוארת הנראית בתוך canvas מותאם לגודל המיכל.', 'A lit cube displayed in a canvas that fits its container.'), minutes: 30, type: 'practice', instructions: lines(['צרו Scene, PerspectiveCamera ו־WebGLRenderer לפי מדריך Three.js.', 'Create a Scene, PerspectiveCamera, and WebGLRenderer using the Three.js guide.'], ['הוסיפו קובייה, חומר ואור אחד. מקמו את המצלמה מחוץ לקובייה.', 'Add a cube, material, and one light. Position the camera outside the cube.'], ['שנו את רוחב החלון והתאימו aspect ו־renderer size. הגישו צילום וקוד.', 'Resize the window and update aspect and renderer size. Submit a screenshot and code.']), example: l('camera.position.set(0, 2, 5); camera.lookAt(0, 0, 0);', 'camera.position.set(0, 2, 5); camera.lookAt(0, 0, 0);'), hints: lines(['אם המסך ריק, בדקו שהמצלמה מכוונת אל העצם ושהחומר מקבל אור.', 'If the screen is empty, check that the camera faces the object and that the material receives light.']), question: q(l('מה קובע מאיזו זווית רואים את העולם?', 'What determines the angle used to view the world?'), lines(['המצלמה', 'The camera'], ['מונה הניקוד', 'The score counter'], ['שם הקובץ', 'The filename']), 0, l('המצלמה מגדירה מיקום, כיוון ושדה ראייה.', 'The camera defines position, direction, and field of view.')) }),
        task({ id: 'game-world', title: l('מרכיבים אי צף פשוט', 'Assemble a simple floating island'), description: l('גאומטריות בסיסיות מספיקות לעולם קטן עם סגנון עקבי.', 'Basic geometry is enough for a small world with a consistent style.'), objective: l('רצפה, שלושה סימני דרך ושער סיום עם חומרים משותפים.', 'A floor, three landmarks, and a finish gate using shared materials.'), minutes: 30, type: 'practice', instructions: lines(['צרו משטח רחב וגבול ברור שאינו דורש טקסטורה.', 'Create a broad platform and a visible border without requiring a texture.'], ['הוסיפו שלושה עצמים בגבהים שונים וחומר צבע משותף.', 'Add three objects at different heights sharing one colored material.'], ['מקמו שער בסוף מסלול אפשרי ושרטטו מבט על של הדרך אליו.', 'Place a gate at the end of a reachable route and draw a top-down plan.']), example: l('חומר אחד לעמודים יכול לשמש חמישה Mesh שונים.', 'One pillar material can be reused by five different meshes.'), hints: lines(['צבע וצורה צריכים לעזור לזהות את היעד, גם ללא אפקטים.', 'Color and shape should help identify the destination even without effects.']), question: q(l('למה לשתף חומר בין עצמים?', 'Why share a material between objects?'), lines(['כדי שכל עצם יצריך קובץ ענק', 'So every object needs a huge file'], ['כדי להשתמש מחדש במשאבים ולשמור על עקביות', 'To reuse resources and maintain consistency'], ['כדי לבטל את המצלמה', 'To remove the camera']), 1, l('שימוש חוזר מצמצם כפילויות ושומר על מראה עקבי.', 'Reuse reduces duplication and keeps appearance consistent.')) }),
      ]),
      chapter('game-actions', l('02 · תנועה וחוקים', '02 · Movement and rules'), [
        task({ id: 'game-movement', title: l('תנועה שאינה תלויה ב־FPS', 'Make frame-independent movement'), description: l('תנועה לפי זמן שעבר שומרת על מהירות דומה במכשירים שונים.', 'Movement based on elapsed time keeps speed similar across devices.'), objective: l('שליטה בחצים או WASD במהירות קבועה יחסית לאורך זמן.', 'Arrow or WASD controls with a consistent speed over time.'), minutes: 30, type: 'practice', instructions: lines(['עקבו אחר מקשים לחוצים עם keydown ו־keyup.', 'Track pressed keys with keydown and keyup.'], ['הכפילו כיוון ומהירות ב־deltaTime בשניות בכל מסגרת.', 'Multiply direction and speed by deltaTime in seconds each frame.'], ['אפסו מקשים ב־blur ועצרו כשאין מיקוד. השוו מרחק אחרי חמש שניות.', 'Clear keys on blur and pause when unfocused. Compare distance after five seconds.']), example: l('player.position.x += direction * speed * deltaTime;', 'player.position.x += direction * speed * deltaTime;'), hints: lines(['הגבילו deltaTime אחרי השהיה כדי למנוע קפיצה פתאומית.', 'Clamp deltaTime after a pause to prevent sudden jumps.']), question: q(l('איך מקטינים תלות בקצב הפריימים?', 'How do you reduce frame-rate dependence?'), lines(['מוסיפים מרחק קבוע בכל פריים', 'Add a fixed distance every frame'], ['מכפילים מהירות בזמן שחלף', 'Multiply speed by elapsed time'], ['מבטלים את כל הקלט', 'Disable all input']), 1, l('מהירות כפול זמן נותנת מרחק, גם כשמספר הפריימים משתנה.', 'Speed multiplied by time gives distance even when frame count changes.')) }),
        task({ id: 'game-collisions', title: l('אוספים חפצים פעם אחת', 'Collect each item once'), description: l('כלל איסוף ברור מחבר את המיקום בעולם לניקוד.', 'A clear collection rule connects a world position to a score.'), objective: l('שלושה פריטים שמעניקים ניקוד פעם אחת בלבד.', 'Three collectibles that each award points exactly once.'), minutes: 30, type: 'practice', instructions: lines(['הגדירו מזהה לכל פריט ורדיוס איסוף קטן.', 'Give every item an ID and a small collection radius.'], ['השוו מרחק מהשחקן; בעת איסוף הוסיפו מזהה ל־Set והסתירו את הפריט.', 'Compare distance from the player; on collection add the ID to a Set and hide the item.'], ['חזרו לאותו מקום וודאו שלא מתקבל ניקוד נוסף. הגישו את הבדיקה.', 'Return to the same position and verify no extra points are awarded. Submit the check.']), example: l('if (!collected.has(id) && distance < 0.8) { collected.add(id); score += 10; }', 'if (!collected.has(id) && distance < 0.8) { collected.add(id); score += 10; }'), hints: lines(['הסתרת אובייקט אינה מספיקה; צריך גם לשמור מצב איסוף.', 'Hiding an object is insufficient; also store its collection state.']), question: q(l('מה מונע ניקוד כפול מאותו חפץ?', 'What prevents double scoring from one item?'), lines(['צבע בהיר', 'A bright color'], ['מצלמה רחוקה', 'A distant camera'], ['שמירת מזהה החפץ שנאסף', 'Remembering the collected item ID']), 2, l('מצב לפי מזהה מאפשר לדחות איסוף חוזר של אותו פריט.', 'State keyed by item ID lets the game reject repeat collection.')) }),
      ]),
      chapter('game-finish', l('03 · חוויה שלמה', '03 · Complete the experience'), [
        task({ id: 'game-access', title: l('מוסיפים עצירה וכפתורי מגע', 'Add pause and touch controls'), description: l('משחק צריך לאפשר עצירה ושליטה גם ללא מקלדת.', 'A game should support pausing and control without a keyboard.'), objective: l('מסך עצירה, חזרה למשחק וארבעה כפתורי כיוון נגישים.', 'A pause screen, resume action, and four accessible direction buttons.'), minutes: 30, type: 'practice', instructions: lines(['חברו Escape למצב paused ועצרו את טיימר המשחק.', 'Connect Escape to a paused state and stop the game timer.'], ['הוסיפו כפתורי כיוון גדולים עם pointerdown ו־pointerup.', 'Add large direction buttons using pointerdown and pointerup.'], ['בדקו החלפת טאבים, pointercancel וחזרה למשחק בלי תנועה תקועה.', 'Test tab switching, pointercancel, and resuming without stuck movement.']), example: l('button.onpointercancel = () => { moving.left = false; };', 'button.onpointercancel = () => { moving.left = false; };'), hints: lines(['איפוס קלט נדרש גם כשהאצבע עוזבת את אזור הכפתור.', 'Input must also reset when the finger leaves the button area.']), question: q(l('מה צריך לקרות כשהמשחק מושהה?', 'What should happen when the game is paused?'), lines(['טיימר המשחק עוצר', 'The game timer stops'], ['הדמות ממשיכה לנוע', 'The character keeps moving'], ['הניקוד מתאפס תמיד', 'The score always resets']), 0, l('עצירה מקפיאה את סימולציית המשחק ואת הזמן הפעיל.', 'Pausing freezes the game simulation and active time.')) }),
        task({ id: 'game-final', title: l('פרויקט סיום: אי האיסוף', 'Final project: collection island'), description: l('המשחק מסתיים רק אחרי איסוף שלושה חפצים והגעה לשער.', 'The game ends only after collecting three items and reaching the gate.'), objective: l('משחק קצר עם התחלה, חוקים, ניצחון, ניסיון חוזר וניקוי משאבים.', 'A short game with a start, rules, win state, replay, and resource cleanup.'), minutes: 60, type: 'project', instructions: lines(['חסמו סיום עד שנאספו שלושה פריטים והציגו כמה חסרים.', 'Block finishing until three items are collected and show how many remain.'], ['הוסיפו ניסיון חוזר שמאפס שחקן, פריטים, ניקוד וטיימר.', 'Add replay that resets player, items, score, and timer.'], ['ודאו שקיים dispose לחומרים וגאומטריות ביציאה. שלחו קוד וסרטון משחק קצר.', 'Dispose materials and geometries when leaving. Submit code and a short gameplay recording.']), example: l('בדיקה: איסוף 3/3, הגעה לשער, סיום, ניסיון חוזר ומונה 0/3.', 'Check: collect 3/3, reach the gate, finish, replay, and see 0/3.'), hints: lines(['השתמשו רק בנכסים שיצרתם או שהרישיון שלהם מתיר שימוש.', 'Use only assets you created or whose license permits use.']), question: q(l('למה מנקים חומרים וגאומטריות ביציאה?', 'Why dispose materials and geometries when leaving?'), lines(['כדי לשנות את שם המשחק', 'To rename the game'], ['כדי לשחרר משאבי GPU שאינם נחוצים', 'To release GPU resources that are no longer needed'], ['כדי להוסיף ניקוד', 'To add points']), 1, l('משאבי גרפיקה עלולים להישאר בזיכרון אם אינם משתחררים.', 'Graphics resources can remain in memory unless they are released.')) }),
      ]),
    ],
  },

  {
    id: 'english', title: l('אנגלית מדוברת למתחילים', 'Everyday spoken English'), description: l('תרגלו הצגה עצמית, בקשה מנומסת ושיחה קצרה באמצעות הקלטות פרטיות.', 'Practice introductions, polite requests, and a short conversation through private recordings.'), category: 'english', level: 'beginner', durationDays: 14, dailyMinutes: 20, price: 0, creator: 'LEVELUP Studio', cover: '/covers/english.svg',
    chapters: [
      chapter('english-start', l('01 · מתחילים לדבר', '01 · Start speaking'), [
        task({ id: 'english-intro', title: l('מציגים את עצמנו בשלושה משפטים', 'Introduce yourself in three sentences'), description: l('משפטים קצרים יעזרו להתחיל לדבר בלי לחכות לאוצר מילים גדול.', 'Short sentences help you start speaking without waiting for a large vocabulary.'), objective: l('הצגה עצמית של 20 שניות עם שם תצוגה ותחביב.', 'A 20-second introduction using a display name and a hobby.'), minutes: 15, type: 'practice', instructions: lines(['כתבו משפט עם My name is ושם תצוגה.', 'Write a sentence with My name is and a display name.'], ['הוסיפו I like ותחביב, ואז I want to learn ומשהו שמעניין אתכם.', 'Add I like with a hobby, then I want to learn with something that interests you.'], ['קראו בקול פעמיים. שלחו תמליל או הקלטה פרטית וכתבו מילה אחת לתרגול.', 'Read aloud twice. Submit a transcript or private recording and one word to practice.']), example: l('My name is Alex. I like drawing. I want to learn English.', 'My name is Alex. I like drawing. I want to learn English.'), hints: lines(['אין צורך לומר גיל, בית ספר או מקום מגורים.', 'There is no need to share your age, school, or home location.']), question: q(l('איזה משפט מציג תחביב?', 'Which sentence describes a hobby?'), lines(['I like drawing.', 'I like drawing.'], ['Where is the bus?', 'Where is the bus?'], ['Please close it.', 'Please close it.']), 0, l('I like ואחריו פעילות מבטא משהו שנהנים לעשות.', 'I like followed by an activity describes something you enjoy.')) }),
        task({ id: 'english-questions', title: l('שואלים ומחזירים שאלה', 'Ask and return a question'), description: l('שיחה נעשית הדדית כשגם עונים וגם שואלים.', 'A conversation becomes mutual when you answer and ask questions.'), objective: l('דיאלוג בן ארבע שורות על תחביבים.', 'A four-line dialogue about hobbies.'), minutes: 20, type: 'practice', instructions: lines(['כתבו שאלה שמתחילה ב־What do you like.', 'Write a question starting with What do you like.'], ['ענו במשפט אחד והוסיפו How about you?', 'Answer with one sentence and add How about you?'], ['תרגלו את שני התפקידים בקול ושלחו את ארבע השורות.', 'Practice both roles aloud and submit the four lines.']), example: l('A: What do you like doing? B: I like reading. How about you? A: I like cycling.', 'A: What do you like doing? B: I like reading. How about you? A: I like cycling.'), hints: lines(['שאלה קצרה נוספת מספיקה כדי להמשיך את השיחה.', 'One short follow-up is enough to continue the conversation.']), question: q(l('מה פירוש How about you?', 'What does How about you do in a conversation?'), lines(['מסיים את השיחה', 'Ends the conversation'], ['מחזיר את השאלה לצד השני', 'Returns the question to the other person'], ['מבקש כתובת מדויקת', 'Asks for an exact address']), 1, l('הביטוי מזמין את הצד השני לענות על אותה שאלה.', 'The phrase invites the other person to answer the same question.')) }),
      ]),
      chapter('english-everyday', l('02 · אנגלית למצבים יומיומיים', '02 · Everyday situations'), [
        task({ id: 'english-request', title: l('מבקשים עזרה בנימוס', 'Ask for help politely'), description: l('Can you ו־Could you עוזרים לנסח בקשה ברורה.', 'Can you and Could you help form a clear request.'), objective: l('שלוש בקשות מנומסות שאפשר להשתמש בהן בלימודים.', 'Three polite requests useful while learning.'), minutes: 20, type: 'practice', instructions: lines(['כתבו בקשה לחזור על משפט עם Could you repeat.', 'Write a request to repeat a sentence using Could you repeat.'], ['כתבו בקשה לדבר לאט ובקשה להסביר מילה.', 'Write a request to speak slowly and one to explain a word.'], ['הקליטו או קראו כל בקשה בקול; סמנו היכן אתם עושים הפסקה קצרה.', 'Record or read each request aloud; mark where you pause briefly.']), example: l('Could you repeat that, please? Could you speak more slowly?', 'Could you repeat that, please? Could you speak more slowly?'), hints: lines(['please יכול להופיע בסוף הבקשה.', 'Please can appear at the end of a request.']), question: q(l('איזו בקשה מנומסת לבקש חזרה?', 'Which is a polite request for repetition?'), lines(['You wrong.', 'You wrong.'], ['Repeat now!', 'Repeat now!'], ['Could you repeat that, please?', 'Could you repeat that, please?']), 2, l('Could you… please היא צורה ברורה ומנומסת לבקשה.', 'Could you… please is a clear, polite request form.')) }),
        task({ id: 'english-direction', title: l('מבינים הוראות כיוון', 'Understand simple directions'), description: l('תרגלו left, right ו־straight במפה דמיונית.', 'Practice left, right, and straight on an imaginary map.'), objective: l('שלוש הוראות שמובילות מנקודת התחלה לספרייה דמיונית.', 'Three directions leading from a starting point to an imaginary library.'), minutes: 20, type: 'practice', instructions: lines(['ציירו מפה דמיונית עם רחוב, פנייה ימינה וספרייה.', 'Draw an imaginary map with a street, a right turn, and a library.'], ['כתבו שלוש הוראות: Go straight, Turn right ומשפט הגעה.', 'Write three directions: Go straight, Turn right, and an arrival sentence.'], ['קראו את ההוראות והצביעו על הדרך. שלחו את המפה או התיאור.', 'Read the directions and trace the route. Submit the map or description.']), example: l('Go straight. Turn right. The library is on your left.', 'Go straight. Turn right. The library is on your left.'), hints: lines(['תרגלו במפה דמיונית, ללא פרטי המיקום שלכם.', 'Use an imaginary map without your own location details.']), question: q(l('מה פירוש Turn left?', 'What does Turn left mean?'), lines(['פנו שמאלה', 'Change direction to the left'], ['המשיכו ישר', 'Continue straight'], ['חזרו מחר', 'Return tomorrow']), 0, l('left הוא שמאל; right הוא ימין; straight הוא ישר.', 'Left and right indicate sides; straight means forward without turning.')) }),
      ]),
      chapter('english-confidence', l('03 · שיחה עם ביטחון', '03 · Build conversational confidence'), [
        task({ id: 'english-repair', title: l('ממשיכים גם כשחסרה מילה', 'Keep going when a word is missing'), description: l('תיאור פשוט יכול להחליף מילה שאינכם זוכרים.', 'A simple description can replace a word you do not remember.'), objective: l('תיאור של שלושה חפצים בלי להשתמש בשמם.', 'Describe three objects without naming them.'), minutes: 20, type: 'practice', instructions: lines(['בחרו חפצים פשוטים כמו עט, כוס ותיק.', 'Choose simple objects such as a pen, cup, and bag.'], ['תארו כל אחד באמצעות It is used for או I use it to.', 'Describe each with It is used for or I use it to.'], ['הוסיפו I do not know the word, but… ותרגלו בלי לעצור באמצע.', 'Add I do not know the word, but… and practice without stopping halfway.']), example: l('I do not know the word, but I use it to carry my books.', 'I do not know the word, but I use it to carry my books.'), hints: lines(['אפשר לתאר שימוש, צבע או גודל במקום לחפש מילה מושלמת.', 'Describe use, color, or size instead of searching for the perfect word.']), question: q(l('מה עדיף לעשות כשחסרה מילה בשיחה?', 'What can help when a word is missing?'), lines(['להפסיק לדבר תמיד', 'Always stop talking'], ['לתאר את המשמעות במילים פשוטות', 'Describe the meaning with simple words'], ['להמציא עובדה', 'Invent a fact']), 1, l('תיאור מאפשר להעביר משמעות גם בלי המילה המדויקת.', 'Description conveys meaning even without the exact word.')) }),
        task({ id: 'english-final', title: l('פרויקט סיום: שיחה של דקה', 'Final project: a one-minute conversation'), description: l('שלבו הצגה עצמית, שאלה, בקשה להבהרה ותשובה.', 'Combine an introduction, a question, a clarification request, and an answer.'), objective: l('שיחה של דקה או תמליל בן שמונה שורות עם ארבעת המרכיבים.', 'A one-minute conversation or eight-line transcript containing all four elements.'), minutes: 30, type: 'project', instructions: lines(['כתבו תסריט קצר בין שני אנשים שנפגשים בחוג.', 'Write a short script between two people meeting at a club.'], ['שלבו Could you repeat that? והמשיכו בשיחה אחרי ההבהרה.', 'Include Could you repeat that? and continue after the clarification.'], ['הגישו הקלטה פרטית או תמליל. ציינו משפט שהשתפר ומטרה אחת להמשך.', 'Submit a private recording or transcript. Name one improved sentence and one next goal.']), example: l('Hello, I am Alex. What do you like drawing? Could you repeat that? I like drawing animals too.', 'Hello, I am Alex. What do you like drawing? Could you repeat that? I like drawing animals too.'), hints: lines(['בהירות חשובה יותר ממהירות. עצירה קצרה למחשבה היא חלק משיחה.', 'Clarity matters more than speed. Brief thinking pauses are part of conversation.']), question: q(l('מהי מטרה טובה לשיחת מתחילים?', 'What is a good goal for a beginner conversation?'), lines(['לדבר בלי שום הפסקה', 'Speak without any pause'], ['להשתמש רק במילים מורכבות', 'Use only complex words'], ['להעביר משמעות ולהבין את הצד השני', 'Convey meaning and understand the other person']), 2, l('שיחה יעילה מבוססת על הבנה הדדית, לא על מהירות או מילים מסובכות.', 'Effective conversation relies on mutual understanding, not speed or complex vocabulary.')) }),
      ]),
    ],
  },
  {
    id: 'video', title: l('יסודות עריכת וידאו', 'Video editing fundamentals'), description: l('הפכו חומרי צילום מקוריים לסרטון של דקה עם סיפור, קול וכתוביות.', 'Turn original footage into a one-minute video with a story, sound, and captions.'), category: 'video', level: 'beginner', durationDays: 14, dailyMinutes: 30, price: 0, creator: 'LEVELUP Studio', cover: '/covers/video.svg',
    chapters: [
      chapter('video-plan', l('01 · חומר וסיפור', '01 · Footage and story'), [
        task({ id: 'video-story', title: l('מתכננים סיפור בשישה שוטים', 'Plan a six-shot story'), description: l('סרטון קצר צריך התחלה, שינוי וסיום שאפשר לראות.', 'A short video needs a visible beginning, change, and ending.'), objective: l('רשימת שישה שוטים לסרטון המציג תהליך פשוט.', 'A six-shot list showing a simple process.'), minutes: 20, type: 'practice', instructions: lines(['בחרו תהליך בטוח כמו קיפול נייר או ארגון שולחן.', 'Choose a safe process such as folding paper or organizing a desk.'], ['כתבו שוט רחב להתחלה, ארבעה שלבי תהליך ושוט סיום.', 'Write a wide opening shot, four process shots, and an ending shot.'], ['ציינו מה צריך להבין מכל שוט ואילו פרטים אישיים לא ייכנסו לפריים.', 'Describe what viewers should understand from each shot and what private details will stay out of frame.']), example: l('שולחן מבולגן → מיון → ניקוי → סידור ספרים → כלי כתיבה → שולחן מוכן.', 'Messy desk → sorting → cleaning → arranging books → placing pens → finished desk.'), hints: lines(['שינוי ברור בין התחלה לסיום נותן לסרטון כיוון.', 'A clear change between beginning and end gives the video direction.']), question: q(l('מה תפקידה של רשימת שוטים?', 'What is a shot list for?'), lines(['לתכנן את הצילומים הדרושים לסיפור', 'Plan the footage needed for the story'], ['להגדיל אוטומטית את הצפיות', 'Automatically increase views'], ['להחליף בדיקת זכויות', 'Replace rights checks']), 0, l('רשימת שוטים עוזרת לצלם את החומר הדרוש לפני העריכה.', 'A shot list helps capture the necessary footage before editing.')) }),
        task({ id: 'video-organize', title: l('מארגנים חומר לפני העריכה', 'Organize footage before editing'), description: l('שמות ותיקיות ברורים חוסכים זמן ומונעים קבצים חסרים.', 'Clear names and folders save time and prevent missing media.'), objective: l('פרויקט עריכה עם תיקיות וידאו, קול וייצוא ושישה קטעים מסודרים.', 'An editing project with video, sound, and export folders and six organized clips.'), minutes: 20, type: 'practice', instructions: lines(['צלמו את השוטים המקוריים שלכם בלי אנשים שלא נתנו רשות.', 'Film original shots without people who have not agreed to appear.'], ['צרו תיקיות footage, audio ו־exports ותנו לקבצים מספר ושם.', 'Create footage, audio, and exports folders and name files with a number and description.'], ['ייבאו לעורך ושמרו קובץ פרויקט. הגישו צילום של הארגון.', 'Import into an editor and save the project. Submit a screenshot of the organization.']), example: l('01-desk-wide.mp4, 02-sorting.mp4, 03-cleaning.mp4', '01-desk-wide.mp4, 02-sorting.mp4, 03-cleaning.mp4'), hints: lines(['אל תזיזו קובצי מקור אחרי הייבוא בלי לעדכן את הקישור בפרויקט.', 'Do not move source files after import without relinking them in the project.']), question: q(l('למה לא להזיז קובץ מקור אחרי ייבוא?', 'Why avoid moving source files after import?'), lines(['זה תמיד מוחק את המצלמה', 'It always deletes the camera'], ['הפרויקט עלול לאבד את הקישור לקובץ', 'The project may lose the file link'], ['אי אפשר לשנות שמות לעולם', 'Filenames can never change']), 1, l('עורכים רבים מקשרים למיקום הקובץ במקום להעתיק אותו לתוך הפרויקט.', 'Many editors link to a file location rather than copying it into the project.')) }),
      ]),
      chapter('video-edit', l('02 · קצב ובהירות', '02 · Rhythm and clarity'), [
        task({ id: 'video-cut', title: l('בונים חיתוך ראשון', 'Build a first cut'), description: l('חיתוך מסיר המתנה ומשאיר את הפעולה שהצופה צריך לראות.', 'A cut removes waiting and keeps the action viewers need to see.'), objective: l('רצף של 45–60 שניות ללא קטעים ריקים בהתחלה ובסיום.', 'A 45–60 second sequence without empty beginnings or endings.'), minutes: 30, type: 'practice', instructions: lines(['סדרו את ששת השוטים על ציר הזמן לפי הסיפור.', 'Arrange the six shots on the timeline in story order.'], ['חתכו רגעים לפני ואחרי הפעולה והשאירו זמן להבין כל שלב.', 'Trim moments before and after the action while leaving enough time to understand each step.'], ['צפו בלי קול. רשמו היכן הסיפור אינו ברור ותקנו את הסדר או האורך.', 'Watch without sound. Note where the story is unclear and adjust the order or duration.']), example: l('אם היד מסדרת ספר במשך ארבע שניות, אין צורך להשאיר עשר שניות של המתנה לפניו.', 'If arranging a book takes four seconds, ten seconds of waiting beforehand are unnecessary.'), hints: lines(['מעבר פשוט בין קטעים בדרך כלל מספיק; אפקט אינו מתקן סיפור לא ברור.', 'A simple cut is usually enough; an effect does not fix an unclear story.']), question: q(l('מהי מטרת החיתוך הראשוני?', 'What is the goal of a first cut?'), lines(['להוסיף את כל האפקטים', 'Add every effect'], ['להאריך כל שוט', 'Make every shot longer'], ['לבדוק שהסיפור והסדר מובנים', 'Check that the story and sequence are understandable']), 2, l('בחיתוך ראשון בודקים מבנה וקצב לפני ליטוש.', 'The first cut tests structure and rhythm before polishing.')) }),
        task({ id: 'video-audio', title: l('מאזנים דיבור וצליל', 'Balance speech and sound'), description: l('צליל צריך לתמוך בהבנת הסרטון ולהימנע מעיוות.', 'Sound should support understanding and avoid distortion.'), objective: l('קריינות מובנת, ללא נורות clipping אדומות ועם מוזיקה מותרת בלבד.', 'Understandable narration without red clipping indicators, using only permitted music.'), minutes: 30, type: 'practice', instructions: lines(['הקליטו משפט פתיחה וסיום במקום שקט.', 'Record an opening and closing sentence in a quiet place.'], ['הנמיכו מוזיקה בזמן דיבור, או ותרו עליה אם אינה נחוצה.', 'Lower music under speech or omit it if unnecessary.'], ['בדקו באוזניות וברמקול חלש שהדיבור מובן ושאין עיוות. ציינו מקור ורישיון לכל צליל חיצוני.', 'Check headphones and a quiet speaker for clarity and distortion. Record the source and license of external audio.']), example: l('הקלטת דיבור מקורית; מוזיקה שהוקלטה עצמאית; עוצמה נמוכה יותר בזמן הסבר.', 'Original narration; self-recorded music; lower music level during explanation.'), hints: lines(['נרמול אינו מתקן הקלטה מעוותת; במקרה כזה הקליטו שוב.', 'Normalization does not repair distorted recording; record again if necessary.']), question: q(l('מה עושים כשהמוזיקה מסתירה את הדיבור?', 'What should you do when music hides speech?'), lines(['מנמיכים את המוזיקה בזמן הדיבור', 'Lower the music during speech'], ['מגבירים הכול עד לעיוות', 'Increase everything until distorted'], ['מוחקים את הכתוביות', 'Delete the captions']), 0, l('הנמכת מוזיקה מפנה מקום לדיבור בלי להגביר את כל המיקס.', 'Lowering music makes room for speech without raising the whole mix.')) }),
      ]),
      chapter('video-deliver', l('03 · כתוביות ומסירה', '03 · Captions and delivery'), [
        task({ id: 'video-captions', title: l('מוסיפים כתוביות מדויקות', 'Add accurate captions'), description: l('כתוביות מאפשרות להבין דיבור גם בלי שמע.', 'Captions make speech understandable without sound.'), objective: l('כתוביות מסונכרנות וקריאות לכל הדיבור בסרטון.', 'Readable, synchronized captions for all speech in the video.'), minutes: 25, type: 'practice', instructions: lines(['תמללו את הקריינות וחלקו ליחידות קצרות.', 'Transcribe narration and divide it into short units.'], ['סנכרנו הופעה והיעלמות לזמן הדיבור ושמרו שוליים בטוחים.', 'Synchronize captions with speech and keep safe margins.'], ['צפו בטלפון בלי קול ותקנו שגיאות. הגישו שתי תמונות מסך.', 'Watch on a phone without sound and correct errors. Submit two screenshots.']), example: l('כתובית אחת: "מתחילים במיון הספרים." בשורה אחת או שתיים קריאות.', 'One caption: “Start by sorting the books.” on one or two readable lines.'), hints: lines(['תמלול אוטומטי הוא טיוטה שדורשת בדיקה אנושית.', 'Automatic transcription is a draft requiring human review.']), question: q(l('מה צריך לעשות לכתוביות אוטומטיות?', 'What should you do with automatic captions?'), lines(['להאמין שהן תמיד מדויקות', 'Assume they are always accurate'], ['לבדוק טקסט ותזמון', 'Check wording and timing'], ['להסתיר אותן מכל הצופים', 'Hide them from all viewers']), 1, l('שמות, הגייה ורעשי רקע יכולים לגרום לשגיאות תמלול.', 'Names, pronunciation, and background noise can cause transcription errors.')) }),
        task({ id: 'video-final', title: l('פרויקט סיום: סרטון של דקה', 'Final project: a one-minute video'), description: l('מסרו סרטון שמציג תהליך שלם ושומר על פרטיות וזכויות.', 'Deliver a complete process video that respects privacy and permissions.'), objective: l('קובץ וידאו עד דקה עם שישה שוטים, קול מאוזן וכתוביות.', 'A video up to one minute with six shots, balanced audio, and captions.'), minutes: 40, type: 'project', instructions: lines(['ייצאו קובץ 1080p בפורמט הנתמך בעורך ובנגן שלכם.', 'Export a 1080p file supported by your editor and player.'], ['פתחו את הקובץ המיוצא עצמו ובדקו התחלה, סוף, כתוביות ושמע.', 'Open the actual exported file and check the beginning, end, captions, and sound.'], ['הגישו קובץ או קישור פרטי, רשימת מקורות ורשימת שני תיקונים מהצפייה הסופית.', 'Submit a file or private link, source list, and two fixes from the final viewing.']), example: l('בדקתי שהכתובית האחרונה נשארת על המסך, שאין כתובת על מעטפה ושכל הקטעים צולמו על ידי.', 'I checked that the last caption remains visible, no address appears on an envelope, and all footage is mine.'), hints: lines(['ייצוא מוצלח אינו מבטיח שהקובץ תקין; צפו בתוצאה.', 'A successful export does not guarantee a correct file; watch the result.']), question: q(l('מה בודקים לפני מסירת סרטון?', 'What should you inspect before delivering a video?'), lines(['רק את שם קובץ הפרויקט', 'Only the project filename'], ['רק את גודל הכותרת', 'Only the title size'], ['את הקובץ המיוצא מתחילתו ועד סופו', 'The exported file from beginning to end']), 2, l('הקובץ המיוצא הוא מה שהצופה יקבל בפועל.', 'The exported file is what the viewer will actually receive.')) }),
      ]),
    ],
  },
  {
    id: 'ai', title: l('התחלה חכמה עם כלי AI', 'Get started with AI tools'), description: l('למדו לנסח בקשות, לבדוק תשובות ולבנות תהליך עבודה ששומר על פרטיות.', 'Learn to write requests, verify responses, and build a workflow that protects privacy.'), category: 'ai', level: 'beginner', durationDays: 7, dailyMinutes: 20, price: 0, creator: 'LEVELUP Studio', cover: '/covers/ai.svg',
    chapters: [
      chapter('ai-brief', l('01 · בקשה ברורה', '01 · Clear requests'), [
        task({ id: 'ai-task', title: l('מפרידים משימה מהבטחה', 'Separate a task from a promise'), description: l('AI יכול לסייע בטיוטות ובהסברים, אך תשובה משכנעת אינה הוכחה לנכונות.', 'AI can help with drafts and explanations, but a persuasive response is not proof of accuracy.'), objective: l('שתי משימות מתאימות לסיוע AI ודבר אחד שחייב אימות אנושי.', 'Two tasks suitable for AI assistance and one thing requiring human verification.'), minutes: 15, type: 'practice', instructions: lines(['בחרו משימה לימודית קטנה, למשל ארגון סיכום לפי נושאים.', 'Choose a small learning task such as organizing notes by topic.'], ['כתבו מה הכלי יעשה ומה אתם תבדקו בעצמכם.', 'Write what the tool will do and what you will check yourself.'], ['הוסיפו דוגמה לטענה שאינה מתקבלת בלי מקור. שלחו את החלוקה.', 'Add an example of a claim you would not accept without a source. Submit your split of responsibilities.']), example: l('AI יארגן את הסיכום; אני אשווה את התאריכים וההגדרות לספר הלימוד.', 'AI organizes the notes; I compare dates and definitions against the textbook.'), hints: lines(['אין להעביר לכלי סיסמאות או מידע פרטי של אדם אחר.', 'Do not send passwords or another person’s private information to a tool.']), question: q(l('האם ניסוח בטוח מוכיח שתשובת AI נכונה?', 'Does confident wording prove an AI answer is correct?'), lines(['כן, תמיד', 'Yes, always'], ['לא; עדיין צריך לבדוק טענות', 'No; claims still need checking'], ['רק אם התשובה ארוכה', 'Only if the answer is long']), 1, l('סגנון התשובה אינו מנגנון אימות.', 'The style of a response is not a verification mechanism.')) }),
        task({ id: 'ai-prompt', title: l('בונים בקשה עם ארבעה חלקים', 'Build a four-part prompt'), description: l('מטרה, הקשר, מגבלות ופורמט עוזרים לקבל טיוטה שימושית.', 'A goal, context, constraints, and format help produce a useful draft.'), objective: l('בקשה הכוללת את ארבעת החלקים והגדרת הצלחה.', 'A request containing all four parts and a success criterion.'), minutes: 20, type: 'practice', instructions: lines(['בחרו נושא שאתם כבר מכירים כדי שתוכלו לבדוק את התשובה.', 'Choose a subject you already know so you can check the response.'], ['כתבו למי ההסבר מיועד, מה לכלול, מה לא לכלול ומה אורך התוצאה.', 'State the audience, what to include, what to omit, and the response length.'], ['בקשו דוגמה אחת ובדקו שהיא מתאימה למטרה. הגישו בקשה והערכה קצרה.', 'Ask for one example and check that it fits the goal. Submit the prompt and a brief evaluation.']), example: l('הסבר למתחיל מהו משתנה ב־JavaScript. עד 100 מילים, בלי ספריות, עם דוגמת let אחת ושאלה לבדיקה.', 'Explain JavaScript variables to a beginner in up to 100 words, without libraries, with one let example and one check question.'), hints: lines(['כתבו מה תוצאה טובה צריכה לאפשר לכם לעשות.', 'Describe what a good result should enable you to do.']), question: q(l('איזו תוספת עוזרת להתאים הסבר?', 'Which detail helps tailor an explanation?'), lines(['רמת הקורא והמטרה', 'The reader’s level and goal'], ['סיסמת החשבון', 'The account password'], ['הוראה להמציא מקורות', 'An instruction to invent sources']), 0, l('הקשר רלוונטי עוזר לבחור פירוט ושפה מתאימים.', 'Relevant context helps choose the appropriate detail and language.')) }),
      ]),
      chapter('ai-review', l('02 · בודקים ומשפרים', '02 · Verify and improve'), [
        task({ id: 'ai-verify', title: l('בודקים שלוש טענות', 'Verify three claims'), description: l('הפרידו בין טענה עובדתית, דעה והצעה לפני שמסתמכים על תשובה.', 'Separate facts, opinions, and suggestions before relying on a response.'), objective: l('טבלה של שלוש טענות, מקור ראשוני ומסקנת אימות.', 'A table of three claims, primary sources, and verification conclusions.'), minutes: 25, type: 'practice', instructions: lines(['קחו תשובה לימודית קצרה וסמנו שלוש טענות עובדתיות.', 'Take a short educational response and mark three factual claims.'], ['פתחו מקור רשמי רלוונטי לכל טענה ובדקו שהוא אכן אומר זאת.', 'Open a relevant official source for each claim and verify it actually supports the statement.'], ['כתבו מאומת, סותר או לא נמצא. תקנו טענה שלא אושרה.', 'Mark verified, contradicted, or not found. Correct an unverified claim.']), example: l('טענה: HTML מתאר מבנה תוכן. מקור: MDN. מסקנה: תואם את ההסבר הרשמי.', 'Claim: HTML describes content structure. Source: MDN. Conclusion: consistent with the official explanation.'), hints: lines(['קישור שנראה אמין אינו מספיק; פתחו וקראו אותו.', 'A credible-looking link is not enough; open and read it.']), question: q(l('מהו אימות מקור?', 'What does source verification involve?'), lines(['ספירת מספר הקישורים', 'Counting links'], ['קריאת הכותרת בלבד', 'Reading only the title'], ['בדיקת התוכן מול הטענה', 'Checking source content against the claim']), 2, l('המקור צריך לתמוך בטענה המסוימת, לא רק לעסוק באותו נושא.', 'A source must support the specific claim, not merely discuss the same topic.')) }),
        task({ id: 'ai-iterate', title: l('משפרים בקשה לפי קריטריונים', 'Improve a prompt using criteria'), description: l('משוב ממוקד עוזר יותר מבקשה כללית כמו תעשה טוב יותר.', 'Specific feedback helps more than a vague request to make it better.'), objective: l('שתי גרסאות בקשה והשוואה לפי דיוק, בהירות ושימושיות.', 'Two prompt versions compared for accuracy, clarity, and usefulness.'), minutes: 20, type: 'practice', instructions: lines(['תנו לטיוטה ציון 1–3 בכל אחד משלושת הקריטריונים.', 'Rate a draft from 1–3 on each of the three criteria.'], ['בחרו בעיה אחת ובקשו שינוי קונקרטי, למשל הוספת דוגמה חסרה.', 'Choose one issue and request a concrete change, such as adding a missing example.'], ['השוו מחדש וציינו אם השינוי שיפר את הבעיה או יצר בעיה אחרת.', 'Compare again and note whether the revision improved the issue or introduced another.']), example: l('ההסבר משתמש במילה שלא הוגדרה. הוסף משפט שמגדיר אותה, בלי להאריך מעבר ל־120 מילים.', 'The explanation uses an undefined term. Add one sentence defining it while staying under 120 words.'), hints: lines(['שנו דבר אחד בכל פעם כדי להבין מה עזר.', 'Change one thing at a time to understand what helped.']), question: q(l('איזה משוב הוא הממוקד ביותר?', 'Which feedback is most specific?'), lines(['הוסף דוגמה שמדגימה לולאת for', 'Add an example demonstrating a for loop'], ['תעשה טוב יותר', 'Make it better'], ['כתוב הכול מחדש בלי מטרה', 'Rewrite everything without a goal']), 0, l('משוב קונקרטי מגדיר שינוי שאפשר לבדוק בתוצאה.', 'Concrete feedback defines a change that can be checked in the result.')) }),
      ]),
      chapter('ai-workflow', l('03 · עבודה אחראית', '03 · Responsible workflows'), [
        task({ id: 'ai-privacy', title: l('מצמצמים מידע לפני השליחה', 'Minimize data before sharing'), description: l('שלחו רק את המידע שנדרש למשימה והחליפו פרטים אישיים בדוגמאות.', 'Share only what is necessary and replace personal details with examples.'), objective: l('גרסה נקייה של מסמך דמיוני ורשימת הפרטים שהוסרו.', 'A cleaned fictional document and a list of removed details.'), minutes: 20, type: 'practice', instructions: lines(['כתבו טקסט דמיוני עם שם, כתובת ומטרת לימוד. אין להשתמש בפרטים אמיתיים.', 'Write fictional text containing a name, address, and learning goal. Do not use real details.'], ['החליפו שם בכינוי ומחקו כתובת ומספר טלפון שאינם נדרשים.', 'Replace the name with an alias and remove unnecessary address and phone details.'], ['בדקו אם עדיין אפשר לבצע את המשימה. שלחו רק את הגרסה הנקייה.', 'Check whether the task can still be done. Submit only the cleaned version.']), example: l('לפני: פרטים אישיים מיותרים. אחרי: לומד מתחיל, 20 דקות ביום, רוצה לתרגל HTML.', 'Before: unnecessary personal details. After: beginner learner, 20 minutes a day, wants to practice HTML.'), hints: lines(['מידע רפואי, פיננסי וסיסמאות אינם נחוצים ליצירת סיכום לימודי.', 'Medical information, financial details, and passwords are unnecessary for creating study notes.']), question: q(l('איזה מידע נחוץ לתוכנית תרגול?', 'Which detail is useful for a practice plan?'), lines(['מספר תעודת זהות', 'An identity number'], ['רמת הידע והזמן הזמין', 'Current level and available time'], ['סיסמת האימייל', 'An email password']), 1, l('רמה וזמן מאפשרים התאמה בלי לחשוף מזהים רגישים.', 'Level and time support personalization without exposing sensitive identifiers.')) }),
        task({ id: 'ai-final', title: l('פרויקט סיום: ערכת עבודה עם AI', 'Final project: an AI workflow kit'), description: l('בנו תהליך קטן שאפשר לחזור עליו ולבדוק את התוצאה בכל פעם.', 'Build a small repeatable process whose output can be checked each time.'), objective: l('תבנית בקשה, דוגמת קלט, תוצאה בדוקה ורשימת בקרת איכות.', 'A prompt template, example input, verified output, and a quality checklist.'), minutes: 30, type: 'project', instructions: lines(['בחרו תהליך כגון סיכום שיעור לשלוש נקודות ושתי שאלות.', 'Choose a process such as summarizing a lesson into three points and two questions.'], ['כתבו תבנית עם מקום לנושא, לרמה ולמטרה. הפעילו על דוגמה אחת.', 'Write a template with fields for topic, level, and goal. Run it on one example.'], ['בדקו עובדות ופרטיות, תעדו תיקון והגישו את כל הערכה.', 'Check facts and privacy, document a correction, and submit the kit.']), example: l('רשימת בדיקה: תואם למקור, אין נתונים אישיים, שתי שאלות עם תשובות שניתן להסביר.', 'Checklist: consistent with the source, no personal data, two questions with explainable answers.'), hints: lines(['ציינו בגלוי שהטיוטה נעזרה ב־AI ומה בדקתם בעצמכם.', 'Clearly state where AI helped and what you checked yourself.']), question: q(l('מה הופך תהליך AI לאמין יותר?', 'What makes an AI workflow more dependable?'), lines(['ביטול כל בדיקה', 'Removing all checks'], ['פרסום אוטומטי של כל תשובה', 'Automatically publishing every response'], ['קריטריונים ברורים ובדיקה אנושית', 'Clear criteria and human review']), 2, l('תהליך עם קריטריונים ובדיקה מאפשר לזהות ולתקן שגיאות לפני שימוש.', 'Criteria and review help detect and correct errors before use.')) }),
      ]),
    ],
  },


  {
    id: 'content', title: l('יוצרים ערוץ תוכן עם כיוון', 'Create a focused content channel'), description: l('בחרו קהל ונושא, הכינו שלושה פרסומים ותכננו קצב יצירה אפשרי.', 'Choose an audience and topic, prepare three posts, and plan a realistic publishing rhythm.'), category: 'content', level: 'beginner', durationDays: 14, dailyMinutes: 20, price: 0, creator: 'LEVELUP Studio', cover: '/covers/content.svg',
    chapters: [
      chapter('content-focus', l('01 · קהל וזווית', '01 · Audience and angle'), [
        task({ id: 'content-audience', title: l('בוחרים למי לעזור', 'Choose whom to help'), description: l('נושא מצומצם מאפשר ליצור תוכן שימושי וברור.', 'A focused topic makes useful, clear content easier to create.'), objective: l('משפט אחד שמגדיר קהל, בעיה ותועלת.', 'One sentence defining an audience, a problem, and a benefit.'), minutes: 15, type: 'practice', instructions: lines(['בחרו תחום שאתם יכולים להדגים בעצמכם, כמו ציור או תכנון זמן.', 'Choose an area you can demonstrate yourself, such as drawing or time planning.'], ['הגדירו קהל באמצעות צורך, בלי לאסוף מידע אישי עליו.', 'Define an audience by a need without collecting personal information.'], ['כתבו שלוש שאלות שהקהל עשוי לשאול והגישו את המשפט והשאלות.', 'Write three questions the audience might ask and submit the statement and questions.']), example: l('אני עוזר למתחילים בציור לצייר חפץ פשוט בעשר דקות.', 'I help drawing beginners sketch a simple object in ten minutes.'), hints: lines(['תחום אחד בתחילת הדרך מקל על בחירת רעיונות.', 'Starting with one area makes choosing ideas easier.']), question: q(l('איזו הגדרת קהל היא הממוקדת ביותר?', 'Which audience definition is most focused?'), lines(['כל העולם', 'Everyone in the world'], ['מתחילים שרוצים לצייר חפץ פשוט', 'Beginners who want to draw a simple object'], ['כל מי שיש לו טלפון', 'Anyone with a phone']), 1, l('הגדרה לפי צורך מסוים עוזרת לתכנן תוכן שימושי.', 'A specific need helps guide useful content.')) }),
        task({ id: 'content-pillars', title: l('מכינים שלושה סוגי פרסומים', 'Plan three types of posts'), description: l('תמהיל קטן של פורמטים שומר על גיוון בלי לאבד כיוון.', 'A small mix of formats adds variety without losing focus.'), objective: l('שלושה רעיונות: הדרכה, טעות נפוצה ודוגמה לפני ואחרי.', 'Three ideas: a tutorial, a common mistake, and a before-and-after example.'), minutes: 20, type: 'practice', instructions: lines(['הפכו שאלה אחת של הקהל להדרכה קצרה.', 'Turn one audience question into a short tutorial.'], ['כתבו טעות שאתם יודעים להסביר ולתקן.', 'Write a mistake you can explain and correct.'], ['תכננו דוגמה מקורית שמראה שינוי. הגדירו מה ילמדו מכל פרסום.', 'Plan an original example showing a change. Define what each post teaches.']), example: l('הדרכה: ציור כוס; טעות: אליפסה לא אחידה; לפני ואחרי: תיקון קו המתאר.', 'Tutorial: drawing a cup; mistake: an uneven ellipse; before and after: correcting the outline.'), hints: lines(['אל תבטיחו תוצאה שאינכם יכולים להדגים.', 'Do not promise a result you cannot demonstrate.']), question: q(l('מה מחבר שלושה פרסומים לאותו ערוץ?', 'What connects three posts to the same channel?'), lines(['צורך משותף של הקהל', 'A shared audience need'], ['שימוש בשלושה צבעים שונים', 'Three different colors'], ['כותרות שאינן קשורות לתוכן', 'Titles unrelated to the content']), 0, l('תוכן יכול להשתנות בפורמט ועדיין לענות על אותו צורך.', 'Posts can differ in format while serving the same need.')) }),
      ]),
      chapter('content-make', l('02 · יצירה אחראית', '02 · Responsible creation'), [
        task({ id: 'content-script', title: l('כותבים פתיחה שמקיימת הבטחה', 'Write an opening that delivers'), description: l('פתיחה טובה מבהירה מה יקבל הצופה בלי להטעות.', 'A good opening explains what viewers will get without misleading them.'), objective: l('תסריט של 120–180 מילים עם פתיחה, שלושה צעדים וסיום.', 'A 120–180 word script with an opening, three steps, and a conclusion.'), minutes: 25, type: 'practice', instructions: lines(['כתבו פתיחה שמציגה תוצאה קטנה ומדויקת.', 'Write an opening that describes a small, precise outcome.'], ['הוסיפו שלושה צעדים שכל אחד מציג פעולה אחת.', 'Add three steps with one action each.'], ['סיימו במשימה לצופה ובדקו שכל הבטחה מהפתיחה מופיעה בתסריט.', 'End with a viewer exercise and check that the script fulfills every opening promise.']), example: l('בעוד דקה תדעו לצייר קו מתאר של כוס בשלושה צעדים.', 'In a minute, you will know a three-step way to sketch a cup outline.'), hints: lines(['החליפו מילים כמו מושלם או מובטח בתוצאה שאפשר לבדוק.', 'Replace words such as perfect or guaranteed with a testable outcome.']), question: q(l('מה כדאי לבדוק בכותרת?', 'What should you check about a title?'), lines(['שהיא מבטיחה הכול', 'That it promises everything'], ['שהיא מסתירה את הנושא', 'That it hides the topic'], ['שהתוכן מקיים את מה שהיא מבטיחה', 'That the content delivers what it promises']), 2, l('התאמה בין כותרת לתוכן עוזרת לשמור על אמון.', 'Matching the title to the content helps maintain trust.')) }),
        task({ id: 'content-rights', title: l('בודקים פרטיות ורשות שימוש', 'Check privacy and permissions'), description: l('יצירה בטוחה כוללת בדיקה של מי ומה מופיעים בפרסום.', 'Responsible creation includes checking who and what appear in a post.'), objective: l('רשימת נכסים עם מקור, רשות שימוש ובדיקת מידע אישי.', 'An asset list with sources, permissions, and a personal-information check.'), minutes: 20, type: 'practice', instructions: lines(['רשמו כל תמונה, צליל וציטוט בתוכן.', 'List every image, sound, and quotation in the content.'], ['השתמשו בחומר מקורי או רשמו את הרישיון ותנאיו לפני שימוש בחומר חיצוני.', 'Use original material or record license terms before using external material.'], ['הסירו מיקום מדויק ופרטים מזהים שאינם נחוצים. קטינים יערבו הורה בהחלטת פרסום.', 'Remove unnecessary exact locations and identifying details. Minors should involve a parent in publishing decisions.']), example: l('תמונה מקורית; מוזיקה מקורית; אין לוגו בית ספר, כתובת או אנשים ללא רשות.', 'Original image; original music; no school logo, address, or people without permission.'), hints: lines(['תוכן שנמצא באינטרנט אינו בהכרח מותר לשימוש מחדש.', 'Content found online is not automatically available for reuse.']), question: q(l('האם תמונה באינטרנט תמיד מותרת לשימוש?', 'Can any online image be reused?'), lines(['לא; צריך לבדוק הרשאה או רישיון', 'No; permission or license terms must be checked'], ['כן, אם היא יפה', 'Yes, if it looks nice'], ['כן, אם משנים את השם', 'Yes, if renamed']), 0, l('זמינות לצפייה אינה זהה להרשאה להעתקה ולפרסום.', 'Being viewable is not the same as permission to copy and publish.')) }),
      ]),
      chapter('content-learn', l('03 · פרסום ולמידה', '03 · Publish and learn'), [
        task({ id: 'content-schedule', title: l('בונים לוח יצירה שאפשר לקיים', 'Build a manageable creation schedule'), description: l('קצב קטן וקבוע מאפשר ללמוד מהתהליך בלי להעמיס.', 'A small, regular schedule lets you learn without overloading yourself.'), objective: l('לוח לשבועיים עם שני פרסומים וזמן לבדיקת איכות.', 'A two-week schedule with two posts and time for quality checks.'), minutes: 20, type: 'practice', instructions: lines(['חלקו יצירה לתכנון, הכנה, בדיקה ופרסום.', 'Divide creation into planning, production, checking, and publishing.'], ['שבצו זמן שמתאים ללימודים ולמנוחה, והוסיפו מרווח לתיקונים.', 'Schedule around study and rest, leaving a buffer for revisions.'], ['בחרו מדד אחד ללמידה, למשל האם צופה מבין את הצעד הראשון.', 'Choose one learning measure, such as whether a viewer understands the first step.']), example: l('יום א: תסריט; יום ג: צילום; יום ה: בדיקת אדם מוכר; יום ו: פרסום פרטי.', 'Sunday: script; Tuesday: filming; Thursday: review by someone you know; Friday: private publication.'), hints: lines(['מספר עוקבים אינו המדד היחיד. התחילו בבהירות וביכולת לעמוד בתהליך.', 'Follower count is not the only measure. Begin with clarity and a sustainable process.']), question: q(l('איזה מדד עוזר לשפר הדרכה?', 'Which measure helps improve a tutorial?'), lines(['כמה צבעים הופיעו בה', 'How many colors it contains'], ['האם צופה הצליח לבצע את הצעד', 'Whether a viewer could perform the step'], ['כמה הבטחות נכתבו', 'How many promises were written']), 1, l('ביצוע הצעד בודק ישירות את התועלת של ההדרכה.', 'Performing the step directly tests the tutorial’s usefulness.')) }),
        task({ id: 'content-final', title: l('פרויקט סיום: ערכת ערוץ ראשונה', 'Final project: a first channel kit'), description: l('הכינו שלושה פרסומים שניתן להציג בפרטיות לפני חשיפה רחבה.', 'Prepare three posts that can be shared privately before a wider release.'), objective: l('תיאור ערוץ, שלושה פרסומים מקוריים, לוח עבודה ודוח משוב קצר.', 'A channel description, three original posts, a schedule, and a short feedback report.'), minutes: 40, type: 'project', instructions: lines(['חברו את שלושת סוגי הפרסומים לאותה שפה חזותית פשוטה.', 'Give the three post types a consistent, simple visual style.'], ['בקשו מאדם מוכר לבדוק בהירות ופרטיות. תעדו שני שיפורים.', 'Ask someone you know to review clarity and privacy. Document two improvements.'], ['הגישו קבצים או קישורים פרטיים ואת ערכת הערוץ. אין חובה לפתוח חשבון ציבורי.', 'Submit files or private links and the channel kit. A public account is not required.']), example: l('תיאור: ציור למתחילים בעשר דקות; שלושה תכנים; בדיקת זכויות; לוח שבועיים.', 'Description: ten-minute drawing for beginners; three posts; permissions check; two-week schedule.'), hints: lines(['אל תשלמו על קידום לפני שהבנתם אם התוכן ברור ושימושי.', 'Understand whether the content is clear and useful before considering paid promotion.']), question: q(l('מה נכון לעשות לפני חשיפה רחבה?', 'What is useful before a wider release?'), lines(['להציג נתוני צפייה מומצאים', 'Show invented view counts'], ['להעתיק תוכן של אחרים', 'Copy other people’s content'], ['לקבל משוב ולבדוק פרטיות', 'Collect feedback and check privacy']), 2, l('משוב ובדיקת פרטיות מאפשרים לתקן בעיות לפני פרסום.', 'Feedback and privacy checks help correct problems before publication.')) }),
      ]),
    ],
  },
  {
    id: 'business', title: l('יסודות יזמות לנוער', 'Entrepreneurship foundations for teens'), description: l('זהו צורך, בדקו רעיון ובנו אבטיפוס קטן בלי להתחייב להוצאות או להכנסה מובטחת.', 'Identify a need, test an idea, and build a small prototype without committing to spending or promised income.'), category: 'business', level: 'beginner', durationDays: 14, dailyMinutes: 20, price: 0, creator: 'LEVELUP Studio', cover: '/covers/business.svg',
    chapters: [
      chapter('business-discover', l('01 · מבינים צורך', '01 · Understand a need'), [
        task({ id: 'business-problem', title: l('מתארים בעיה לפני פתרון', 'Describe a problem before a solution'), description: l('רעיון מתחיל בקושי שאפשר להסביר ולבדוק.', 'An idea begins with a difficulty that can be explained and checked.'), objective: l('הגדרת בעיה, קהל ומצב שבו היא מתרחשת.', 'A problem statement, audience, and situation in which it occurs.'), minutes: 20, type: 'practice', instructions: lines(['בחרו קושי יומיומי קטן שאתם מכירים, למשל שכחת ציוד לחוג.', 'Choose a small everyday difficulty you know, such as forgetting supplies for an activity.'], ['תארו מי נתקל בו, מתי ומה הוא עושה היום.', 'Describe who experiences it, when, and what they currently do.'], ['הפרידו עובדות שראיתם מהשערות שטרם בדקתם.', 'Separate observed facts from untested assumptions.']), example: l('השערה: תלמידים שוכחים ציוד כי הרשימה מפוזרת בין כמה הודעות.', 'Hypothesis: students forget supplies because the list is spread across several messages.'), hints: lines(['בעיה קטנה ומוגדרת עדיפה לניסוי ראשון על רעיון שמנסה לפתור הכול.', 'A small, specific problem is more suitable for a first experiment than an idea addressing everything.']), question: q(l('מה כדאי להגדיר לפני בחירת פתרון?', 'What should you define before choosing a solution?'), lines(['לוגו יקר', 'An expensive logo'], ['את הבעיה והקהל', 'The problem and audience'], ['הבטחת רווח', 'A profit guarantee']), 1, l('הבנת הבעיה והקהל עוזרת לבחור פתרון שניתן לבדוק.', 'Understanding the problem and audience guides a testable solution.')) }),
        task({ id: 'business-interview', title: l('שואלים שאלות בלי להוביל', 'Ask non-leading questions'), description: l('סיפורים על התנהגות אמיתית מועילים יותר ממחמאה על רעיון.', 'Stories about real behavior are more useful than compliments about an idea.'), objective: l('שלוש שאלות פתוחות וסיכום שיחה עם אדם מוכר בהסכמתו.', 'Three open questions and notes from a conversation with a consenting person you know.'), minutes: 25, type: 'practice', instructions: lines(['כתבו שאלות על הפעם האחרונה שבה הבעיה קרתה.', 'Write questions about the last time the problem occurred.'], ['בקשו רשות לשיחה קצרה מאדם מוכר; אין לאסוף פרטי קשר או להקליט ללא הסכמה.', 'Ask someone you know for a short conversation; do not collect contact details or record without permission.'], ['סכמו בלי שם: מה קרה, מה ניסו ומה היה קשה.', 'Summarize without a name: what happened, what they tried, and what was difficult.']), example: l('ספרו על הפעם האחרונה ששכחתם ציוד. איך גיליתם? מה עשיתם אז?', 'Tell me about the last time you forgot supplies. How did you notice? What did you do next?'), hints: lines(['הימנעו מ־נכון שהרעיון שלי מעולה? זו שאלה שמובילה לתשובה.', 'Avoid Isn’t my idea great? That question leads the answer.']), question: q(l('איזו שאלה הכי פחות מובילה?', 'Which question is least leading?'), lines(['מה עשית בפעם האחרונה שזה קרה?', 'What did you do the last time it happened?'], ['ברור שתקנה את זה, נכון?', 'You would obviously buy this, right?'], ['הרעיון שלי מעולה, נכון?', 'My idea is great, right?']), 0, l('שאלה על אירוע אמיתי מזמינה תיאור בלי לרמוז לתשובה הרצויה.', 'A question about a real event invites description without suggesting the desired answer.')) }),
      ]),
      chapter('business-test', l('02 · בודקים פתרון קטן', '02 · Test a small solution'), [
        task({ id: 'business-value', title: l('מנסחים הצעת ערך', 'Write a value proposition'), description: l('הצעת ערך מסבירה למי עוזרים, באיזה קושי ובאיזה אופן.', 'A value proposition states whom you help, with which difficulty, and how.'), objective: l('שתי חלופות פתרון ובחירה מנומקת באחת.', 'Two possible solutions and a reasoned choice of one.'), minutes: 20, type: 'practice', instructions: lines(['הציעו פתרון ידני פשוט ופתרון דיגיטלי קטן לאותה בעיה.', 'Suggest one simple manual and one small digital solution to the same problem.'], ['השוו מאמץ, נגישות ומידת העזרה לקהל.', 'Compare effort, accessibility, and usefulness to the audience.'], ['בחרו את הדרך הקטנה ביותר לבדוק את ההשערה וכתבו את הצעת הערך.', 'Choose the smallest way to test the hypothesis and write the value proposition.']), example: l('רשימת ציוד אחת שאפשר לסמן, כדי שכל מה שצריך לחוג יהיה במקום אחד.', 'One checkable supplies list so everything needed for the activity is in one place.'), hints: lines(['לא כל פתרון צריך אפליקציה או הוצאה כספית.', 'Not every solution needs an app or spending.']), question: q(l('מהי הצעת ערך ברורה?', 'Which value proposition is clear?'), lines(['הפתרון הכי מדהים בעולם', 'The most amazing solution ever'], ['מוצר שיעשה הכול', 'A product that does everything'], ['רשימה אחת שמרכזת ציוד לחוג', 'One list that organizes supplies for an activity']), 2, l('האפשרות מתארת תועלת מסוימת שניתן להדגים.', 'This option describes a specific benefit that can be demonstrated.')) }),
        task({ id: 'business-prototype', title: l('בונים אבטיפוס בלי הוצאה', 'Build a no-spend prototype'), description: l('אבטיפוס בודק רעיון; הוא לא חייב להיות מוצר מוגמר.', 'A prototype tests an idea; it does not need to be a finished product.'), objective: l('אבטיפוס נייר או מסך שמדגים פעולה מרכזית אחת.', 'A paper or screen prototype demonstrating one central action.'), minutes: 30, type: 'practice', instructions: lines(['בחרו פעולה אחת, למשל סימון פריט ברשימת ציוד.', 'Choose one action, such as checking an item on a supplies list.'], ['ציירו את המצב לפני ואחרי הפעולה והוסיפו הוראה קצרה.', 'Draw the state before and after the action and add a short instruction.'], ['תנו לאדם מוכר לנסות בלי להסביר. רשמו תקלה אחת ושפרו.', 'Let someone you know try it without explanation. Record one difficulty and improve it.']), example: l('דף עם חמישה פריטים ותיבת סימון לכל פריט; בסיום מופיע הכל מוכן.', 'A page with five items and a checkbox for each; a completion state says Everything is ready.'), hints: lines(['שמרו את המשוב על התהליך, לא על פרטים אישיים של הבודק.', 'Keep feedback about the process rather than the tester’s personal details.']), question: q(l('מה תפקיד אבטיפוס ראשון?', 'What is the role of a first prototype?'), lines(['לבדוק השערה על פעולה מרכזית', 'Test a hypothesis about a central action'], ['להבטיח מכירות', 'Guarantee sales'], ['להוכיח שהכול מוכן', 'Prove everything is finished']), 0, l('האבטיפוס מאפשר ללמוד על שימושיות לפני השקעה נוספת.', 'A prototype lets you learn about usability before further investment.')) }),
      ]),
      chapter('business-next', l('03 · מודדים ולומדים', '03 · Measure and learn'), [
        task({ id: 'business-numbers', title: l('מבדילים הכנסה מעלות', 'Distinguish revenue from cost'), description: l('תרגיל חשבוני עם מספרים דמיוניים עוזר להבין את מבנה הרעיון.', 'A calculation with fictional numbers helps explain the structure of an idea.'), objective: l('חישוב הכנסה ועלות בדוגמה דמיונית ורשימת הנחות.', 'A revenue and cost calculation using fictional figures and a list of assumptions.'), minutes: 20, type: 'quiz', instructions: lines(['נניח שמוכרים 10 יחידות דמיוניות במחיר 5 ₪ כל אחת.', 'Assume 10 fictional units are sold at ₪5 each.'], ['העלות המשתנה היא 2 ₪ ליחידה ועלות הכנה דמיונית היא 10 ₪. חשבו הכנסה ועלות כוללת.', 'Variable cost is ₪2 per unit and fictional setup cost is ₪10. Calculate revenue and total cost.'], ['כתבו שהדוגמה אינה תחזית ואינה כוללת את כל העלויות האפשריות. אין לבצע רכישה או מכירה.', 'State that the example is not a forecast and does not include every possible cost. Do not make a purchase or sale.']), example: l('הכנסה 50 ₪; עלות משתנה 20 ₪; הכנה 10 ₪; ההפרש בדוגמה 20 ₪.', 'Revenue ₪50; variable cost ₪20; setup ₪10; the example’s difference is ₪20.'), hints: lines(['הכנסה היא מחיר כפול כמות; היא אינה זהה לרווח.', 'Revenue is price multiplied by quantity; it is not the same as profit.']), question: q(l('מה ההכנסה ממכירת 10 יחידות ב־5 ₪?', 'What is the revenue from 10 units at ₪5 each?'), lines(['20 ₪', '₪20'], ['50 ₪', '₪50'], ['5 ₪', '₪5']), 1, l('10 כפול 5 הם 50. העלויות מחושבות בנפרד.', '10 multiplied by 5 equals 50. Costs are calculated separately.')) }),
        task({ id: 'business-final', title: l('פרויקט סיום: ניסוי יזמי קטן', 'Final project: a small entrepreneurship experiment'), description: l('סכמו מה למדתם והחליטו על הצעד הבא לפי הראיות.', 'Summarize what you learned and decide the next step using evidence.'), objective: l('מסמך בן עמוד עם בעיה, אבטיפוס, משוב, חישוב דמיוני והחלטה.', 'A one-page document with a problem, prototype, feedback, fictional calculation, and decision.'), minutes: 40, type: 'project', instructions: lines(['רשמו אילו השערות קיבלו תמיכה ואילו נותרו פתוחות.', 'Record which assumptions gained support and which remain open.'], ['בחרו להמשיך, לשנות או לעצור והסבירו לפי המשוב.', 'Choose to continue, change, or stop and explain using feedback.'], ['הגישו מסמך ואבטיפוס. כל פעילות עסקית אמיתית בהמשך מחייבת מעורבות מבוגר ובדיקת הדרישות המקומיות.', 'Submit the document and prototype. Any future real business activity requires adult involvement and checking local requirements.']), example: l('שניים הצליחו לסמן ציוד; אחד לא הבין איך לאפס. הצעד הבא: כפתור איפוס ברור ובדיקה נוספת.', 'Two people checked their supplies; one could not reset. Next step: a clear reset button and another test.'), hints: lines(['החלטה לעצור רעיון אחרי בדיקה היא תוצאת למידה מועילה.', 'Choosing to stop an idea after testing is a useful learning outcome.']), question: q(l('על מה כדאי לבסס את הצעד הבא?', 'What should guide the next step?'), lines(['מספרים מומצאים שמוצגים כאמיתיים', 'Invented numbers presented as real'], ['רק התלהבות מהרעיון', 'Only excitement about the idea'], ['משוב וראיות מהניסוי', 'Feedback and evidence from the experiment']), 2, l('משוב וראיות עוזרים לבחור שינוי שמטפל בבעיה שנצפתה.', 'Feedback and evidence help choose a change that addresses an observed problem.')) }),
      ]),
    ],
  },
];

const resourcesByPath: Record<string, { title: string; url: string }[]> = {
  website: [{ title: 'MDN · Your first website', url: 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Getting_started/Your_first_website' }],
  app: [{ title: 'React · Learn', url: 'https://react.dev/learn' }],
  game: [{ title: 'Three.js · Manual', url: 'https://threejs.org/manual/#en/fundamentals' }],
  english: [{ title: 'British Council · A1 speaking', url: 'https://learnenglish.britishcouncil.org/free-resources/speaking/a1' }],
  video: [{ title: 'Blackmagic Design · DaVinci Resolve Training', url: 'https://www.blackmagicdesign.com/products/davinciresolve/training' }],
  ai: [{ title: 'UNICEF · Guidance on AI and children', url: 'https://www.unicef.org/innocenti/reports/policy-guidance-ai-children' }],
  content: [{ title: 'Creative Commons · Licenses', url: 'https://creativecommons.org/cc-licenses/' }],
  business: [{ title: 'SBA · Plan your business', url: 'https://www.sba.gov/counseling/plan-your-business/' }],
};
for (const path of learningPaths) {
  for (const unit of path.chapters) {
    for (const lesson of unit.tasks) lesson.resources = resourcesByPath[path.id];
  }
}


