/**
 * Exercise catalog – Part A: warm-up drills (wu-*), backhand (bh-*), forehand (fh-*), hammer (hm-*).
 * Every entry here matches its row in src/content/manifest.ts (id, name, category, skills, roles,
 * participants, equipment, levels, intensity are copied verbatim from the manifest).
 * fh-short-gate lives in ./example.ts (the quality bar) and is re-used here.
 */
import type { Exercise } from "@/lib/types";
import { fhShortGate } from "./example";

const ALL_FIELDS: Exercise["fieldSizes"] = ["small", "medium", "large", "indoor", "park", "beach", "yard"];
const OPEN_FIELDS: Exercise["fieldSizes"] = ["small", "medium", "large", "park", "beach"];
const ALL_AGES: Exercise["ageGroups"] = ["kid", "teen", "adult", "senior"];

/* ------------------------------------------------------------------ */
/* Warm-up                                                              */
/* ------------------------------------------------------------------ */

const wuDynamicJog: Exercise = {
  id: "wu-dynamic-jog",
  name: { he: "ריצה קלה ומוביליטי", en: "Light jog & mobility" },
  category: "warmup",
  skills: ["warmup", "mobility"],
  roles: [],
  levels: ["beginner", "intermediate", "advanced"],
  phases: ["warmup"],
  goal: { he: "להעלות דופק וטמפרטורת שרירים בהדרגה ולפתוח ירכיים, קרסוליים וגו לפני עבודה מהירה.", en: "Raise heart rate and muscle temperature gradually and open the hips, ankles and trunk before fast work." },
  participants: ["solo", "pair", "group"],
  equipment: [],
  optionalEquipment: ["cones"],
  fieldSizes: ALL_FIELDS,
  intensity: "low",
  offenseDefense: "both",
  wind: "any",
  ageGroups: ALL_AGES,
  durationMinutes: 4,
  minDurationMinutes: 3,
  maxDurationMinutes: 5,
  sets: 1,
  reps: 6,
  restSeconds: 0,
  setup: {
    he: "סמנו קטע של 20 מטר עם שני קונוסים, שני דיסקים או שני חפצים שיש לכם. זה כל מה שצריך.",
    en: "Mark a 20 m stretch with two cones, two discs or whatever you have. That's all you need.",
  },
  instructions: [
    { he: "ריצה קלה של 2 דקות הלוך ושוב לאורך 20 המטרים – בקצב שבו אפשר לדבר משפט שלם.", en: "Jog easily for 2 minutes up and down the 20 m – at a pace where you can still speak a full sentence." },
    { he: "אורך אחד של Skips עם ברכיים גבוהות בקצב מתון, חזרה בהליכה עם סיבובי זרועות גדולים.", en: "One length of high-knee skips at a moderate pace, walk back with big arm circles." },
    { he: "אורך אחד של בעיטות לישבן (Butt Kicks), חזרה בצעדי הצלבה (Carioca) – המותניים מסתובבות, הכתפיים קדימה.", en: "One length of butt kicks, back with carioca crossover steps – hips rotate, shoulders stay square." },
    { he: "הליכת לאנג׳ עם סיבוב גו לכיוון הרגל הקדמית: 8 צעדים לכל רגל.", en: "Walking lunge with a trunk twist toward the front leg: 8 steps per leg." },
    { he: "סיימו ב-2 ריצות של 20 מטר ב-70% מהמהירות עם האטה הדרגתית.", en: "Finish with 2 runs of 20 m at 70% speed, easing down gradually." },
  ],
  cues: [
    { he: "נחיתה רכה על כרית כף הרגל, לא על העקב.", en: "Land softly on the ball of the foot, not the heel." },
    { he: "כתפיים משוחררות, ידיים בגובה המותניים.", en: "Shoulders relaxed, hands at hip height." },
    { he: "טווח התנועה גדל בהדרגה – האורך השני תמיד קצת יותר גדול מהראשון.", en: "Range of motion grows gradually – the second length is always a bit bigger than the first." },
  ],
  commonMistakes: [
    { he: "מתחילים מהר מדי ומגיעים לחלק הזריקות כבר עם נשימה כבדה.", en: "Starting too fast and reaching the throwing block already out of breath." },
    { he: "מדלגים על ה-Skips וה-Carioca ורצים רק ישר – הירכיים נשארות סגורות.", en: "Skipping the skips and carioca and only jogging straight – the hips stay tight." },
  ],
  successMetric: { type: "rating", key: "confidence_rating", label: { he: "עד כמה הגוף מרגיש חם ומוכן (1–5)", en: "How warm and ready the body feels (1–5)" }, target: 4 },
  easierVersion: { he: "הליכה מהירה במקום ריצה, ואורך אחד בלבד מכל תנועה.", en: "Brisk walk instead of a jog, and only one length of each movement." },
  harderVersion: { he: "הוסיפו אורך של Skips לגובה ואורך של ריצה לאחור, וסיימו ב-3 ריצות ב-80%.", en: "Add a length of power skips for height and a length of backpedal, and finish with 3 runs at 80%." },
  soloAlternative: { he: "עובד לבד כפי שהוא – ספרו לעצמכם את האורכים והחזיקו את הקצב בעזרת הנשימה.", en: "Works solo as written – count the lengths yourself and hold the pace by your breathing." },
  partnerAlternative: { he: "רוצו זה לצד זה; מי שמוביל בוחר את התנועה הבאה, ומתחלפים בכל אורך.", en: "Run side by side; the leader picks the next movement, swap every length." },
  safetyNotes: [
    { he: "עברו על המשטח לפני הריצה – בורות, אבנים ודשא רטוב.", en: "Scan the surface before you run – holes, stones and wet grass." },
    { he: "כאב חד בקרסול או בברך – עוצרים ומעדכנים בצ׳ק-אין.", en: "Sharp pain in an ankle or knee – stop and note it in the check-in." },
  ],
  diagram: {
    field: "lane",
    items: [
      { type: "player", x: 12, y: 62 },
      { type: "cone", x: 10, y: 50, label: "0" },
      { type: "cone", x: 90, y: 50, label: "20m" },
      { type: "run", from: [16, 62], to: [86, 62], label: "jog" },
      { type: "run", from: [86, 38], to: [16, 38], dashed: true, label: "walk" },
    ],
  },
  throwsPerSet: 0,
  catchesPerSet: 0,
};

const wuShoulderWrist: Exercise = {
  id: "wu-shoulder-wrist",
  name: { he: "סיבובי כתפיים, מרפקים ושורש כף היד", en: "Shoulder, elbow & wrist circles" },
  category: "warmup",
  skills: ["warmup", "mobility"],
  roles: [],
  levels: ["beginner", "intermediate", "advanced"],
  phases: ["warmup"],
  goal: { he: "להכין את הכתפיים, המרפקים ושורשי כפות הידיים לזריקה – טווח תנועה מלא בלי כאב לפני הדיסק הראשון.", en: "Prepare shoulders, elbows and wrists for throwing – full, pain-free range of motion before the first disc." },
  participants: ["solo", "pair", "group"],
  equipment: [],
  fieldSizes: ALL_FIELDS,
  intensity: "low",
  offenseDefense: "both",
  wind: "any",
  ageGroups: ALL_AGES,
  durationMinutes: 3,
  minDurationMinutes: 3,
  maxDurationMinutes: 5,
  sets: 2,
  reps: 10,
  restSeconds: 0,
  setup: {
    he: "עמידה ברוחב כתפיים עם דיסק ביד. לא צריך שום ציוד נוסף ולא צריך שטח.",
    en: "Stand shoulder-width apart with a disc in hand. No extra equipment and no space needed.",
  },
  instructions: [
    { he: "סיבובי כתפיים בזרועות ישרות: 10 קדימה ו-10 אחורה, מתחילים במעגלים קטנים ומגדילים.", en: "Straight-arm shoulder circles: 10 forward and 10 backward, starting small and growing." },
    { he: "מרפקים: זרועות לצדדים כפופות ב-90°, 10 סיבובים של האמה לכל כיוון.", en: "Elbows: arms out to the sides bent at 90°, 10 forearm rotations each direction." },
    { he: "שורש כף היד: החזיקו את הדיסק ביד אחת ועשו 10 מעגלים לכל כיוון, ואז החליפו יד.", en: "Wrists: hold the disc in one hand and make 10 circles each direction, then swap hands." },
    { he: "זריקות יבשות: 10 Backhand ו-10 Forehand בתנועה איטית עם הדיסק ביד, בלי לשחרר, עם snap בסוף.", en: "Dry throws: 10 backhands and 10 forehands in slow motion holding the disc, no release, with a snap at the end." },
    { he: "סבב שני של הכול בקצב מעט מהיר יותר.", en: "Second round of everything at a slightly quicker tempo." },
  ],
  cues: [
    { he: "תנועה איטית ומלאה – לא מקפצים בין קצוות הטווח.", en: "Slow, full movement – don't bounce between the ends of the range." },
    { he: "הכתפיים למטה, רחוק מהאוזניים.", en: "Shoulders down, away from the ears." },
    { he: "ה-snap בסוף הזריקה היבשה – כמו לנער מים מהיד.", en: "The snap at the end of the dry throw – like flicking water off your hand." },
  ],
  commonMistakes: [
    { he: "מבצעים מהר ולא מגיעים לטווח מלא.", en: "Rushing and never reaching full range." },
    { he: "מזניחים את היד החלשה – גם היא תופסת ומאזנת.", en: "Neglecting the weak hand – it catches and balances too." },
  ],
  successMetric: { type: "rating", key: "confidence_rating", label: { he: "עד כמה הכתפיים והידיים מרגישות חופשיות (1–5)", en: "How free the shoulders and hands feel (1–5)" }, target: 4 },
  easierVersion: { he: "מעגלים קטנים יותר ו-6 חזרות; אם יש מגבלה בכתף – רק עד גבול הנוחות.", en: "Smaller circles and 6 reps; with a shoulder limitation stay inside the comfortable range." },
  harderVersion: { he: "הוסיפו 10 שכיבות סמיכה על קיר ו-15 שניות פלאנק על האמות בין הסבבים.", en: "Add 10 wall push-ups and a 15-second forearm plank between rounds." },
  soloAlternative: { he: "עובד לבד כפי שהוא – ספרו בקול כדי לא לקצר את הסבב.", en: "Works solo as written – count out loud so you don't cut the round short." },
  partnerAlternative: { he: "עמדו זה מול זה ובצעו יחד; אחרי הזריקות היבשות זרקו 5 זריקות רכות של 5 מטר בכל יד.", en: "Face each other and do it together; after the dry throws exchange 5 soft 5 m throws with each hand." },
  safetyNotes: [
    { he: "לא מותחים את שורש כף היד בכוח עם היד השנייה – הסיבובים אקטיביים בלבד.", en: "Don't force the wrist with the other hand – active circles only." },
    { he: "כאב בכתף בהרמה מעל הראש – מקטינים את המעגל או מדלגים על התנועה.", en: "Shoulder pain when raising overhead – shrink the circle or skip that movement." },
  ],
  diagram: {
    field: "square",
    items: [
      { type: "player", x: 50, y: 58 },
      { type: "disc", x: 58, y: 52 },
      { type: "shuffle", from: [30, 32], to: [70, 32], curve: true, label: "circles" },
      { type: "throw", from: [56, 56], to: [84, 46], dashed: true, label: "dry throw" },
    ],
  },
  throwsPerSet: 0,
  catchesPerSet: 0,
};

const wuHipSquatLunge: Exercise = {
  id: "wu-hip-squat-lunge",
  name: { he: "פתיחת ירכיים, סקוואט ולאנג׳", en: "Hip openers, squats & lunges" },
  category: "warmup",
  skills: ["warmup", "mobility", "strength"],
  roles: [],
  levels: ["beginner", "intermediate", "advanced"],
  phases: ["warmup"],
  goal: { he: "לפתוח את הירכיים ולהפעיל את הרגליים והישבן לפני Pivot, ריצה ושינויי כיוון.", en: "Open the hips and switch on the legs and glutes before pivots, running and changes of direction." },
  participants: ["solo", "pair", "group"],
  equipment: [],
  fieldSizes: ALL_FIELDS,
  intensity: "low",
  offenseDefense: "both",
  wind: "any",
  ageGroups: ALL_AGES,
  durationMinutes: 4,
  minDurationMinutes: 3,
  maxDurationMinutes: 5,
  sets: 2,
  reps: 8,
  restSeconds: 20,
  setup: {
    he: "משטח ישר ויציב עם 3 מטר פנויים לכל כיוון. בלי ציוד.",
    en: "A flat, stable surface with 3 m of space in every direction. No equipment.",
  },
  instructions: [
    { he: "פתיחת ירכיים בעמידה: הרימו ברך לגובה המותן, פתחו החוצה והורידו – 8 לכל רגל, ואז 8 מבחוץ פנימה.", en: "Standing hip openers: lift the knee to hip height, swing it out and down – 8 per leg, then 8 from outside in." },
    { he: "8 סקוואטים איטיים: 3 שניות ירידה, עצירה של שנייה למטה, עלייה מהירה.", en: "8 slow squats: 3 seconds down, a one-second pause at the bottom, quick up." },
    { he: "לאנג׳ קדימה: 8 לכל רגל, הברך האחורית יורדת עד 5 ס״מ מהקרקע.", en: "Forward lunge: 8 per leg, the back knee drops to 5 cm off the ground." },
    { he: "לאנג׳ לצד: 8 לכל רגל, כף הרגל שנשארת במקום מצביעה קדימה – זו בדיוק תנועת ה-Pivot.", en: "Side lunge: 8 per leg, the planted foot keeps pointing forward – exactly the pivot movement." },
    { he: "סבב שני של הכול, 20 שניות מנוחה בין הסבבים.", en: "Second round of everything, 20 seconds rest between rounds." },
  ],
  cues: [
    { he: "הברך בקו עם האצבע השנייה של כף הרגל.", en: "Knee tracks over the second toe." },
    { he: "החזה למעלה, המשקל על אמצע כף הרגל והעקב בסקוואט.", en: "Chest up, weight through the mid-foot and heel in the squat." },
    { he: "בלאנג׳ צדי – הישבן אחורה כמו להתיישב על כיסא.", en: "In the side lunge – hips back like sitting down on a chair." },
  ],
  commonMistakes: [
    { he: "הברך קורסת פנימה בלאנג׳ ובסקוואט.", en: "The knee collapses inward in the lunge and squat." },
    { he: "טווח קצר מדי – לא יורדים מספיק כדי שהירכיים באמת ייפתחו.", en: "Too shallow – not going deep enough for the hips to actually open." },
  ],
  successMetric: { type: "rating", key: "confidence_rating", label: { he: "עד כמה הרגליים מרגישות מוכנות לזוז מהר (1–5)", en: "How ready the legs feel to move fast (1–5)" }, target: 4 },
  easierVersion: { he: "סקוואט חלקי (עד 45°) ולאנג׳ בלי ירידה מלאה, 6 חזרות וסבב אחד.", en: "Partial squat (to 45°) and lunges without the full drop, 6 reps and one round." },
  harderVersion: { he: "הוסיפו קפיצה קטנה בסוף כל סקוואט (8 Squat Jumps) ולאנג׳ הליכה של 10 מטר.", en: "Add a small jump at the top of every squat (8 squat jumps) and a 10 m walking lunge." },
  soloAlternative: { he: "עובד לבד כפי שהוא – ספרו את החזרות בקול ושמרו על קצב אחיד.", en: "Works solo as written – count the reps out loud and keep an even tempo." },
  partnerAlternative: { he: "עמדו זה מול זה; אחד קורא ״למטה / למעלה״ ומכתיב קצב, ואחרי כל לאנג׳ צדי מבצעים Pivot יבש מול השותף.", en: "Face each other; one calls \"down / up\" to set the tempo, and after every side lunge you do a dry pivot facing your partner." },
  safetyNotes: [
    { he: "לאנג׳ רק על משטח ישר ויבש.", en: "Lunges only on a flat, dry surface." },
    { he: "כאב חד בברך – עוברים לסקוואט חלקי ומדלגים על הלאנג׳.", en: "Sharp knee pain – switch to partial squats and skip the lunges." },
  ],
  diagram: {
    field: "square",
    items: [
      { type: "player", x: 50, y: 60 },
      { type: "marker", x: 18, y: 60, label: "side" },
      { type: "marker", x: 82, y: 60, label: "side" },
      { type: "marker", x: 50, y: 22, label: "forward" },
      { type: "shuffle", from: [44, 60], to: [22, 60], dashed: true },
      { type: "shuffle", from: [56, 60], to: [78, 60], dashed: true },
      { type: "run", from: [50, 54], to: [50, 26], dashed: true, label: "lunge" },
    ],
  },
  throwsPerSet: 0,
  catchesPerSet: 0,
};

const wuHighKneesShuffle: Exercise = {
  id: "wu-high-knees-shuffle",
  name: { he: "High Knees ו-Side Shuffle", en: "High knees & side shuffles" },
  category: "warmup",
  skills: ["warmup", "footwork", "agility"],
  roles: [],
  levels: ["beginner", "intermediate", "advanced"],
  phases: ["warmup"],
  goal: { he: "להכין עבודת רגליים מהירה – מגע קרקע קצר, מותניים נמוכות ותנועה צידית לפני הגנה ו-Cuts.", en: "Prime fast footwork – short ground contact, low hips and lateral movement before defence and cutting." },
  participants: ["solo", "pair", "group"],
  equipment: [],
  optionalEquipment: ["cones"],
  fieldSizes: ALL_FIELDS,
  intensity: "medium",
  offenseDefense: "both",
  wind: "any",
  ageGroups: ALL_AGES,
  durationMinutes: 4,
  minDurationMinutes: 3,
  maxDurationMinutes: 5,
  sets: 2,
  reps: 4,
  restSeconds: 30,
  setup: {
    he: "סמנו קטע של 10 מטר עם שני קונוסים או שני דיסקים.",
    en: "Mark a 10 m stretch with two cones or two discs.",
  },
  instructions: [
    { he: "High Knees: 10 מטר עם ברכיים לגובה המותן וקצב רגליים מהיר, חזרה בהליכה.", en: "High knees: 10 m with knees to hip height and a fast foot rhythm, walk back." },
    { he: "Side Shuffle: 10 מטר לימין ו-10 מטר לשמאל, ברכיים כפופות, הרגליים לא נצמדות זו לזו.", en: "Side shuffle: 10 m to the right and 10 m to the left, knees bent, feet never touch." },
    { he: "Carioca: 10 מטר לכל צד – המותניים מסתובבות, הכתפיים נשארות קדימה.", en: "Carioca: 10 m each way – hips rotate, shoulders stay facing forward." },
    { he: "שילוב: 5 מטר High Knees ומיד 5 מטר Shuffle לצד, וחוזרים באותה צורה.", en: "Combo: 5 m of high knees straight into 5 m of side shuffle, and back the same way." },
    { he: "2 סבבים עם 30 שניות מנוחה ביניהם.", en: "2 rounds with 30 seconds rest between them." },
  ],
  cues: [
    { he: "מגע קצר עם הקרקע – ״הרצפה חמה״.", en: "Short ground contact – \"the floor is hot\"." },
    { he: "ב-Shuffle: מותניים נמוכות, גב ישר, לא מקפצים למעלה.", en: "In the shuffle: hips low, back straight, no bouncing upward." },
    { he: "הידיים עובדות בקצב הרגליים.", en: "Arms work at the same rhythm as the feet." },
  ],
  commonMistakes: [
    { he: "ב-Shuffle הרגליים נצמדות והגוף עולה למעלה – מאבדים את היכולת לשנות כיוון.", en: "In the shuffle the feet come together and the body rises – you lose the ability to change direction." },
    { he: "High Knees איטי עם הגוף נשען אחורה.", en: "Slow high knees with the body leaning back." },
  ],
  successMetric: { type: "rating", key: "confidence_rating", label: { he: "עד כמה הרגליים מרגישות קלות ומהירות (1–5)", en: "How light and quick the legs feel (1–5)" }, target: 4 },
  easierVersion: { he: "5 מטר בכל תנועה, קצב מתון, סבב אחד בלבד.", en: "5 m per movement, moderate pace, one round only." },
  harderVersion: { he: "סבב שלישי, ובסיום כל Shuffle יציאה לספרינט של 5 מטר.", en: "A third round, and every shuffle finishes with a 5 m sprint." },
  soloAlternative: { he: "עובד לבד כפי שהוא – השתמשו בקונוסים או בדיסקים כסימון ל-10 המטרים.", en: "Works solo as written – use cones or discs to mark the 10 m." },
  partnerAlternative: { he: "Shuffle זה מול זה: אחד מוביל ומחליף כיוון, השני ״מראה״ – 20 שניות ומתחלפים.", en: "Face-to-face shuffle: one leads and changes direction, the other mirrors – 20 seconds then swap." },
  safetyNotes: [
    { he: "Shuffle על משטח שלא מחליק; בדשא רטוב מורידים קצב.", en: "Shuffle on a non-slip surface; slow down on wet grass." },
    { he: "לא מצליבים רגליים ב-Shuffle כדי לא להיתקל בעצמכם.", en: "Never cross the feet in the shuffle so you don't trip over yourself." },
  ],
  diagram: {
    field: "lane",
    items: [
      { type: "player", x: 12, y: 62 },
      { type: "cone", x: 10, y: 50, label: "0" },
      { type: "cone", x: 90, y: 50, label: "10m" },
      { type: "run", from: [16, 62], to: [86, 62], label: "high knees" },
      { type: "shuffle", from: [86, 38], to: [16, 38], label: "shuffle" },
    ],
  },
  throwsPerSet: 0,
  catchesPerSet: 0,
};

const wuShortAccelerations: Exercise = {
  id: "wu-short-accelerations",
  name: { he: "האצות קצרות", en: "Short accelerations" },
  category: "warmup",
  skills: ["warmup", "acceleration", "speed"],
  roles: [],
  levels: ["beginner", "intermediate", "advanced"],
  phases: ["warmup"],
  goal: { he: "להכין את מערכת העצבים והשרירים לספרינט – האצות הדרגתיות שסוגרות את החימום לפני עבודה מהירה.", en: "Prime the nervous system and muscles for sprinting – progressive accelerations that close the warm-up before fast work." },
  participants: ["solo", "pair", "group"],
  equipment: [],
  optionalEquipment: ["cones"],
  fieldSizes: ALL_FIELDS,
  intensity: "medium",
  offenseDefense: "both",
  wind: "any",
  ageGroups: ALL_AGES,
  durationMinutes: 4,
  minDurationMinutes: 3,
  maxDurationMinutes: 5,
  sets: 1,
  reps: 6,
  restSeconds: 40,
  setup: {
    he: "סמנו 20 מטר עם שני קונוסים או שני דיסקים, והשאירו עוד 10 מטר פנויים אחרי הקונוס השני להאטה. מבצעים רק אחרי ריצה קלה ומוביליטי – לא כתרגיל ראשון.",
    en: "Mark 20 m with two cones or discs and leave another 10 m free past the second cone for slowing down. Do this only after a light jog and mobility – never as the first drill.",
  },
  instructions: [
    { he: "האצות 1–2: 20 מטר ב-60% מהמהירות, האטה הדרגתית לאורך 10 מטר אחרי הקונוס.", en: "Accelerations 1–2: 20 m at 60% speed, easing down over 10 m past the cone." },
    { he: "האצות 3–4: 20 מטר ב-75%, אותה האטה. חזרה בהליכה = המנוחה (כ-40 שניות).", en: "Accelerations 3–4: 20 m at 75%, same slow-down. Walking back is the rest (about 40 seconds)." },
    { he: "האצות 5–6: 20 מטר ב-90% מיציאה עם רגל אחת קדימה, כמו יציאה ל-Cut.", en: "Accelerations 5–6: 20 m at 90% from a staggered stance, like the start of a cut." },
    { he: "בין ההאצות נערו את הרגליים ותנו לנשימה להתייצב לפני היציאה הבאה.", en: "Between runs shake out the legs and let your breathing settle before the next start." },
  ],
  cues: [
    { he: "10 המטרים הראשונים – גוף נוטה קדימה, צעדים קצרים וחזקים.", en: "First 10 m – body leaning forward, short, powerful steps." },
    { he: "הידיים דוחפות אחורה, מרפקים ב-90°.", en: "Arms drive back, elbows at 90°." },
    { he: "מאיטים בהדרגה, אף פעם לא עצירה חדה.", en: "Slow down gradually, never a hard stop." },
  ],
  commonMistakes: [
    { he: "יוצאים ב-100% כבר בהאצה הראשונה.", en: "Going 100% on the very first run." },
    { he: "נעמדים זקוף מהצעד הראשון ומאבדים את הדחיפה.", en: "Standing upright from the first step and losing the drive." },
  ],
  successMetric: { type: "rating", key: "confidence_rating", label: { he: "עד כמה הגוף מרגיש מוכן לספרינט מלא (1–5)", en: "How ready the body feels for a full sprint (1–5)" }, target: 4 },
  easierVersion: { he: "4 האצות בלבד עד 75%, על 15 מטר.", en: "Only 4 accelerations up to 75%, over 15 m." },
  harderVersion: { he: "8 האצות, השתיים האחרונות ב-95% מיציאה מתוך Shuffle צדי.", en: "8 accelerations, the last two at 95% starting out of a side shuffle." },
  soloAlternative: { he: "עובד לבד כפי שהוא – ספרו לעצמכם ״שלוש, שתיים, אחת״ לפני כל יציאה כדי להתרגל לצאת על סימן.", en: "Works solo as written – count yourself down \"three, two, one\" before each start to get used to leaving on a signal." },
  partnerAlternative: { he: "יוצאים לסירוגין על קריאה של השותף (״צא!״); בסבב השני השני יוצא שנייה אחרי הראשון ומנסה לסגור פער – בלי מגע.", en: "Take turns starting on your partner's call (\"go!\"); in the second round the second runner leaves one second later and tries to close the gap – no contact." },
  safetyNotes: [
    { he: "לא כתרגיל ראשון – רק אחרי ריצה קלה ומוביליטי.", en: "Never the first drill – only after a light jog and mobility." },
    { he: "משיכה או ״תפיסה״ בירך האחורית – עוצרים מיד ולא ממשיכים לספרינטים.", en: "A pull or grab in the hamstring – stop immediately and skip the sprint work." },
  ],
  diagram: {
    field: "lane",
    items: [
      { type: "player", x: 8, y: 50 },
      { type: "cone", x: 10, y: 40, label: "0" },
      { type: "cone", x: 66, y: 40, label: "20m" },
      { type: "cone", x: 92, y: 40, label: "30m" },
      { type: "run", from: [12, 50], to: [64, 50], label: "accelerate" },
      { type: "run", from: [68, 50], to: [90, 50], dashed: true, label: "slow down" },
    ],
  },
  throwsPerSet: 0,
  catchesPerSet: 0,
};

const wuEasyThrows: Exercise = {
  id: "wu-easy-throws",
  name: { he: "זריקות קלות", en: "Easy throws" },
  category: "warmup",
  skills: ["warmup", "backhand", "forehand"],
  roles: [],
  levels: ["beginner", "intermediate", "advanced"],
  phases: ["warmup"],
  goal: { he: "להכניס את היד לזריקה בעדינות – Backhand ו-Forehand קצרים בכוח נמוך, בלי מרחק ובלי לחץ.", en: "Ease the arm into throwing – short backhands and forehands at low power, no distance and no pressure." },
  participants: ["solo", "pair", "group"],
  equipment: [],
  optionalEquipment: ["wall", "discs"],
  fieldSizes: ALL_FIELDS,
  intensity: "low",
  offenseDefense: "offense",
  wind: "any",
  ageGroups: ALL_AGES,
  durationMinutes: 4,
  minDurationMinutes: 3,
  maxDurationMinutes: 5,
  sets: 2,
  reps: 20,
  restSeconds: 0,
  setup: {
    he: "עמדו 8 מטר זה מול זה. לבד: 6 מטר מקיר, או קונוס במרחק 8 מטר וכמה דיסקים.",
    en: "Stand 8 m apart. Solo: 6 m from a wall, or a cone 8 m away and a few discs.",
  },
  instructions: [
    { he: "10 זריקות Backhand ב-50% כוח מ-8 מטר – רק להרגיש את האחיזה והשחרור.", en: "10 backhands at 50% power from 8 m – just feel the grip and the release." },
    { he: "10 זריקות Forehand מאותו מרחק, שטוחות ואיטיות.", en: "10 forehands from the same distance, flat and slow." },
    { he: "התרחקו ל-12 מטר וחזרו על 10 ו-10 ב-60% כוח.", en: "Move back to 12 m and repeat 10 and 10 at 60% power." },
    { he: "תופסים כל דיסק בשתי ידיים (Pancake) – גם התפיסה מתחממת.", en: "Catch every disc with two hands (pancake) – the catching warms up too." },
  ],
  cues: [
    { he: "דיסק שטוח, קשת נמוכה, אפס כוח מהכתף.", en: "Flat disc, low arc, zero power from the shoulder." },
    { he: "שחרור רך עם snap – הדיסק צריך להסתובב מהר גם בזריקה איטית.", en: "Soft release with a snap – the disc should spin fast even on a slow throw." },
    { he: "עומדים מוכנים לתפוס: ידיים לפני הגוף, משקל על כריות כפות הרגליים.", en: "Ready to catch: hands in front of the body, weight on the balls of the feet." },
  ],
  commonMistakes: [
    { he: "אחרי 3 זריקות כבר זורקים חזק ורחוק.", en: "Three throws in and it's already hard and long." },
    { he: "זורקים רק את היד הנוחה (Backhand) ומזניחים את ה-Forehand.", en: "Only throwing the comfortable side (backhand) and neglecting the forehand." },
  ],
  successMetric: { type: "count", key: "throw_count", label: { he: "מספר הזריקות שבוצעו (יעד 40)", en: "Throws completed (target 40)" }, target: 40 },
  easierVersion: { he: "6 מטר, 8 זריקות מכל סוג, ורק Backhand אם ה-Forehand עדיין לא יציב.", en: "6 m, 8 throws of each type, and backhand only if the forehand is still shaky." },
  harderVersion: { he: "סבב שלישי מ-15 מטר, וכל זריקה אחרי Pivot קטן.", en: "A third round from 15 m, with every throw after a small pivot." },
  soloAlternative: { he: "מול קיר מ-6 מטר: זרקו רך ותפסו את החזרה בשתי ידיים; או זרקו 3–5 דיסקים לעבר קונוס במרחק 8 מטר ואספו בהליכה.", en: "Against a wall from 6 m: throw softly and catch the rebound with two hands; or throw 3–5 discs at a cone 8 m away and collect at a walk." },
  partnerAlternative: { he: "כמו שכתוב – שני שחקנים 8 מטר זה מול זה, מחליפים סוג זריקה כל 10.", en: "As written – two players 8 m apart, switching throw type every 10." },
  safetyNotes: [
    { he: "לא זורקים חזק לפני שהכתף חמה – זה החימום, לא אימון הזריקה.", en: "No hard throws before the shoulder is warm – this is the warm-up, not the throwing session." },
    { he: "בקבוצה: כולם זורקים באותו כיוון, בלי הצלבות.", en: "In a group: everyone throws in the same direction, no crossing lanes." },
  ],
  diagram: {
    field: "lane",
    items: [
      { type: "player", x: 15, y: 50 },
      { type: "partner", x: 85, y: 50, label: "8m" },
      { type: "throw", from: [20, 44], to: [80, 44], label: "BH" },
      { type: "throw", from: [80, 56], to: [20, 56], dashed: true, label: "FH" },
    ],
  },
  throwsPerSet: 20,
  catchesPerSet: 20,
};

const wuLadderWarmup: Exercise = {
  id: "wu-ladder-warmup",
  name: { he: "חימום בסולם זריזות", en: "Agility-ladder warm-up" },
  category: "warmup",
  skills: ["warmup", "footwork", "agility"],
  roles: [],
  levels: ["beginner", "intermediate", "advanced"],
  phases: ["warmup"],
  goal: { he: "להעיר את כפות הרגליים והתיאום לפני עבודה מהירה – דפוסי סולם פשוטים בקצב עולה.", en: "Wake up the feet and coordination before fast work – simple ladder patterns at a rising tempo." },
  participants: ["solo", "pair", "group"],
  equipment: ["ladder"],
  optionalEquipment: ["cones"],
  fieldSizes: ALL_FIELDS,
  intensity: "medium",
  offenseDefense: "both",
  wind: "any",
  ageGroups: ALL_AGES,
  durationMinutes: 4,
  minDurationMinutes: 3,
  maxDurationMinutes: 5,
  sets: 2,
  reps: 4,
  restSeconds: 30,
  setup: {
    he: "פרשו סולם זריזות (4–5 מטר, 8–10 משבצות) על משטח ישר. אין סולם? סמנו 8 קווים בקונוסים או בגיר במרווח של 45 ס״מ.",
    en: "Lay out an agility ladder (4–5 m, 8–10 rungs) on a flat surface. No ladder? Mark 8 lines with cones or chalk 45 cm apart.",
  },
  instructions: [
    { he: "רגל אחת בכל משבצת, ריצה קדימה בקצב מתון. חזרה בהליכה.", en: "One foot per square, running forward at a moderate pace. Walk back." },
    { he: "שתי רגליים בכל משבצת (Two-In), הידיים עובדות.", en: "Two feet in every square (two-in), arms working." },
    { he: "Lateral: פנים לצד, שתי רגליים בכל משבצת – פעם לכל כיוון.", en: "Lateral: face sideways, two feet in every square – once each direction." },
    { he: "In-Out: שתי רגליים פנימה, שתי רגליים החוצה לצדדים, לאורך כל הסולם.", en: "In-out: two feet in, two feet out to the sides, the length of the ladder." },
    { he: "סבב שני של אותם 4 דפוסים במהירות גבוהה יותר – בלי לדרוך על השלבים.", en: "Second round of the same 4 patterns at a higher speed – without stepping on the rungs." },
  ],
  cues: [
    { he: "על כריות כפות הרגליים, העקבים לא נוגעים.", en: "On the balls of the feet, heels never touch." },
    { he: "מבט קדימה, לא על הסולם.", en: "Eyes forward, not on the ladder." },
    { he: "הידיים מכתיבות את קצב הרגליים.", en: "The arms set the rhythm for the feet." },
  ],
  commonMistakes: [
    { he: "דורכים על השלבים כי מנסים מהר מדי – קודם נקי, אחר כך מהיר.", en: "Stepping on the rungs from rushing – clean first, fast second." },
    { he: "הגוף זקוף ונוקשה, הברכיים לא כפופות.", en: "Body upright and stiff, knees not bent." },
  ],
  successMetric: { type: "rating", key: "confidence_rating", label: { he: "עד כמה הרגליים מרגישות מהירות ומדויקות (1–5)", en: "How fast and precise the feet feel (1–5)" }, target: 4 },
  easierVersion: { he: "סבב אחד בקצב הליכה מהירה, דפוסים 1–2 בלבד.", en: "One round at a brisk-walk pace, patterns 1–2 only." },
  harderVersion: { he: "הוסיפו Icky Shuffle ו-Hopscotch, וכל דפוס מסתיים ביציאה לספרינט של 5 מטר.", en: "Add the Icky Shuffle and hopscotch, and finish every pattern with a 5 m sprint." },
  soloAlternative: { he: "עובד לבד כפי שהוא – לבד אפשר גם לצלם 20 שניות כדי לבדוק אם דורכים על השלבים.", en: "Works solo as written – alone you can also film 20 seconds to check whether you're hitting the rungs." },
  partnerAlternative: { he: "בטור, יוצאים במרווח של 2 משבצות; המוביל בוחר את הדפוס והשני חייב לעקוב.", en: "In a line, starting 2 squares apart; the leader picks the pattern and the second must follow." },
  safetyNotes: [
    { he: "סולם על משטח ישר בלבד, וודאו שהוא לא זז – הצמידו את הקצוות.", en: "Ladder on a flat surface only, and make sure it doesn't slide – pin the ends." },
    { he: "נתקלתם בשלב? עוצרים ומתחילים מחדש – לא ״מתקנים״ באוויר.", en: "Caught a rung? Stop and restart – don't try to \"fix it\" mid-air." },
  ],
  diagram: {
    field: "lane",
    items: [
      { type: "player", x: 8, y: 50 },
      { type: "gate", x: 22, y: 50 },
      { type: "gate", x: 34, y: 50 },
      { type: "gate", x: 46, y: 50 },
      { type: "gate", x: 58, y: 50 },
      { type: "gate", x: 70, y: 50 },
      { type: "cone", x: 90, y: 50, label: "5m" },
      { type: "run", from: [12, 50], to: [86, 50], dashed: true },
    ],
  },
  throwsPerSet: 0,
  catchesPerSet: 0,
};

const wuThrowingLadder: Exercise = {
  id: "wu-throwing-ladder",
  name: { he: "סולם מרחקים לזריקה", en: "Throwing distance ladder" },
  category: "warmup",
  skills: ["warmup", "backhand", "forehand", "distance"],
  roles: [],
  levels: ["beginner", "intermediate", "advanced"],
  phases: ["warmup"],
  goal: { he: "לפתוח את הזריקה בהדרגה מ-8 עד 30 מטר – הכתף, המרפק והשחרור מתחממים לפני עבודת מרחק או דיוק.", en: "Open up the throw gradually from 8 to 30 m – shoulder, elbow and release warm up before distance or accuracy work." },
  participants: ["solo", "pair", "group"],
  equipment: [],
  optionalEquipment: ["cones", "discs"],
  fieldSizes: OPEN_FIELDS,
  intensity: "low",
  offenseDefense: "offense",
  wind: "any",
  ageGroups: ALL_AGES,
  durationMinutes: 5,
  minDurationMinutes: 3,
  maxDurationMinutes: 5,
  sets: 4,
  reps: 8,
  restSeconds: 0,
  setup: {
    he: "סמנו 4 נקודות על קו אחד: 8, 15, 22 ו-30 מטר מנקודת הזריקה (קונוסים, דיסקים או ספירת צעדים). השותף מתחיל ב-8 מטר.",
    en: "Mark 4 points on one line: 8, 15, 22 and 30 m from the throwing spot (cones, discs or paced out). Your partner starts at 8 m.",
  },
  instructions: [
    { he: "מ-8 מטר: 4 Backhand ו-4 Forehand ב-50% כוח, שטוחים.", en: "From 8 m: 4 backhands and 4 forehands at 50% power, flat." },
    { he: "השותף נסוג ל-15 מטר: 4 ו-4 ב-60%.", en: "Partner backs up to 15 m: 4 and 4 at 60%." },
    { he: "22 מטר: 4 ו-4 ב-70% – מכאן מוסיפים סיבוב גו.", en: "22 m: 4 and 4 at 70% – from here add trunk rotation." },
    { he: "30 מטר: 4 ו-4 ב-80% – עדיין לא כוח מלא; המטרה היא קשת נקייה שמגיעה לשותף.", en: "30 m: 4 and 4 at 80% – still not full power; the goal is a clean arc that reaches your partner." },
    { he: "זריקה שמתחילה לרעוד (wobble)? חוזרים מדרגה אחת אחורה לפני שממשיכים.", en: "A throw starting to wobble? Drop back one rung before moving on." },
  ],
  cues: [
    { he: "כל מדרגה מוסיפה 10% כוח, לא 30%.", en: "Each rung adds 10% power, not 30%." },
    { he: "המרחק מגיע מהסיבוב ומה-snap, לא מהיד.", en: "Distance comes from rotation and snap, not the arm." },
    { he: "עדיין שטוח – בלי לנסות ״להרים״ את הדיסק.", en: "Still flat – no trying to \"lift\" the disc." },
  ],
  commonMistakes: [
    { he: "קופצים ישר ל-30 מטר ומתאמצים מהזריקה הראשונה.", en: "Jumping straight to 30 m and straining from the first throw." },
    { he: "ב-22–30 מטר מפסיקים לזרוק Forehand כי ״לא הולך״.", en: "At 22–30 m giving up on the forehand because \"it isn't working\"." },
  ],
  successMetric: { type: "count", key: "throw_count", label: { he: "מספר הזריקות שבוצעו (יעד 32)", en: "Throws completed (target 32)" }, target: 32 },
  easierVersion: { he: "3 מדרגות: 8, 12 ו-18 מטר, 3 זריקות מכל סוג.", en: "3 rungs: 8, 12 and 18 m, 3 throws of each type." },
  harderVersion: { he: "מדרגה חמישית של 40 מטר ב-85%, וזריקה לקונוס במקום לשותף.", en: "A fifth rung at 40 m at 85%, throwing to a cone instead of a partner." },
  soloAlternative: { he: "זרקו 4 דיסקים לקונוס בכל מרחק ואספו בהליכה מהירה – ההליכה בין המדרגות היא המנוחה. אין 30 מטר? עצרו ב-22.", en: "Throw 4 discs at a cone at each distance and collect at a brisk walk – the walk between rungs is the rest. No 30 m available? Stop at 22." },
  partnerAlternative: { he: "כמו שכתוב – השותף נסוג מדרגה אחרי כל 8 זריקות ומחזיר באותו סוג זריקה.", en: "As written – your partner backs up one rung after every 8 throws and returns with the same throw type." },
  safetyNotes: [
    { he: "10 מטר פנויים מאחורי השותף לזריקות שעוברות.", en: "Keep 10 m clear behind your partner for throws that sail." },
    { he: "בחימום לא זורקים בכוח מלא – 80% מקסימום.", en: "No full-power throws in a warm-up – 80% at most." },
  ],
  diagram: {
    field: "lane",
    items: [
      { type: "player", x: 6, y: 50 },
      { type: "cone", x: 28, y: 50, label: "8m" },
      { type: "cone", x: 48, y: 50, label: "15m" },
      { type: "cone", x: 68, y: 50, label: "22m" },
      { type: "partner", x: 92, y: 50, label: "30m" },
      { type: "throw", from: [10, 44], to: [88, 44], dashed: true },
    ],
  },
  throwsPerSet: 8,
  catchesPerSet: 8,
};

/* ------------------------------------------------------------------ */
/* Backhand                                                             */
/* ------------------------------------------------------------------ */

const bhShortGate: Exercise = {
  id: "bh-short-gate",
  name: { he: "Backhand דרך שער", en: "Backhand accuracy gate" },
  category: "throwing",
  skills: ["backhand", "accuracy", "short_throws"],
  roles: ["handler", "hybrid", "allround"],
  levels: ["beginner", "intermediate", "advanced"],
  phases: ["throwing"],
  goal: { he: "דיוק ושחרור נקי ב-Backhand במרחק קצר – הזריקה הבסיסית של כל מסירה במשחק.", en: "Accuracy and a clean release on the short backhand – the base throw of every pass in a game." },
  participants: ["solo", "pair", "group"],
  equipment: ["cones"],
  optionalEquipment: ["discs"],
  fieldSizes: ALL_FIELDS,
  intensity: "low",
  offenseDefense: "offense",
  wind: "any",
  ageGroups: ALL_AGES,
  durationMinutes: 8,
  minDurationMinutes: 6,
  maxDurationMinutes: 12,
  sets: 3,
  reps: 10,
  restSeconds: 60,
  setup: {
    he: "שני קונוסים במרחק 2 מטר זה מזה. עמדת הזריקה 10 מטר מהשער. הניחו כמה דיסקים לצדכם כדי לא לרוץ אחרי כל זריקה.",
    en: "Two cones 2 m apart. Throwing spot 10 m from the gate. Keep a few discs beside you so you don't chase every throw.",
  },
  instructions: [
    { he: "3 סטים של 10 זריקות Backhand דרך השער ב-60–70% כוח.", en: "3 sets of 10 backhands through the gate at 60–70% power." },
    { he: "כל זריקה מתחילה מעמידה: צעד קטן עם הרגל הקדמית (ימין לימניים) לכיוון המטרה, ואז זריקה.", en: "Every throw starts from standing: a small step with the front foot (right foot for right-handers) toward the target, then throw." },
    { he: "ספרו כמה עברו בין הקונוסים בכל סט – דיסק שנוגע בקונוס לא נספר.", en: "Count how many pass between the cones each set – a disc that touches a cone doesn't count." },
    { he: "בסט השלישי הוסיפו Pivot קטן מעמדת Forehand ל-Backhand לפני כל זריקה.", en: "In the third set add a small pivot from the forehand stance to backhand before every throw." },
  ],
  cues: [
    { he: "האגודל על הדיסק, 4 אצבעות מתחת לשפה – אחיזה חזקה אבל שורש כף היד משוחרר.", en: "Thumb on top, four fingers under the rim – firm grip, loose wrist." },
    { he: "משיכה בקו ישר מהחזה למטרה, לא בקשת רחבה סביב הגוף.", en: "Pull in a straight line from the chest to the target, not a wide arc around the body." },
    { he: "סיום עם היד מצביעה לשער והמבט על הקונוסים.", en: "Finish with the hand pointing at the gate and eyes on the cones." },
  ],
  commonMistakes: [
    { he: "הכתף נפתחת מוקדם והדיסק בורח שמאלה (לימניים).", en: "The shoulder opens early and the disc drifts left (for right-handers)." },
    { he: "שחרור עם הקצה החיצוני למעלה (OI) – הזריקה צפה, עולה ומתעקלת.", en: "Releasing with the outside edge up (OI) – the throw floats, climbs and curls." },
  ],
  successMetric: { type: "ratio", key: "backhand_accuracy", label: { he: "זריקות שעברו בשער מתוך 30", en: "Throws through the gate out of 30" }, target: 70, attempts: 30 },
  easierVersion: { he: "הרחיבו את השער ל-3 מטר או התקרבו ל-7 מטר.", en: "Widen the gate to 3 m or move in to 7 m." },
  harderVersion: { he: "שער של 1.5 מטר במרחק 15 מטר, או זריקה אחרי 2 Fakes.", en: "A 1.5 m gate at 15 m, or throw after 2 fakes." },
  soloAlternative: { he: "עובד לבד כפי שהוא: 5 דיסקים, איסוף בהליכה בין הסטים – זו המנוחה.", en: "Works solo as written: 5 discs, collect at a walk between sets – that's the rest." },
  partnerAlternative: { he: "השותף עומד מאחורי השער, סופר בקול ומחזיר ב-Forehand קל – ככה גם היד השנייה שלו עובדת.", en: "Your partner stands behind the gate, calls the count and returns with an easy forehand – so their other hand works too." },
  safetyNotes: [
    { he: "20 מטר פנויים מאחורי השער.", en: "Keep 20 m clear behind the gate." },
  ],
  diagram: {
    field: "lane",
    items: [
      { type: "player", x: 15, y: 50, label: "10m" },
      { type: "disc", x: 11, y: 62 },
      { type: "cone", x: 75, y: 38 },
      { type: "cone", x: 75, y: 62 },
      { type: "throw", from: [20, 50], to: [78, 50], dashed: true },
    ],
  },
  throwsPerSet: 10,
  catchesPerSet: 0,
};

const bhDistanceLadder: Exercise = {
  id: "bh-distance-ladder",
  name: { he: "Backhand במרחקים עולים", en: "Backhand distance ladder" },
  category: "throwing",
  skills: ["backhand", "distance", "deep_throws"],
  roles: ["handler", "wing", "hybrid", "allround"],
  levels: ["beginner", "intermediate", "advanced"],
  phases: ["throwing"],
  goal: { he: "להאריך את ה-Backhand בהדרגה מ-15 עד 35 מטר בלי לאבד זווית שטוחה ושליטה.", en: "Extend the backhand gradually from 15 to 35 m without losing a flat angle and control." },
  participants: ["solo", "pair", "group"],
  equipment: ["cones"],
  optionalEquipment: ["discs"],
  fieldSizes: OPEN_FIELDS,
  intensity: "medium",
  offenseDefense: "offense",
  wind: "wind_ok",
  ageGroups: ALL_AGES,
  durationMinutes: 10,
  minDurationMinutes: 6,
  maxDurationMinutes: 12,
  sets: 5,
  reps: 5,
  restSeconds: 45,
  setup: {
    he: "קונוסים ב-15, 20, 25, 30 ו-35 מטר מנקודת הזריקה, על קו ישר. ליד הקונוס הרחוק ביותר הניחו 2 קונוסים נוספים במרחק 3 מטר מכל צד – זה טווח הפגיעה.",
    en: "Cones at 15, 20, 25, 30 and 35 m from the throwing spot on a straight line. By the farthest cone place 2 extra cones 3 m either side – that's the hit zone.",
  },
  instructions: [
    { he: "5 זריקות Backhand ל-15 מטר – דיסק שטוח, קשת נמוכה. נחיתה בטווח 3 מטר מהקונוס = פגיעה.", en: "5 backhands to 15 m – flat disc, low arc. Landing within 3 m of the cone = a hit." },
    { he: "עברו ל-20, 25, 30 ו-35 מטר, 5 זריקות בכל מרחק. הכוח מגיע מהרגליים ומסיבוב הגו, לא מהיד.", en: "Move to 20, 25, 30 and 35 m, 5 throws at each distance. Power comes from the legs and trunk rotation, not the arm." },
    { he: "פחות מ-2 פגיעות מתוך 5? חזרו על אותו מרחק במקום להתקדם.", en: "Fewer than 2 hits out of 5? Repeat that distance instead of moving on." },
    { he: "איסוף הדיסקים בהליכה = מנוחה של כ-45 שניות בין המרחקים.", en: "Collecting the discs at a walk = about 45 seconds of rest between distances." },
  ],
  cues: [
    { he: "צעד ארוך לכיוון המטרה – המשקל עובר מהרגל האחורית לקדמית.", en: "A long step toward the target – weight shifts from the back foot to the front." },
    { he: "הדיסק נשאר שטוח ומשתחרר בגובה החזה – בלי להרים.", en: "The disc stays flat and releases at chest height – no lifting." },
    { he: "ה-snap בסוף: הדיסק צריך להסתובב מהר, לא לעוף גבוה.", en: "The snap at the end: the disc should spin fast, not fly high." },
  ],
  commonMistakes: [
    { he: "מנסים ״לזרוק גבוה״ כדי להרחיק – הדיסק מתרומם, נעצר ונופל.", en: "Trying to \"throw high\" for distance – the disc climbs, stalls and drops." },
    { he: "היד עוטפת את הגוף בסיום ומאבדים את קו המטרה.", en: "The arm wraps around the body on the follow-through and the target line is lost." },
  ],
  successMetric: { type: "ratio", key: "backhand_accuracy", label: { he: "נחיתות בטווח 3 מטר מהקונוס מתוך 25", en: "Landings within 3 m of the cone out of 25" }, target: 60, attempts: 25 },
  easierVersion: { he: "10, 15 ו-20 מטר בלבד, טווח פגיעה של 5 מטר.", en: "Only 10, 15 and 20 m, with a 5 m hit zone." },
  harderVersion: { he: "25 עד 45 מטר, טווח פגיעה של 2 מטר, או המרחק הרחוק ביותר נגד רוח קלה.", en: "25 to 45 m, a 2 m hit zone, or the longest distance into a light headwind." },
  soloAlternative: { he: "עובד לבד כפי שהוא – 5 דיסקים לפחות, ומעגל הפגיעה מסומן בקונוסים כדי שתוכלו לשפוט מרחוק.", en: "Works solo as written – at least 5 discs, with the hit zone marked by cones so you can judge from afar." },
  partnerAlternative: { he: "השותף עומד ליד הקונוס, מסמן פגיעה או החטאה ביד ומחזיר; אחרי כל סט הוא נסוג 5 מטר.", en: "Your partner stands by the cone, signals hit or miss by hand and returns; after every set they back up 5 m." },
  safetyNotes: [
    { he: "בדקו שאין אנשים במרחק 50 מטר בקו הזריקה.", en: "Check that nobody is within 50 m along the throwing line." },
    { he: "הכתף מתחילה ״למשוך״? נשארים במרחק הנוכחי ולא ממשיכים לרחוק יותר.", en: "Shoulder starting to \"pull\"? Stay at the current distance and don't go further." },
  ],
  diagram: {
    field: "lane",
    items: [
      { type: "player", x: 5, y: 50 },
      { type: "cone", x: 25, y: 50, label: "15m" },
      { type: "cone", x: 40, y: 50, label: "20m" },
      { type: "cone", x: 55, y: 50, label: "25m" },
      { type: "cone", x: 70, y: 50, label: "30m" },
      { type: "cone", x: 88, y: 50, label: "35m" },
      { type: "throw", from: [9, 44], to: [85, 44], curve: true, dashed: true },
    ],
  },
  throwsPerSet: 5,
  catchesPerSet: 0,
};

const bhLowRelease: Exercise = {
  id: "bh-low-release",
  name: { he: "Backhand בשחרור נמוך", en: "Low-release backhand" },
  category: "throwing",
  skills: ["backhand", "break_throws", "release_speed"],
  roles: ["handler", "hybrid"],
  levels: ["intermediate", "advanced"],
  phases: ["throwing"],
  goal: { he: "Backhand נמוך – שחרור מתחת לגובה הברך של המגן, לזריקות Break מהירות סביב ה-Mark.", en: "The low backhand – releasing below the marker's knee for quick break throws around the mark." },
  participants: ["solo", "pair", "group"],
  equipment: ["cones"],
  optionalEquipment: ["discs"],
  fieldSizes: ALL_FIELDS,
  intensity: "low",
  offenseDefense: "offense",
  wind: "any",
  ageGroups: ALL_AGES,
  durationMinutes: 8,
  minDurationMinutes: 6,
  maxDurationMinutes: 12,
  sets: 3,
  reps: 10,
  restSeconds: 60,
  setup: {
    he: "שער של 2 קונוסים ברוחב 2 מטר במרחק 8 מטר. מטר וחצי לפני עמדת הזריקה, על הקו לשער, הניחו קונוס גבוה (או תיק) שמדמה את רגל המגן. אם יש מקל או חבל – הניחו אותו על שני קונוסים בגובה 50 ס״מ, והדיסק צריך לעבור מתחתיו.",
    en: "A 2 m gate of two cones 8 m away. 1.5 m in front of the throwing spot, on the line to the gate, put a tall cone (or a bag) standing in for the marker's leg. If you have a stick or rope, rest it on two cones at 50 cm – the disc must pass underneath.",
  },
  instructions: [
    { he: "עמדו ב-Pivot נמוך: רגל הציר (שמאל לימניים) נטועה, צעד רחב לצד ה-Backhand, הברך הקדמית כפופה ב-90°.", en: "Get into a low pivot: pivot foot (left for right-handers) planted, a wide step to the backhand side, front knee bent to 90°." },
    { he: "10 זריקות Backhand מהעמדה הנמוכה – הדיסק משתחרר מתחת לגובה הברך ועובר בשער.", en: "10 backhands from the low stance – the disc releases below knee height and passes through the gate." },
    { he: "זריקה נספרת רק אם עברה נמוך (מתחת ל-50 ס״מ ליד הקונוס הקדמי) וגם דרך השער.", en: "A throw counts only if it went low (under 50 cm at the front cone) and through the gate." },
    { he: "סט 2: Fake Forehand גבוה לפני כל זריקה. סט 3: שחרור מהיר – פחות משנייה מה-Fake לזריקה.", en: "Set 2: a high forehand fake before every throw. Set 3: quick release – under one second from fake to throw." },
  ],
  cues: [
    { he: "יורדים עם הרגליים, לא מתכופפים בגב.", en: "Get low with the legs, don't bend the back." },
    { he: "היד מגיעה קרוב לקרקע – ״לגלגל״ את הדיסק מתחת ליד של המגן.", en: "The hand gets close to the ground – \"roll\" the disc under the marker's hand." },
    { he: "שחרור עם זווית IO קלה כדי שהדיסק לא יתרומם.", en: "Release with a slight inside-out angle so the disc doesn't climb." },
  ],
  commonMistakes: [
    { he: "מתכופפים מהגב במקום לכופף ברכיים – הזריקה יוצאת גבוהה ולא יציבה.", en: "Bending from the back instead of the knees – the throw comes out high and unstable." },
    { he: "מאבדים את ה-snap בעמדה הנמוכה והדיסק רועד.", en: "Losing the snap in the low stance and the disc wobbles." },
  ],
  successMetric: { type: "ratio", key: "backhand_accuracy", label: { he: "זריקות נמוכות שעברו בשער מתוך 30", en: "Low throws through the gate out of 30" }, target: 60, attempts: 30 },
  easierVersion: { he: "שער 3 מטר במרחק 6 מטר, ושחרור בגובה הירך במקום מתחת לברך.", en: "A 3 m gate at 6 m, releasing at hip height instead of below the knee." },
  harderVersion: { he: "שער 1.5 מטר במרחק 12 מטר, ושותף שעומד כ-Mark עם יד נמוכה (בלי מגע).", en: "A 1.5 m gate at 12 m, with a partner marking with a low hand (no contact)." },
  soloAlternative: { he: "עובד לבד כפי שהוא – קונוס גבוה במקום מגן, 5 דיסקים, ובודקים בעצמכם אם הדיסק עבר מתחת לקו ה-50 ס״מ.", en: "Works solo as written – a tall cone stands in for the marker, 5 discs, and you judge yourself whether the disc passed under the 50 cm line." },
  partnerAlternative: { he: "השותף עומד כ-Mark במרחק זרוע ומוריד יד לכיוון הזריקה (בלי לגעת) – זורקים מתחת ליד שלו.", en: "Your partner marks at arm's length and drops a hand toward the throw (no touching) – throw under the hand." },
  safetyNotes: [
    { he: "ה-Mark לא נוגע בזורק ולא חוסם את הרגליים.", en: "The marker never touches the thrower or blocks the feet." },
    { he: "עמדה נמוכה מעמיסה על הברך – כאב בברך הקדמית? מעלים את השחרור לגובה הירך.", en: "The low stance loads the knee – front-knee pain? Raise the release to hip height." },
  ],
  diagram: {
    field: "lane",
    items: [
      { type: "player", x: 15, y: 50, label: "8m" },
      { type: "defender", x: 25, y: 44, label: "mark" },
      { type: "cone", x: 78, y: 38 },
      { type: "cone", x: 78, y: 62 },
      { type: "throw", from: [18, 60], to: [80, 52], dashed: true, label: "low" },
    ],
  },
  throwsPerSet: 10,
  catchesPerSet: 0,
};

const bhPivotThrow: Exercise = {
  id: "bh-pivot-throw",
  name: { he: "Pivot ואז Backhand", en: "Pivot-to-backhand" },
  category: "throwing",
  skills: ["backhand", "pivot", "footwork"],
  roles: ["handler", "hybrid", "allround"],
  levels: ["beginner", "intermediate", "advanced"],
  phases: ["throwing"],
  goal: { he: "לחבר Pivot ל-Backhand – שינוי כיוון מהיר של הגוף ואז זריקה מדויקת, בלי לאבד את רגל הציר.", en: "Link the pivot to the backhand – a fast body turn followed by an accurate throw, without losing the pivot foot." },
  participants: ["solo", "pair", "group"],
  equipment: [],
  optionalEquipment: ["cones", "discs"],
  fieldSizes: ALL_FIELDS,
  intensity: "low",
  offenseDefense: "offense",
  wind: "any",
  ageGroups: ALL_AGES,
  durationMinutes: 8,
  minDurationMinutes: 6,
  maxDurationMinutes: 12,
  sets: 3,
  reps: 8,
  restSeconds: 45,
  setup: {
    he: "מטרה במרחק 10 מטר – שותף, קונוס או דיסק על הקרקע. סמנו את מקום רגל הציר בקונוס או בדיסק כדי לראות אם היא זזה.",
    en: "A target 10 m away – a partner, a cone or a disc on the ground. Mark the pivot-foot spot with a cone or disc so you can see if it moves.",
  },
  instructions: [
    { he: "רגל הציר (שמאל לימניים) נטועה. מתחילים בעמדת Forehand – משקל על הרגל הימנית, פתוחים לצד ימין.", en: "Pivot foot (left for right-handers) planted. Start in the forehand stance – weight on the right foot, open to the right side." },
    { he: "Pivot: דוחפים מהרגל הימנית, מעבירים אותה מעבר לגוף לעמדת Backhand וזורקים מיד למטרה.", en: "Pivot: push off the right foot, swing it across the body into the backhand stance and throw to the target immediately." },
    { he: "8 חזרות בסט; הזריקה נספרת אם נחתה בתוך 2 מטר מהמטרה ורגל הציר לא זזה.", en: "8 reps per set; a throw counts if it lands within 2 m of the target and the pivot foot didn't move." },
    { he: "סט 2: Fake Forehand אמיתי לפני ה-Pivot. סט 3: 2 Pivots ברצף (Forehand–Backhand–Forehand–Backhand) ואז זריקה.", en: "Set 2: a convincing forehand fake before the pivot. Set 3: 2 pivots in a row (forehand–backhand–forehand–backhand) then throw." },
  ],
  cues: [
    { he: "רגל הציר דבוקה – רק כף הרגל מסתובבת על המקום.", en: "Pivot foot glued down – only the foot rotates in place." },
    { he: "צעד גדול ונמוך, המותניים לפני הכתפיים.", en: "A big, low step, hips before shoulders." },
    { he: "הדיסק יוצא תוך חצי שנייה מסיום ה-Pivot.", en: "The disc leaves within half a second of finishing the pivot." },
  ],
  commonMistakes: [
    { he: "רגל הציר ״מטיילת״ – במשחק זה Travel.", en: "The pivot foot \"wanders\" – in a game that's a travel." },
    { he: "עומדים זקוף ב-Pivot ומגיעים לזריקה בלי איזון.", en: "Standing tall through the pivot and arriving at the throw off balance." },
  ],
  successMetric: { type: "ratio", key: "backhand_accuracy", label: { he: "זריקות בטווח 2 מטר מהמטרה אחרי Pivot מתוך 24", en: "Throws within 2 m of the target after a pivot out of 24" }, target: 65, attempts: 24 },
  easierVersion: { he: "Pivot איטי בשני חלקים – עצירה בעמדת Backhand ואז זריקה – ל-7 מטר, מטרה של 3 מטר.", en: "A slow two-part pivot – pause in the backhand stance, then throw – to 7 m, with a 3 m target." },
  harderVersion: { he: "15 מטר, מטרה של 1.5 מטר, ו-Pivot מיד אחרי תפיסה משותף (Catch–Pivot–Throw).", en: "15 m, a 1.5 m target, and the pivot straight after a catch from a partner (catch–pivot–throw)." },
  soloAlternative: { he: "עובד לבד כפי שהוא – קונוס או דיסק כמטרה, 4 דיסקים, ובודקים אחרי כל זריקה שכף הרגל עדיין על הסימון.", en: "Works solo as written – a cone or disc as the target, 4 discs, and after every throw check that the foot is still on its mark." },
  partnerAlternative: { he: "השותף עומד כ-Mark ללא מגע בצד ה-Forehand ומכריח Pivot, ואז תופס את ה-Backhand ומחזיר.", en: "Your partner marks without contact on the forehand side to force the pivot, then catches the backhand and returns it." },
  safetyNotes: [
    { he: "Pivot על משטח יציב – בדשא רטוב מקצרים את הצעד.", en: "Pivot on a stable surface – shorten the step on wet grass." },
    { he: "ה-Mark שומר מרחק זרוע – בלי מגע ברגליים.", en: "The marker keeps arm's length – no contact with the legs." },
  ],
  diagram: {
    field: "lane",
    items: [
      { type: "player", x: 18, y: 50 },
      { type: "marker", x: 18, y: 58, label: "pivot foot" },
      { type: "defender", x: 27, y: 38, label: "mark" },
      { type: "shuffle", from: [14, 40], to: [14, 62], curve: true, label: "pivot" },
      { type: "target", x: 86, y: 50, label: "10m" },
      { type: "throw", from: [22, 56], to: [82, 52], dashed: true },
    ],
  },
  throwsPerSet: 8,
  catchesPerSet: 0,
};

/* ------------------------------------------------------------------ */
/* Forehand                                                             */
/* ------------------------------------------------------------------ */

const fhWristSnap: Exercise = {
  id: "fh-wrist-snap",
  name: { he: "Forehand – עבודת שורש כף היד", en: "Forehand wrist-snap drill" },
  category: "throwing",
  skills: ["forehand", "release_speed", "short_throws"],
  roles: ["handler", "hybrid", "allround"],
  levels: ["beginner", "intermediate", "advanced"],
  phases: ["throwing"],
  goal: { he: "לבודד את ה-snap של שורש כף היד ב-Forehand – שחרור מהיר ודיסק יציב בלי רעידה, במרחק קצר.", en: "Isolate the wrist snap of the forehand – a quick release and a stable, wobble-free disc at short range." },
  participants: ["solo", "pair", "group"],
  equipment: [],
  optionalEquipment: ["wall", "cones", "discs"],
  fieldSizes: ALL_FIELDS,
  intensity: "low",
  offenseDefense: "offense",
  wind: "any",
  ageGroups: ALL_AGES,
  durationMinutes: 8,
  minDurationMinutes: 6,
  maxDurationMinutes: 12,
  sets: 3,
  reps: 12,
  restSeconds: 45,
  setup: {
    he: "שותף במרחק 5 מטר, או קיר במרחק 3 מטר. לא צריך ציוד נוסף.",
    en: "A partner 5 m away, or a wall 3 m away. No extra equipment needed.",
  },
  instructions: [
    { he: "סט 1 – רק שורש כף היד: בכריעה על ברך אחת, המרפק נשען על הירך הקדמית; 12 זריקות Forehand ל-5 מטר עם snap בלבד.", en: "Set 1 – wrist only: kneel on one knee with the elbow resting on the front thigh; 12 forehands to 5 m using only the snap." },
    { he: "סט 2 – בעמידה, מרפק צמוד לגוף והזרוע לא זזה: 12 זריקות שטוחות ל-5 מטר.", en: "Set 2 – standing, elbow pinned to the body and the arm still: 12 flat throws to 5 m." },
    { he: "סט 3 – תנועה מלאה קצרה: צעד קטן, מרפק מוביל, snap – 12 זריקות ל-8 מטר.", en: "Set 3 – short full motion: small step, elbow leads, snap – 12 throws to 8 m." },
    { he: "זריקה טובה = מגיעה שטוחה ויציבה לידיים של השותף (או חוזרת מהקיר בלי לרעוד) בלי שהוא צריך לזוז.", en: "A good throw = arrives flat and stable in your partner's hands (or comes back off the wall without wobble) without them moving." },
  ],
  cues: [
    { he: "האצבע האמצעית לוחצת על השפה הפנימית – היא זו שנותנת את הסיבוב.", en: "The middle finger presses on the inside rim – it's what gives the spin." },
    { he: "כף היד פתוחה כלפי מעלה בשחרור, כמו להגיש מגש.", en: "Palm open and facing up at release, like carrying a tray." },
    { he: "היד ממשיכה לכיוון המטרה אחרי השחרור, לא נסגרת לגוף.", en: "The hand continues toward the target after release, it doesn't close back to the body." },
  ],
  commonMistakes: [
    { he: "המרפק מתרחק מהגוף והזריקה הופכת ל״הטלה״ מהכתף.", en: "The elbow drifts away from the body and the throw turns into a shoulder \"push\"." },
    { he: "אחיזה חזקה מדי – הדיסק לא מסתובב ורועד באוויר.", en: "Gripping too hard – the disc doesn't spin and wobbles in the air." },
  ],
  successMetric: { type: "ratio", key: "forehand_accuracy", label: { he: "זריקות שטוחות ויציבות שהגיעו לשותף מתוך 36", en: "Flat, stable throws that reached the partner out of 36" }, target: 70, attempts: 36 },
  easierVersion: { he: "3 מטר, 8 חזרות, סטים 1–2 בלבד.", en: "3 m, 8 reps, sets 1–2 only." },
  harderVersion: { he: "12 מטר בסט 3, וסט נוסף של 12 זריקות מהירות – מהתפיסה לשחרור בפחות משנייה.", en: "12 m in set 3, plus an extra set of 12 quick throws – catch to release in under one second." },
  soloAlternative: { he: "מול קיר מ-3 מטר: snap בלבד ותפיסת החזרה בשתי ידיים; בלי קיר – 5 דיסקים לעבר קונוס במרחק 5 מטר.", en: "Against a wall from 3 m: snap only and catch the rebound with two hands; without a wall – 5 discs at a cone 5 m away." },
  partnerAlternative: { he: "כמו שכתוב – 5 מטר זה מול זה, השותף מחזיר את הדיסק באותו סט (גם הוא עובד על ה-snap).", en: "As written – 5 m apart, your partner returns the disc in the same set (they're working on the snap too)." },
  safetyNotes: [
    { he: "כריעה על אספלט? שימו בגד או כרית מתחת לברך.", en: "Kneeling on asphalt? Put a garment or a pad under the knee." },
    { he: "כאב בצד הפנימי של המרפק = עצירה; ממשיכים ב-snap יבש בלי דיסק עד שהכאב עובר.", en: "Pain on the inside of the elbow = stop; continue with dry snaps and no disc until it passes." },
  ],
  diagram: {
    field: "lane",
    items: [
      { type: "player", x: 20, y: 55, label: "5m" },
      { type: "marker", x: 20, y: 68, label: "knee" },
      { type: "partner", x: 70, y: 55 },
      { type: "throw", from: [25, 50], to: [66, 50], dashed: true, label: "snap" },
      { type: "disc", x: 75, y: 62 },
    ],
  },
  throwsPerSet: 12,
  catchesPerSet: 12,
};

const fhDistanceLadder: Exercise = {
  id: "fh-distance-ladder",
  name: { he: "Forehand במרחקים עולים", en: "Forehand distance ladder" },
  category: "throwing",
  skills: ["forehand", "distance", "deep_throws"],
  roles: ["handler", "wing", "hybrid", "allround"],
  levels: ["intermediate", "advanced"],
  phases: ["throwing"],
  goal: { he: "להאריך את ה-Forehand בהדרגה מ-15 עד 35 מטר בלי לאבד את השטיחות ואת ה-snap.", en: "Extend the forehand gradually from 15 to 35 m without losing flatness and snap." },
  participants: ["solo", "pair", "group"],
  equipment: ["cones"],
  optionalEquipment: ["discs"],
  fieldSizes: OPEN_FIELDS,
  intensity: "medium",
  offenseDefense: "offense",
  wind: "wind_ok",
  ageGroups: ALL_AGES,
  durationMinutes: 10,
  minDurationMinutes: 6,
  maxDurationMinutes: 12,
  sets: 5,
  reps: 5,
  restSeconds: 45,
  setup: {
    he: "קונוסים ב-15, 20, 25, 30 ו-35 מטר על קו ישר. סביב הקונוס הפעיל – טווח פגיעה של 3 מטר לכל צד (סמנו ב-2 קונוסים נוספים).",
    en: "Cones at 15, 20, 25, 30 and 35 m on a straight line. Around the active cone – a hit zone of 3 m either side (mark it with 2 extra cones).",
  },
  instructions: [
    { he: "5 זריקות Forehand ל-15 מטר, זווית שטוחה, 60% כוח.", en: "5 forehands to 15 m, flat angle, 60% power." },
    { he: "20, 25, 30 ו-35 מטר – 5 בכל מרחק. הכוח מגיע מהצעד ומסיבוב המותניים; הזרוע נשארת קצרה.", en: "20, 25, 30 and 35 m – 5 at each distance. Power comes from the step and hip rotation; the arm stays short." },
    { he: "פגיעה = נחיתה בטווח 3 מטר מהקונוס. פחות מ-2 פגיעות מתוך 5 – חוזרים על המרחק.", en: "A hit = landing within 3 m of the cone. Fewer than 2 hits out of 5 – repeat the distance." },
    { he: "ב-30 ו-35 מטר אפשר לשחרר עם זווית IO קלה שנפתחת לשטוח באוויר. ההליכה לאיסוף היא המנוחה.", en: "At 30 and 35 m you may release with a slight inside-out angle that flattens out in the air. The walk to collect is the rest." },
  ],
  cues: [
    { he: "צעד רחב לצד ה-Forehand, הכתפיים נסגרות ואז נפתחות למטרה.", en: "A wide step to the forehand side, shoulders close then open to the target." },
    { he: "המרפק מוביל וה-snap סוגר – לא זורקים ״עם כל היד״.", en: "Elbow leads, snap finishes – don't throw \"with the whole arm\"." },
    { he: "שחרור בגובה המותן, לא מעל הכתף.", en: "Release at hip height, not above the shoulder." },
  ],
  commonMistakes: [
    { he: "המרפק עולה ומתרחק, הדיסק יוצא בזווית OI ונופל.", en: "The elbow rises and drifts out, the disc leaves outside-in and dies." },
    { he: "מפצים על מרחק ב״הרמה״ של הדיסק במקום בסיבוב.", en: "Compensating for distance by \"lifting\" the disc instead of rotating." },
  ],
  successMetric: { type: "ratio", key: "forehand_accuracy", label: { he: "נחיתות בטווח 3 מטר מהקונוס מתוך 25", en: "Landings within 3 m of the cone out of 25" }, target: 55, attempts: 25 },
  easierVersion: { he: "10, 15 ו-20 מטר בלבד, טווח פגיעה של 5 מטר.", en: "Only 10, 15 and 20 m, with a 5 m hit zone." },
  harderVersion: { he: "25 עד 45 מטר, טווח פגיעה של 2 מטר, או כל זריקה אחרי Pivot מעמדת Backhand.", en: "25 to 45 m, a 2 m hit zone, or every throw after a pivot from the backhand stance." },
  soloAlternative: { he: "עובד לבד כפי שהוא – 5 דיסקים לפחות, איסוף בהליכה מהירה בין המרחקים.", en: "Works solo as written – at least 5 discs, collect at a brisk walk between distances." },
  partnerAlternative: { he: "השותף ליד הקונוס מסמן פגיעה ומחזיר ב-Backhand; אחרי כל סט הוא נסוג 5 מטר.", en: "Your partner by the cone signals a hit and returns with a backhand; after every set they back up 5 m." },
  safetyNotes: [
    { he: "50 מטר פנויים בקו הזריקה.", en: "Keep 50 m clear along the throwing line." },
    { he: "Forehand ארוך מעמיס על המרפק – כאב בצד הפנימי של המרפק? עוצרים את הסולם.", en: "Long forehands load the elbow – pain on the inside of the elbow? Stop the ladder." },
  ],
  diagram: {
    field: "lane",
    items: [
      { type: "player", x: 5, y: 50 },
      { type: "cone", x: 25, y: 50, label: "15m" },
      { type: "cone", x: 40, y: 50, label: "20m" },
      { type: "cone", x: 55, y: 50, label: "25m" },
      { type: "cone", x: 70, y: 50, label: "30m" },
      { type: "cone", x: 88, y: 50, label: "35m" },
      { type: "throw", from: [9, 56], to: [85, 56], curve: true, dashed: true },
    ],
  },
  throwsPerSet: 5,
  catchesPerSet: 0,
};

const fhReleaseAngles: Exercise = {
  id: "fh-release-angles",
  name: { he: "Forehand בזוויות שחרור שונות", en: "Forehand release angles" },
  category: "throwing",
  skills: ["forehand", "break_throws", "wind"],
  roles: ["handler", "hybrid"],
  levels: ["intermediate", "advanced"],
  phases: ["throwing"],
  goal: { he: "לשלוט בזווית השחרור ב-Forehand – IO, שטוח ו-OI – כדי לזרוק סביב Mark ולתקן לרוח.", en: "Control the forehand release angle – inside-out, flat and outside-in – to throw around a mark and correct for wind." },
  participants: ["solo", "pair", "group"],
  equipment: ["cones"],
  optionalEquipment: ["discs"],
  fieldSizes: ALL_FIELDS,
  intensity: "low",
  offenseDefense: "offense",
  wind: "wind_focus",
  ageGroups: ALL_AGES,
  durationMinutes: 9,
  minDurationMinutes: 6,
  maxDurationMinutes: 12,
  sets: 3,
  reps: 8,
  restSeconds: 60,
  setup: {
    he: "מטרה (קונוס או שותף) במרחק 12 מטר. 4 מטר לפני הזורק, על הקו הישר למטרה, קונוס גבוה – ה״מגן״. 3 מטר משמאלו ו-3 מטר מימינו עוד קונוס – הם מסמנים מאיזה צד הדיסק צריך לעבור.",
    en: "A target (cone or partner) 12 m away. 4 m in front of the thrower, on the straight line to the target, a tall cone – the \"marker\". Another cone 3 m to its left and 3 m to its right – they mark which side the disc has to pass." },
  instructions: [
    { he: "סט 1 – IO: 8 זריקות Forehand שיוצאות עם הקצה החיצוני למטה, עוקפות את קונוס המגן מימין (לימניים) ונוחתות עד 2 מטר מהמטרה.", en: "Set 1 – inside-out: 8 forehands leaving with the outside edge down, passing the marker cone on the right (right-handers) and landing within 2 m of the target." },
    { he: "סט 2 – שטוח: 8 זריקות ישרות שעוברות ליד קונוס המגן ונוחתות במטרה בלי סטייה.", en: "Set 2 – flat: 8 straight throws passing beside the marker cone and landing on the target with no drift." },
    { he: "סט 3 – OI: 8 זריקות שיוצאות עם הקצה החיצוני למעלה, מתחילות משמאל לקונוס המגן ומתעקלות פנימה למטרה.", en: "Set 3 – outside-in: 8 throws leaving with the outside edge up, starting left of the marker cone and curling in to the target." },
    { he: "יש רוח? זרקו את ה-IO נגד הרוח ואת ה-OI עם הרוח, ורשמו איזו זווית הכי יציבה היום.", en: "Windy? Throw the inside-out into the wind and the outside-in with it, and note which angle is most stable today." },
  ],
  cues: [
    { he: "הזווית נקבעת בשורש כף היד בשחרור – לא בהטיית כל הגוף.", en: "The angle is set by the wrist at release – not by tilting the whole body." },
    { he: "IO: הקצה הרחוק מהגוף נמוך, הדיסק ״נפתח״ באוויר.", en: "Inside-out: the edge far from the body is low, the disc \"opens up\" in the air." },
    { he: "OI: שחרור מעט גבוה יותר עם הקצה למעלה, הדיסק מתעקל וצונח למטרה.", en: "Outside-in: a slightly higher release with the edge up, the disc curls and drops onto the target." },
  ],
  commonMistakes: [
    { he: "משנים את הזווית עם הכתף וכל התנועה משתנה.", en: "Changing the angle with the shoulder so the whole motion changes." },
    { he: "IO חזק מדי – הדיסק מתגלגל על הקצה ולא מתיישר.", en: "Too much inside-out – the disc rolls on its edge and never flattens." },
  ],
  successMetric: { type: "ratio", key: "forehand_accuracy", label: { he: "זריקות שעקפו את המגן בזווית הנכונה ונחתו במטרה מתוך 24", en: "Throws that passed the marker at the right angle and landed on the target out of 24" }, target: 60, attempts: 24 },
  easierVersion: { he: "8 מטר, מטרה של 3 מטר, וסטים 1–2 בלבד (IO ושטוח).", en: "8 m, a 3 m target, and sets 1–2 only (inside-out and flat)." },
  harderVersion: { he: "15 מטר, מטרה של 1.5 מטר, ושותף Mark אמיתי (בלי מגע) שזז לחסום את הזווית האחרונה שזרקתם.", en: "15 m, a 1.5 m target, and a real marker (no contact) who shifts to block the last angle you threw." },
  soloAlternative: { he: "עובד לבד כפי שהוא – הקונוסים מסמנים את הצד, 5 דיסקים, ובודקים בעצמכם את הנחיתה ביחס למטרה.", en: "Works solo as written – the cones mark the side, 5 discs, and you check the landing against the target yourself." },
  partnerAlternative: { he: "השותף עומד כ-Mark במקום הקונוס הגבוה ומכריז לפני כל זריקה ״IO״, ״OI״ או ״שטוח״ – בלי מגע.", en: "Your partner marks in place of the tall cone and calls \"IO\", \"OI\" or \"flat\" before every throw – no contact." },
  safetyNotes: [
    { he: "ה-Mark לא מרים ידיים לפנים של הזורק – בלי מגע.", en: "The marker never puts hands in the thrower's face – no contact." },
    { he: "ברוח חזקה לא מאלצים OI חד – הדיסק עלול לעוף מחוץ לשטח.", en: "In strong wind don't force a sharp outside-in – the disc may sail out of the area." },
  ],
  diagram: {
    field: "lane",
    items: [
      { type: "player", x: 12, y: 50 },
      { type: "defender", x: 32, y: 50, label: "mark" },
      { type: "cone", x: 32, y: 28 },
      { type: "cone", x: 32, y: 72 },
      { type: "target", x: 88, y: 50, label: "12m" },
      { type: "throw", from: [16, 56], to: [86, 52], curve: true, dashed: true, label: "IO" },
      { type: "throw", from: [16, 44], to: [86, 48], curve: true, dashed: true, label: "OI" },
    ],
  },
  throwsPerSet: 8,
  catchesPerSet: 0,
};
