/**
 * Exercise manifest – the canonical list of exercise ids in the catalog.
 * Content authors expand each entry into a full `Exercise` (see src/content/exercises/*.ts).
 * Workout recipes, the engine and tests reference these ids.
 */
import type { Equipment, ExerciseCategory, Intensity, Level, Participants, PhaseType, Role, Skill } from "@/lib/types";

export interface ManifestEntry {
  id: string;
  he: string;
  en: string;
  category: ExerciseCategory;
  phases: PhaseType[];
  skills: Skill[];
  roles: Role[];
  participants: Participants[];
  equipment: Equipment[];
  levels: Level[];
  intensity: Intensity;
  /** Authoring batch. */
  part: "A" | "B" | "C" | "D";
}

const ALL: Level[] = ["beginner", "intermediate", "advanced"];
const IA: Level[] = ["intermediate", "advanced"];
const SPG: Participants[] = ["solo", "pair", "group"];
const PG: Participants[] = ["pair", "group"];

export const EXERCISE_MANIFEST: ManifestEntry[] = [
  /* ---------- Part A: warm-up, cool-down, backhand/forehand/hammer basics ---------- */
  { id: "wu-dynamic-jog", he: "ריצה קלה ומוביליטי", en: "Light jog & mobility", category: "warmup", phases: ["warmup"], skills: ["warmup", "mobility"], roles: [], participants: SPG, equipment: [], levels: ALL, intensity: "low", part: "A" },
  { id: "wu-shoulder-wrist", he: "סיבובי כתפיים, מרפקים ושורש כף היד", en: "Shoulder, elbow & wrist circles", category: "warmup", phases: ["warmup"], skills: ["warmup", "mobility"], roles: [], participants: SPG, equipment: [], levels: ALL, intensity: "low", part: "A" },
  { id: "wu-hip-squat-lunge", he: "פתיחת ירכיים, סקוואט ולאנג׳", en: "Hip openers, squats & lunges", category: "warmup", phases: ["warmup"], skills: ["warmup", "mobility", "strength"], roles: [], participants: SPG, equipment: [], levels: ALL, intensity: "low", part: "A" },
  { id: "wu-high-knees-shuffle", he: "High Knees ו-Side Shuffle", en: "High knees & side shuffles", category: "warmup", phases: ["warmup"], skills: ["warmup", "footwork", "agility"], roles: [], participants: SPG, equipment: [], levels: ALL, intensity: "medium", part: "A" },
  { id: "wu-short-accelerations", he: "האצות קצרות", en: "Short accelerations", category: "warmup", phases: ["warmup"], skills: ["warmup", "acceleration", "speed"], roles: [], participants: SPG, equipment: [], levels: ALL, intensity: "medium", part: "A" },
  { id: "wu-easy-throws", he: "זריקות קלות", en: "Easy throws", category: "warmup", phases: ["warmup"], skills: ["warmup", "backhand", "forehand"], roles: [], participants: SPG, equipment: [], levels: ALL, intensity: "low", part: "A" },
  { id: "wu-ladder-warmup", he: "חימום בסולם זריזות", en: "Agility-ladder warm-up", category: "warmup", phases: ["warmup"], skills: ["warmup", "footwork", "agility"], roles: [], participants: SPG, equipment: ["ladder"], levels: ALL, intensity: "medium", part: "A" },
  { id: "wu-throwing-ladder", he: "סולם מרחקים לזריקה", en: "Throwing distance ladder", category: "warmup", phases: ["warmup"], skills: ["warmup", "backhand", "forehand", "distance"], roles: [], participants: SPG, equipment: [], levels: ALL, intensity: "low", part: "A" },
  { id: "bh-short-gate", he: "Backhand דרך שער", en: "Backhand accuracy gate", category: "throwing", phases: ["throwing"], skills: ["backhand", "accuracy", "short_throws"], roles: ["handler", "hybrid", "allround"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "low", part: "A" },
  { id: "bh-distance-ladder", he: "Backhand במרחקים עולים", en: "Backhand distance ladder", category: "throwing", phases: ["throwing"], skills: ["backhand", "distance", "deep_throws"], roles: ["handler", "wing", "hybrid", "allround"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "medium", part: "A" },
  { id: "bh-low-release", he: "Backhand בשחרור נמוך", en: "Low-release backhand", category: "throwing", phases: ["throwing"], skills: ["backhand", "break_throws", "release_speed"], roles: ["handler", "hybrid"], participants: SPG, equipment: ["cones"], levels: IA, intensity: "low", part: "A" },
  { id: "bh-pivot-throw", he: "Pivot ואז Backhand", en: "Pivot-to-backhand", category: "throwing", phases: ["throwing"], skills: ["backhand", "pivot", "footwork"], roles: ["handler", "hybrid", "allround"], participants: SPG, equipment: [], levels: ALL, intensity: "low", part: "A" },
  { id: "fh-short-gate", he: "Forehand דרך שער", en: "Forehand accuracy gate", category: "throwing", phases: ["throwing"], skills: ["forehand", "accuracy", "short_throws"], roles: ["handler", "hybrid", "allround"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "low", part: "A" },
  { id: "fh-wrist-snap", he: "Forehand – עבודת שורש כף היד", en: "Forehand wrist-snap drill", category: "throwing", phases: ["throwing"], skills: ["forehand", "release_speed", "short_throws"], roles: ["handler", "hybrid", "allround"], participants: SPG, equipment: [], levels: ALL, intensity: "low", part: "A" },
  { id: "fh-distance-ladder", he: "Forehand במרחקים עולים", en: "Forehand distance ladder", category: "throwing", phases: ["throwing"], skills: ["forehand", "distance", "deep_throws"], roles: ["handler", "wing", "hybrid", "allround"], participants: SPG, equipment: ["cones"], levels: IA, intensity: "medium", part: "A" },
  { id: "fh-release-angles", he: "Forehand בזוויות שחרור שונות", en: "Forehand release angles", category: "throwing", phases: ["throwing"], skills: ["forehand", "break_throws", "wind"], roles: ["handler", "hybrid"], participants: SPG, equipment: ["cones"], levels: IA, intensity: "low", part: "A" },
  { id: "hm-hammer-basics", he: "Hammer – יסודות", en: "Hammer fundamentals", category: "throwing", phases: ["throwing"], skills: ["hammer"], roles: ["handler", "hybrid", "allround"], participants: SPG, equipment: [], levels: IA, intensity: "low", part: "A" },
  { id: "hm-hammer-target", he: "Hammer למטרה", en: "Hammer to target", category: "throwing", phases: ["throwing"], skills: ["hammer", "accuracy"], roles: ["handler", "hybrid"], participants: SPG, equipment: ["target"], levels: ["advanced"], intensity: "low", part: "A" },

  /* ---------- Part B: mixed throwing, catching ---------- */
  { id: "th-alternating-bh-fh", he: "חילופי Backhand/Forehand", en: "Backhand–forehand alternation", category: "throwing", phases: ["throwing", "game"], skills: ["backhand", "forehand", "release_speed"], roles: ["handler", "hybrid", "allround"], participants: SPG, equipment: [], levels: ALL, intensity: "medium", part: "B" },
  { id: "th-quick-release", he: "שחרור מהיר אחרי תפיסה", en: "Catch-and-throw quick release", category: "throwing", phases: ["throwing", "game"], skills: ["release_speed", "catching", "decision_making"], roles: ["handler", "cutter", "hybrid", "allround"], participants: SPG, equipment: [], levels: ALL, intensity: "medium", part: "B" },
  { id: "th-deep-huck", he: "זריקות עומק (Huck)", en: "Deep hucks", category: "throwing", phases: ["throwing"], skills: ["deep_throws", "distance", "backhand", "forehand"], roles: ["handler", "wing", "hybrid"], participants: SPG, equipment: ["cones"], levels: IA, intensity: "medium", part: "B" },
  { id: "th-distance-max", he: "מדידת זריקה ארוכה", en: "Max-distance measurement", category: "throwing", phases: ["throwing", "challenge"], skills: ["distance", "deep_throws"], roles: [], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "medium", part: "B" },
  { id: "th-cone-corridor", he: "זריקה במסדרון קונוסים", en: "Cone-corridor throws", category: "throwing", phases: ["throwing"], skills: ["accuracy", "backhand", "forehand"], roles: [], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "low", part: "B" },
  { id: "th-target-points", he: "זריקה לנקודות מטרה", en: "Target-point throws", category: "throwing", phases: ["throwing", "challenge"], skills: ["accuracy", "short_throws"], roles: [], participants: SPG, equipment: ["target"], levels: ALL, intensity: "low", part: "B" },
  { id: "th-wind-throws", he: "זריקות ברוח", en: "Throwing in wind", category: "throwing", phases: ["throwing"], skills: ["wind", "backhand", "forehand", "accuracy"], roles: [], participants: SPG, equipment: ["cones"], levels: IA, intensity: "low", part: "B" },
  { id: "th-fake-throw", he: "Fake ואז זריקה", en: "Fake-then-throw", category: "throwing", phases: ["throwing", "role"], skills: ["fakes", "pivot", "backhand", "forehand"], roles: ["handler", "hybrid"], participants: SPG, equipment: [], levels: ALL, intensity: "low", part: "B" },
  { id: "th-break-throws", he: "Break Throws סביב מגן", en: "Break throws around a mark", category: "throwing", phases: ["throwing", "role"], skills: ["break_throws", "pivot", "backhand", "forehand"], roles: ["handler", "hybrid"], participants: SPG, equipment: ["cones"], levels: IA, intensity: "medium", part: "B" },
  { id: "th-stall-count-throws", he: "זריקות תחת Stall Count", en: "Throwing under a stall count", category: "throwing", phases: ["throwing", "game"], skills: ["decision_making", "release_speed", "backhand", "forehand"], roles: ["handler", "hybrid", "allround"], participants: SPG, equipment: [], levels: ALL, intensity: "medium", part: "B" },
  { id: "ct-two-hand-basics", he: "תפיסת Pancake ותפיסה בשתי ידיים", en: "Pancake & two-hand catching", category: "catching", phases: ["throwing", "warmup"], skills: ["catching"], roles: [], participants: SPG, equipment: [], levels: ["beginner", "intermediate"], intensity: "low", part: "B" },
  { id: "ct-one-hand", he: "תפיסות ביד אחת", en: "One-hand catches", category: "catching", phases: ["throwing", "role"], skills: ["one_hand_catch", "catching"], roles: ["cutter", "wing", "runner", "hybrid", "allround"], participants: SPG, equipment: [], levels: IA, intensity: "low", part: "B" },
  { id: "ct-catch-on-the-run", he: "תפיסות בריצה", en: "Catch on the run", category: "catching", phases: ["role", "movement", "game"], skills: ["catch_moving", "catching", "timing"], roles: ["cutter", "wing", "runner", "hybrid", "allround"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "medium", part: "B" },
  { id: "ct-catch-streak", he: "רצף תפיסות", en: "Consecutive-catch streak", category: "catching", phases: ["throwing", "challenge"], skills: ["catching"], roles: [], participants: SPG, equipment: [], levels: ALL, intensity: "low", part: "B" },
  { id: "ct-pressure-catch", he: "תפיסות תחת לחץ", en: "Catching under pressure", category: "catching", phases: ["game", "role"], skills: ["catch_pressure", "catching", "reaction"], roles: ["cutter", "wing", "runner", "hybrid", "allround"], participants: PG, equipment: [], levels: IA, intensity: "medium", part: "B" },
  { id: "ct-self-toss", he: "זריקה עצמית ותפיסה", en: "Self-toss & catch", category: "catching", phases: ["throwing", "warmup"], skills: ["catching", "one_hand_catch"], roles: [], participants: ["solo"], equipment: [], levels: ALL, intensity: "low", part: "B" },

  /* ---------- Part C: movement, game / pressure, challenges ---------- */
  { id: "mv-short-sprints", he: "ספרינטים קצרים", en: "Short sprints", category: "movement", phases: ["movement", "challenge"], skills: ["speed", "acceleration"], roles: ["runner", "wing", "cutter", "defender", "hybrid", "allround"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "high", part: "C" },
  { id: "mv-repeat-sprints", he: "ספרינטים חוזרים", en: "Repeat sprints", category: "movement", phases: ["movement"], skills: ["speed", "endurance", "acceleration"], roles: ["runner", "wing", "cutter", "hybrid"], participants: SPG, equipment: ["cones", "stopwatch"], levels: IA, intensity: "high", part: "C" },
  { id: "mv-cone-cod", he: "שינויי כיוון בין קונוסים (5-10-5)", en: "Cone change-of-direction (5-10-5)", category: "movement", phases: ["movement", "challenge"], skills: ["change_of_direction", "agility", "footwork"], roles: [], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "high", part: "C" },
  { id: "mv-t-drill", he: "T-Drill", en: "T-drill", category: "movement", phases: ["movement"], skills: ["agility", "change_of_direction", "footwork"], roles: ["defender", "cutter", "runner", "hybrid", "allround"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "high", part: "C" },
  { id: "mv-side-shuffle", he: "Side Shuffle מהיר", en: "Fast side shuffles", category: "movement", phases: ["movement", "role"], skills: ["footwork", "agility", "defense"], roles: ["defender", "hybrid", "allround"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "medium", part: "C" },
  { id: "mv-forward-backpedal", he: "קדימה ואחורה", en: "Forward & backpedal", category: "movement", phases: ["movement", "role"], skills: ["footwork", "defense", "change_of_direction"], roles: ["defender", "hybrid", "allround"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "medium", part: "C" },
  { id: "mv-reaction-signal", he: "תגובה לסימן", en: "Reaction to signal", category: "movement", phases: ["movement", "role", "game"], skills: ["reaction", "acceleration", "footwork"], roles: ["defender", "runner", "cutter", "hybrid", "allround"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "medium", part: "C" },
  { id: "mv-stop-and-go", he: "עצירה ויציאה מחדש", en: "Stop-and-go", category: "movement", phases: ["movement", "role"], skills: ["change_of_direction", "acceleration", "cutting"], roles: ["runner", "cutter", "wing", "hybrid"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "high", part: "C" },
  { id: "mv-pivot-footwork", he: "Pivot Footwork", en: "Pivot footwork", category: "movement", phases: ["movement", "role"], skills: ["pivot", "footwork", "fakes"], roles: ["handler", "hybrid", "allround"], participants: SPG, equipment: [], levels: ALL, intensity: "low", part: "C" },
  { id: "mv-ladder-agility", he: "סולם זריזות", en: "Agility-ladder patterns", category: "movement", phases: ["movement"], skills: ["agility", "footwork"], roles: [], participants: SPG, equipment: ["ladder"], levels: ALL, intensity: "medium", part: "C" },
  { id: "mv-endurance-intervals", he: "אינטרוולים לסיבולת", en: "Endurance intervals", category: "fitness", phases: ["movement"], skills: ["endurance", "speed"], roles: ["wing", "runner", "cutter", "hybrid", "allround"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "high", part: "C" },
  { id: "mv-acceleration-starts", he: "יציאה מהמקום", en: "Acceleration starts", category: "movement", phases: ["movement", "role"], skills: ["acceleration", "speed"], roles: ["runner", "cutter", "wing", "defender", "hybrid"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "high", part: "C" },
  { id: "gm-catch-release-circuit", he: "מעגל Catch & Release", en: "Catch-and-release circuit", category: "game", phases: ["game"], skills: ["release_speed", "catching", "decision_making"], roles: ["handler", "cutter", "wing", "hybrid", "allround"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "medium", part: "C" },
  { id: "gm-throw-after-sprint", he: "זריקה מיד אחרי ספרינט", en: "Throw after sprint", category: "game", phases: ["game"], skills: ["accuracy", "speed", "endurance"], roles: [], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "high", part: "C" },
  { id: "gm-error-free-sequence", he: "רצף ללא טעות", en: "Error-free sequence", category: "game", phases: ["game", "challenge"], skills: ["accuracy", "decision_making", "catching"], roles: [], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "medium", part: "C" },
  { id: "gm-fatigue-accuracy", he: "דיוק תחת עייפות", en: "Accuracy under fatigue", category: "game", phases: ["game"], skills: ["accuracy", "endurance"], roles: [], participants: SPG, equipment: ["cones"], levels: IA, intensity: "high", part: "C" },
  { id: "gm-decision-sim", he: "סימולציית החלטה", en: "Decision simulation", category: "game", phases: ["game", "role"], skills: ["decision_making", "field_vision", "reaction"], roles: ["handler", "hybrid", "allround"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "medium", part: "C" },
  { id: "gm-mini-game", he: "משחק קטן (3 על 3)", en: "Mini game (3v3)", category: "game", phases: ["game"], skills: ["decision_making", "cutting", "defense", "communication"], roles: [], participants: ["group"], equipment: ["cones"], levels: ALL, intensity: "high", part: "C" },
  { id: "gm-stall-pressure", he: "לחץ Stall Count", en: "Stall-count pressure", category: "game", phases: ["game"], skills: ["decision_making", "release_speed", "marking"], roles: ["handler", "defender", "hybrid"], participants: PG, equipment: [], levels: IA, intensity: "medium", part: "C" },
  { id: "gm-endzone-drill", he: "תרגיל End Zone", en: "End-zone drill", category: "game", phases: ["game"], skills: ["cutting", "timing", "decision_making", "communication"], roles: [], participants: ["group"], equipment: ["cones"], levels: IA, intensity: "high", part: "C" },
  { id: "ch-8-of-10", he: "8 מתוך 10 למטרה", en: "8-of-10 target hits", category: "challenge", phases: ["challenge"], skills: ["accuracy"], roles: [], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "low", part: "C" },
  { id: "ch-20-catch-streak", he: "20 תפיסות רצופות", en: "20 consecutive catches", category: "challenge", phases: ["challenge"], skills: ["catching"], roles: [], participants: SPG, equipment: [], levels: ALL, intensity: "low", part: "C" },
  { id: "ch-5-bh-5-fh", he: "5 Backhand ו-5 Forehand ברצף", en: "5 backhand + 5 forehand in a row", category: "challenge", phases: ["challenge"], skills: ["backhand", "forehand", "accuracy"], roles: [], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "low", part: "C" },
  { id: "ch-distance-pb", he: "ניסיון שיא מרחק", en: "Distance PB attempt", category: "challenge", phases: ["challenge"], skills: ["distance", "deep_throws"], roles: [], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "medium", part: "C" },
  { id: "ch-course-time", he: "מסלול נגד השעון", en: "Course against the clock", category: "challenge", phases: ["challenge"], skills: ["agility", "speed", "change_of_direction"], roles: [], participants: SPG, equipment: ["cones", "stopwatch"], levels: ALL, intensity: "high", part: "C" },
  { id: "ch-pressure-three", he: "שלוש זריקות תחת לחץ", en: "Three throws under pressure", category: "challenge", phases: ["challenge"], skills: ["accuracy", "decision_making"], roles: [], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "medium", part: "C" },
  { id: "cd-walk-breathe", he: "הליכה קלה ונשימות", en: "Easy walk & breathing", category: "cooldown", phases: ["cooldown"], skills: ["cooldown"], roles: [], participants: SPG, equipment: [], levels: ALL, intensity: "low", part: "C" },
  { id: "cd-stretch", he: "מתיחות עדינות", en: "Gentle stretches", category: "cooldown", phases: ["cooldown"], skills: ["cooldown", "mobility"], roles: [], participants: SPG, equipment: [], levels: ALL, intensity: "low", part: "C" },
  { id: "cd-reflection", he: "דירוג קושי וסיכום", en: "Rate & reflect", category: "cooldown", phases: ["cooldown"], skills: ["cooldown"], roles: [], participants: SPG, equipment: [], levels: ALL, intensity: "low", part: "C" },

  /* ---------- Part D: role-specific drills + role challenges ---------- */
  { id: "wg-sideline-runs", he: "ריצות לאורך קו הצד", en: "Sideline lane runs", category: "position", phases: ["role"], skills: ["width", "deep_runs", "timing", "endurance"], roles: ["wing"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "high", part: "D" },
  { id: "wg-deep-run-timing", he: "תזמון ריצת עומק", en: "Deep-run timing", category: "position", phases: ["role"], skills: ["deep_runs", "timing", "catch_moving"], roles: ["wing", "runner"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "high", part: "D" },
  { id: "wg-swing-pass", he: "מסירות רוחב (Swing)", en: "Swing passes", category: "position", phases: ["role", "throwing"], skills: ["width", "backhand", "forehand", "accuracy"], roles: ["wing", "handler"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "medium", part: "D" },
  { id: "wg-catch-and-continue", he: "Catch and Continue", en: "Catch and continue", category: "position", phases: ["role", "game"], skills: ["catch_moving", "transition", "release_speed"], roles: ["wing", "cutter"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "high", part: "D" },
  { id: "wg-angle-creation", he: "יצירת זווית מסירה", en: "Creating a passing angle", category: "position", phases: ["role"], skills: ["width", "field_vision", "timing"], roles: ["wing"], participants: SPG, equipment: ["cones"], levels: IA, intensity: "medium", part: "D" },
  { id: "rn-explosive-cuts", he: "Cuts חדים", en: "Explosive cuts", category: "position", phases: ["role", "movement"], skills: ["cutting", "change_of_direction", "acceleration"], roles: ["runner", "cutter"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "high", part: "D" },
  { id: "rn-deep-sprint-catch", he: "ספרינט עומק ותפיסה", en: "Deep sprint & catch", category: "position", phases: ["role"], skills: ["deep_runs", "speed", "catch_moving"], roles: ["runner", "wing"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "high", part: "D" },
  { id: "rn-tempo-change", he: "שינויי קצב", en: "Tempo changes", category: "position", phases: ["role", "movement"], skills: ["cutting", "acceleration", "separation"], roles: ["runner", "cutter"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "high", part: "D" },
  { id: "rn-catch-and-release", he: "Catch and Release בריצה", en: "Catch-and-release on the run", category: "position", phases: ["role", "game"], skills: ["catch_moving", "release_speed", "transition"], roles: ["runner", "cutter"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "high", part: "D" },
  { id: "rn-read-the-thrower", he: "קריאת תנועת המוסר", en: "Reading the thrower", category: "position", phases: ["role"], skills: ["timing", "reaction", "cutting"], roles: ["runner", "cutter"], participants: SPG, equipment: ["cones"], levels: IA, intensity: "medium", part: "D" },
  { id: "df-mirror-drill", he: "Mirror Drill", en: "Mirror drill", category: "defense", phases: ["role", "movement"], skills: ["mirror", "defense", "reaction", "footwork"], roles: ["defender", "hybrid", "allround"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "high", part: "D" },
  { id: "df-lateral-defense", he: "עבודת רגליים הגנתית", en: "Defensive footwork", category: "defense", phases: ["role", "movement"], skills: ["defense", "footwork", "agility"], roles: ["defender", "hybrid", "allround"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "medium", part: "D" },
  { id: "df-mark-drill", he: "תרגיל Mark", en: "Mark drill", category: "defense", phases: ["role"], skills: ["marking", "defense", "footwork"], roles: ["defender", "hybrid", "allround"], participants: SPG, equipment: [], levels: ALL, intensity: "medium", part: "D" },
  { id: "df-recovery-sprint", he: "Recovery Sprint", en: "Recovery sprint", category: "defense", phases: ["role", "movement"], skills: ["defense", "speed", "transition"], roles: ["defender", "hybrid"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "high", part: "D" },
  { id: "df-deny-deep", he: "מניעת ריצת עומק", en: "Deny the deep", category: "defense", phases: ["role"], skills: ["defense", "deep_runs", "reaction", "footwork"], roles: ["defender"], participants: SPG, equipment: ["cones"], levels: IA, intensity: "high", part: "D" },
  { id: "df-fake-reaction", he: "תגובה ל-Fake", en: "Reacting to fakes", category: "defense", phases: ["role"], skills: ["defense", "reaction", "footwork"], roles: ["defender"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "medium", part: "D" },
  { id: "hd-give-and-go", he: "Give and Go", en: "Give and go", category: "position", phases: ["role", "game"], skills: ["give_and_go", "release_speed", "catch_moving"], roles: ["handler", "hybrid"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "medium", part: "D" },
  { id: "hd-pivot-fake-throw", he: "Pivot–Fake–זריקה", en: "Pivot–fake–throw combos", category: "position", phases: ["role", "throwing"], skills: ["pivot", "fakes", "backhand", "forehand"], roles: ["handler", "hybrid", "allround"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "low", part: "D" },
  { id: "hd-break-side", he: "זריקות ל-Break Side", en: "Break-side throws", category: "position", phases: ["role"], skills: ["break_throws", "pivot", "backhand", "forehand"], roles: ["handler", "hybrid"], participants: SPG, equipment: ["cones"], levels: IA, intensity: "medium", part: "D" },
  { id: "hd-two-target-decision", he: "החלטה בין שתי מטרות", en: "Two-target decision", category: "position", phases: ["role", "game"], skills: ["decision_making", "field_vision", "accuracy"], roles: ["handler", "hybrid", "allround"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "medium", part: "D" },
  { id: "hd-quick-swing", he: "מסירות קצרות ומהירות", en: "Quick short passes", category: "position", phases: ["role", "throwing"], skills: ["short_throws", "release_speed", "backhand", "forehand"], roles: ["handler", "hybrid"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "medium", part: "D" },
  { id: "cu-in-deep-cut", he: "In-Cut ואז Deep Cut", en: "In-cut to deep-cut", category: "position", phases: ["role", "movement"], skills: ["cutting", "change_of_direction", "timing"], roles: ["cutter", "runner", "hybrid"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "high", part: "D" },
  { id: "cu-separation", he: "יצירת הפרדה מהמגן", en: "Separation drill", category: "position", phases: ["role"], skills: ["separation", "cutting", "acceleration"], roles: ["cutter", "runner", "wing"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "high", part: "D" },
  { id: "cu-clear-out", he: "Clear Out וחזרה למבנה", en: "Clear out & reset", category: "position", phases: ["role"], skills: ["cutting", "field_vision", "communication"], roles: ["cutter", "hybrid", "allround"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "medium", part: "D" },
  { id: "cu-cut-timing", he: "תזמון Cut מול Handler", en: "Cut timing with a handler", category: "position", phases: ["role", "game"], skills: ["timing", "cutting", "communication", "catch_moving"], roles: ["cutter", "hybrid", "allround"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "high", part: "D" },
  { id: "ch-role-wing", he: "אתגר כנף", en: "Wing challenge", category: "challenge", phases: ["challenge"], skills: ["catch_moving", "deep_runs", "width"], roles: ["wing"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "high", part: "D" },
  { id: "ch-role-runner", he: "אתגר רץ", en: "Runner challenge", category: "challenge", phases: ["challenge"], skills: ["speed", "change_of_direction", "catch_moving"], roles: ["runner"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "high", part: "D" },
  { id: "ch-role-defender", he: "אתגר מגן", en: "Defender challenge", category: "challenge", phases: ["challenge"], skills: ["mirror", "reaction", "defense"], roles: ["defender"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "high", part: "D" },
  { id: "ch-role-handler", he: "אתגר Handler", en: "Handler challenge", category: "challenge", phases: ["challenge"], skills: ["backhand", "forehand", "break_throws", "decision_making"], roles: ["handler"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "medium", part: "D" },
  { id: "ch-role-cutter", he: "אתגר Cutter", en: "Cutter challenge", category: "challenge", phases: ["challenge"], skills: ["cutting", "separation", "catch_moving"], roles: ["cutter"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "high", part: "D" },
  { id: "ch-role-hybrid", he: "אתגר היברידי", en: "Hybrid challenge", category: "challenge", phases: ["challenge"], skills: ["backhand", "forehand", "cutting", "defense"], roles: ["hybrid", "allround"], participants: SPG, equipment: ["cones"], levels: ALL, intensity: "high", part: "D" },
];

export const EXERCISE_IDS = EXERCISE_MANIFEST.map((e) => e.id);
