import type { GameLocale, GameMode } from "@/lib/game";
const he = {
  progress: "התקדמות במשחק", collapseQuestion: "צמצום השאלה לפינוי הזירה", expandQuestion: "הרחבת השאלה והתשובות", expandToChoose: "פתחו את השאלה כדי לבחור תשובה", chooseBeforeSubmit: "בחרו תשובה לפני השליחה.", seeResults: "לתוצאות המשחק", shieldHit: "המגן נפגע. זוזו אל המחסה.", shieldRecovered: "המגן התחזק", tutorialMove: "זזים בין המחסות", tutorialMoveHint: "הג׳ויסטיק מזיז את הדמות לכל כיוון.", tutorialAim: "בוחרים תשובה ומכוונים", tutorialAimHint: "סמנו גביש ולחצו ירי. גרירה מכוונת ידנית.", tutorialDash: "מתחמקים מהתקפה", tutorialDashHint: "זינוק קצר עוזר לחצות את הזירה בבטחה.",
  arenaBlocked: "המחסה חוסם את הירי. זוזו מעט הצידה ונסו שוב.", arenaReady: "הגביש מסומן. לחצו על ירי כדי לבחור בתשובה.",
  askAI: "שאלה למאמן AI", fire: "ירי אנרגיה", fireHint: "החזיקו לירי · גררו לכיוון", dash: "זינוק", dashReady: "זינוק מוכן", arenaHealth: "מגן הדמות", arenaEnemies: "רובוטים בזירה", arenaCrystals: "גבישים נאספו", arenaWave: "גל", arenaSelect: "בחרו תשובה ואז ירו לעבר הגביש שלה", arenaControls: "WASD או חצים לתנועה · E לירי · רווח לזינוק · 1–4 לבחירת גביש", arenaMobileControls: "אגודל שמאל לתנועה. החזיקו את כפתור הירי לכיוון אוטומטי או גררו כדי לכוון. זינוק עוזר לעבור בין מחסות.", arenaAnswerHint: "הכפתורים מסמנים גביש בזירה. ירי שפוגע בגביש שולח את התשובה. אם מחסה חוסם את הדרך, זוזו מעט הצידה.",
  demo: "Demo · נתוני תרגול",
  loading: "טוען את עולם המשחק", loadingAsset: "טוען את הדמות", ready: "מכין את הסצנה", exit: "יציאה מהמשחק", pause: "עצירת המשחק", resume: "חזרה למשחק", paused: "המשחק מושהה", pauseNote: "העולם מושהה. הזמן היומי ממשיך להיספר בשרת.",
  score: "ניקוד", time: "זמן שנותר", question: "שאלה", of: "מתוך", combo: "רצף", interact: "פעולה", jump: "קפיצה", sound: "צלילים", mute: "כיבוי צלילים", tutorial: "איך משחקים?", close: "סגירה", begin: "קדימה, למסע", correct: "נכון. ממשיכים!", incorrect: "הזדמנות ללמוד", next: "המשך", retry: "ניסיון שמירה נוסף", saving: "שומר את ההתקדמות", networkError: "התשובה עדיין לא נשמרה. בדקו את החיבור ונסו שוב; ההתקדמות נשמרת במכשיר.", finishError: "התוצאה עדיין לא נשמרה בשרת. אפשר לנסות שוב.",
  controls: "WASD או חצים לתנועה · רווח לקפיצה · E לפעולה · גרירת עכבר למצלמה · Esc לעצירה", mobileControls: "הזיזו את הג׳ויסטיק לתנועה. גררו על העולם לסיבוב המצלמה. השתמשו בכפתורים לקפיצה ולפעולה.",
  select: "בחירה", confirm: "אישור הבחירה", inspect: "בדיקת החפץ", selected: "נבחר", moveNear: "התקרבו לחפץ המואר ולחצו פעולה",
  fallbackTitle: "מצב משחק נגיש בדו־ממד", fallbackBody: "תצוגת 3D אינה זמינה במכשיר הזה. אותן שאלות, אותה שמירה ואותם פרסים זמינים גם כאן.", fallbackSwitch: "מעבר למצב דו־ממד", contextLost: "תצוגת התלת־ממד הופסקה. ההתקדמות נשמרה; אפשר להמשיך בדו־ממד.",
  low: "איכות מותאמת למכשיר", keyboard: "ניתן לשחק גם עם המקלדת", finished: "המסע הושלם", door: "פתחו את דלת היציאה", doorOpen: "הדלת נפתחה", drawer: "מסוף חידות", crate: "פריט", deliver: "אספתם פריט. החזירו אותו למשטח המיון שבמרכז", build: "בחרו את השלב הבא והניחו אותו בגשר", boss: "אנרגיית הבוס", dodge: "התחמקו הצידה מהגל!", phase: "שלב", shield: "מגן נאסף", hint: "הצגת רמז", questionHint: "רמז לשאלה הזו", hintText: "קראו שוב את השאלה, פסלו תשובה שאינה מתאימה וחשבו על המשימה האחרונה במסלול.",
  health: "מגנים", finish: "שמירת התוצאה", deadline: "הזמן הסתיים. שומרים את מה שהספקתם.", tutorialTitle: "המשימה שלכם", help: "עזרה", canvas: "עולם המשחק התלת־ממדי. ההוראות ואפשרויות התשובה מופיעות גם מחוץ לקנבס.", joystick: "ג׳ויסטיק תנועה", chooser: "אפשרויות תשובה", return: "חזרה לאתגר", error: "לא ניתן לטעון את המשחק", unready: "המתינו לטעינה", leaveTitle: "לצאת מהמשחק?", leaveBody: "התשובות שנשלחו שמורות. יציאה צורכת את הניסיון שהתחלתם.", leaveConfirm: "יציאה", music: "מוזיקה", effects: "אפקטים", visit: "התקרבות", carry: "איסוף הפריט הנבחר", deliverAction: "מיון הפריט", bridge: "הנחת המקטע", gate: "מעבר לשער הנבחר", station: "פתיחת מסוף", dodgeButton: "התחמקות", noHint: "ללא רמזים", saved: "נשמר בשרת", connection: "מחכים לחיבור כדי לשמור", fallbackAction: "שליחת תשובה", inspectHint: "בחרו חפץ בעולם או השתמשו בחצים כדי להגיע אליו.",
};
const en: typeof he = {
  progress: "Quest progress", collapseQuestion: "Minimize question to reveal the arena", expandQuestion: "Expand question and answers", expandToChoose: "Open the question to choose an answer", chooseBeforeSubmit: "Choose an answer before submitting.", seeResults: "View game results", shieldHit: "Shield hit. Move into cover.", shieldRecovered: "Shield restored", tutorialMove: "Move between cover", tutorialMoveHint: "Use the joystick to move in any direction.", tutorialAim: "Choose an answer and aim", tutorialAimHint: "Select a crystal and fire. Drag to aim manually.", tutorialDash: "Dodge the attack", tutorialDashHint: "A quick dash helps you cross the arena safely.",
  arenaBlocked: "Cover blocks your shot. Move a little sideways and try again.", arenaReady: "Crystal selected. Press fire to choose this answer.",
  askAI: "Ask the AI coach", fire: "Energy shot", fireHint: "Hold to fire · drag to aim", dash: "Dash", dashReady: "Dash ready", arenaHealth: "Explorer shield", arenaEnemies: "Robots in arena", arenaCrystals: "Crystals collected", arenaWave: "Wave", arenaSelect: "Select an answer, then shoot its crystal", arenaControls: "WASD or arrows to move · E to fire · Space to dash · 1–4 to choose a crystal", arenaMobileControls: "Move with your left thumb. Hold the fire button for auto-aim, or drag to aim manually. Dash between cover.", arenaAnswerHint: "Answer buttons select a crystal in the arena. Hit that crystal with a shot to submit. If cover blocks your line, move sideways.",
  demo: "Demo · practice data",
  loading: "Loading your world", loadingAsset: "Loading the explorer", ready: "Preparing the scene", exit: "Exit game", pause: "Pause game", resume: "Resume game", paused: "Game paused", pauseNote: "The world is paused. The daily timer continues on the server.",
  score: "Score", time: "Time left", question: "Question", of: "of", combo: "Streak", interact: "Interact", jump: "Jump", sound: "Sound", mute: "Mute sounds", tutorial: "How to play", close: "Close", begin: "Start exploring", correct: "Correct. Keep going!", incorrect: "A chance to learn", next: "Continue", retry: "Retry saving", saving: "Saving your progress", networkError: "Your answer has not been saved yet. Check your connection and retry; progress is stored on this device.", finishError: "Your result has not been saved to the server yet. Please retry.",
  controls: "WASD or arrows to move · Space to jump · E to interact · Drag to turn camera · Esc to pause", mobileControls: "Move with the joystick. Drag the world to turn your camera. Use the jump and interact buttons.",
  select: "Choose", confirm: "Confirm choice", inspect: "Inspect object", selected: "Selected", moveNear: "Approach the lit object and press Interact",
  fallbackTitle: "Accessible 2D game mode", fallbackBody: "3D is unavailable on this device. The same questions, saved progress and rewards are available here.", fallbackSwitch: "Switch to 2D mode", contextLost: "The 3D view stopped. Your progress is saved; continue in 2D.",
  low: "Graphics adapted to your device", keyboard: "You can also play using your keyboard", finished: "Quest complete", door: "Open the exit door", doorOpen: "The door is open", drawer: "Puzzle terminal", crate: "Item", deliver: "You picked up an item. Bring it to the sorting pad in the center", build: "Choose the next step and place it in your bridge", boss: "Boss energy", dodge: "Dodge the wave by moving sideways!", phase: "Phase", shield: "Shield collected", hint: "Show a hint", questionHint: "Hint for this question", hintText: "Read the question again, eliminate an unsuitable option, and remember the last task on your learning path.",
  health: "Shields", finish: "Save result", deadline: "Time is up. Saving what you completed.", tutorialTitle: "Your mission", help: "Help", canvas: "The 3D game world. Instructions and answer options also appear outside the canvas.", joystick: "Movement joystick", chooser: "Answer options", return: "Return to quest", error: "Unable to load game", unready: "Please wait for loading", leaveTitle: "Leave this game?", leaveBody: "Submitted answers are saved. Leaving uses the attempt you started.", leaveConfirm: "Leave game", music: "Music", effects: "Effects", visit: "Approach", carry: "Collect selected item", deliverAction: "Deliver item", bridge: "Place bridge section", gate: "Move to selected gate", station: "Open terminal", dodgeButton: "Dodge", noHint: "No hints used", saved: "Saved to server", connection: "Waiting for a connection to save", fallbackAction: "Submit answer", inspectHint: "Select an object in the world or use the arrow keys to reach it.",
};
export const gameMessages = { he, en };
export const modeSummaries: Record<GameMode, Record<GameLocale, string>> = {
  "knowledge-arena": { he: "זזים, מתחמקים ופוגעים בתשובה הנכונה.", en: "Move, dodge and hit the correct answer." },
  "answer-gates": { he: "רצים במסלול, קופצים מעל מכשולים ובוחרים את שער התשובה.", en: "Run, jump over obstacles and choose an answer gate." },
  "escape-room": { he: "מגלים מסופים, פותרים חידות ומשחררים את מנעולי הדלת.", en: "Discover terminals, solve puzzles and release the door locks." },
  "collect-sort": { he: "אוספים את הפריט המתאים ומביאים אותו למשטח המיון.", en: "Collect the right item and bring it to the sorting pad." },
  "build-path": { he: "בוחרים את השלב הבא ובונים גשר בין האיים.", en: "Choose the next step and build a bridge between islands." },
  "boss-quiz": { he: "פותרים שאלות, מתחמקים מגלי אנרגיה ומחלישים את הבוס.", en: "Answer questions, dodge energy waves and weaken the boss." },
};
export const modeInstructions: Record<GameMode, Record<GameLocale, string>> = {
  "knowledge-arena": { he: "הזיזו את הדמות בין המחסות, ירו ברובוטים ואספו גבישי מגן. קראו את השאלה, בחרו תשובה וירו בגביש הממוספר שלה. פתרון נכון בונה את שער היציאה; טעות מפעילה גל שאפשר להתחמק ממנו. רק תשובות מעניקות ניקוד לימודי.", en: "Move between cover, zap robots and collect shield crystals. Read the question, choose an answer and shoot its numbered crystal. Correct answers build the exit gate; mistakes trigger a wave you can dodge. Only answers earn learning points." },
  "answer-gates": { he: "בחרו שער עם התשובה הנכונה. הרובוט מתקדם בעצמו; חצים או בחירה בתשובה משנים נתיב. קפצו מעל המכשולים בדרך.", en: "Choose the gate with the right answer. Your robot runs forward; use arrows or select an answer to change lanes. Jump over obstacles." },
  "escape-room": { he: "חפשו את המסוף המואר בחדר, התקרבו ולחצו E או על המסוף. פתרו את החידות כדי לגלות את הקוד ולפתוח את הדלת.", en: "Find the lit terminal, approach and press E or select it. Solve its puzzles to discover the code and open the exit door." },
  "collect-sort": { he: "אספו את הפריט עם התשובה הנכונה והביאו אותו למשטח המיון שבמרכז. אפשר לבחור פריט מהתפריט כדי להתקרב אליו.", en: "Collect the item with the correct answer and carry it to the sorting pad in the center. Select an item below to approach it." },
  "build-path": { he: "בכל צומת בחרו את השלב המתאים. התקרבו למקטע ולחצו פעולה כדי להניח אותו. כל פתרון פותח חלק נוסף בגשר.", en: "Choose the correct step at each junction. Approach a section and interact to place it. Each solution opens another part of your bridge." },
  "boss-quiz": { he: "התקרבו לעמוד התשובה הנכונה והפעילו אותו כדי להחליש את הבוס. אחרי טעות התחמקו מהגל הצבעוני ואספו מגן מהזירה.", en: "Approach and activate the correct answer pillar to weaken the boss. After a mistake, dodge its colorful wave and collect a shield in the arena." },
};
